import { createHash } from 'node:crypto';
import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';

type Document = { openapi: string; info: { title: string; version: string }; paths: Record<string, Record<string, Record<string, any>>> };
type Service = 'inference' | 'training' | 'lab' | 'qualification';

process.env.NODE_ENV = 'test';
const [{ inferenceOpenApi }, { trainingOpenApi }, { labOpenApi }, { managerOpenApi }] = await Promise.all([
	import('../../packages/inference-api/src/app.ts'), import('../../packages/training-api/src/app.ts'),
	import('../../packages/lab/src/controller.ts'), import('../../packages/manager/src/http/api.ts'),
]);

function canonical(value: unknown): string {
	if (Array.isArray(value)) return `[${value.map(canonical).join(',')}]`;
	if (value && typeof value === 'object') return `{${Object.entries(value as Record<string, unknown>).sort(([a], [b]) => a.localeCompare(b)).map(([key, child]) => `${JSON.stringify(key)}:${canonical(child)}`).join(',')}}`;
	return JSON.stringify(value);
}

function digest(value: unknown) { return `sha256:${createHash('sha256').update(canonical(value)).digest('hex')}`; }
function generatedId(service: Service, method: string, path: string) {
	return [service, method.toLowerCase(), ...path.replace(/^\/v1\//u, '').replace(/^\//u, '').split('/').filter(Boolean).map((part) => part.replaceAll(/[{}]/gu, '').replace(/^:/u, '').replaceAll(/[^a-zA-Z0-9-]/gu, '-'))].join('.');
}

function normalize(service: Service, document: Document): Document {
	document = JSON.parse(JSON.stringify(document)) as Document;
	for (const [path, methods] of Object.entries(document.paths)) for (const [method, operation] of Object.entries(methods)) operation.operationId ??= generatedId(service, method, path);
	return document;
}

const rawQualification = managerOpenApi() as Document;
const qualificationPaths = Object.fromEntries(Object.entries(rawQualification.paths).filter(([path]) => [
	'/healthz', '/readyz', '/v1/version', '/v1/status', '/v1/mode', '/v1/events/stream', '/v1/metrics',
].includes(path) || path.startsWith('/v1/qualification/') || path.startsWith('/v1/transitions/')));
const documents: Record<Service, Document> = {
	inference: normalize('inference', inferenceOpenApi() as Document),
	training: normalize('training', trainingOpenApi() as Document),
	lab: normalize('lab', labOpenApi() as Document),
	qualification: normalize('qualification', { ...rawQualification, info: { title: 'TreeAI Qualification and Mode API', version: '0.11.0' }, paths: qualificationPaths }),
};

const operations = Object.entries(documents).flatMap(([service, document]) => Object.entries(document.paths).flatMap(([path, methods]) => Object.entries(methods).map(([method, operation]) => ({
	service, operationId: operation.operationId as string, method: method.toUpperCase(), path, summary: operation.summary ?? operation.operationId,
	scopes: (operation.security?.[0]?.apiKey ?? []) as string[], kind: method.toUpperCase() === 'GET' ? 'read' : 'mutation',
})))).sort((left, right) => left.operationId.localeCompare(right.operationId));
const ids = new Set<string>();
for (const operation of operations) {
	if (ids.has(operation.operationId)) throw new Error(`Duplicate TreeAI operation ID ${operation.operationId}.`);
	ids.add(operation.operationId);
}

const root = resolve('packages/treeai-sdk');
mkdirSync(resolve(root, 'openapi'), { recursive: true });
mkdirSync(resolve(root, 'src/generated'), { recursive: true });
for (const [service, document] of Object.entries(documents)) writeFileSync(resolve(root, `openapi/${service}.json`), `${JSON.stringify(document, null, 2)}\n`);
const inventory = { schemaVersion: 'treeai.operation-inventory/v1', version: '0.11.0', operations };
writeFileSync(resolve(root, 'operation-inventory.json'), `${JSON.stringify(inventory, null, 2)}\n`);
const contracts = Object.fromEntries(Object.entries(documents).map(([service, document]) => [service, { openapiVersion: document.openapi, digest: digest(document) }]));
const source = `// Generated by scripts/sdk/generate-contracts.ts.\nexport const TREEAI_CONTRACT_VERSION = '0.11.0' as const;\nexport const TREEAI_OPENAPI_CONTRACTS = ${JSON.stringify(contracts, null, 2)} as const;\nexport const TREEAI_OPERATION_INVENTORY_DIGEST = '${digest(inventory)}' as const;\nexport const TREEAI_OPERATIONS = ${JSON.stringify(operations, null, 2)} as const;\nexport type TreeAiOperation = typeof TREEAI_OPERATIONS[number];\nexport type TreeAiOperationId = TreeAiOperation['operationId'];\n`;
writeFileSync(resolve(root, 'src/generated/contract.ts'), source);
console.log(JSON.stringify({ status: 'ready', services: Object.keys(documents), operations: operations.length, inventoryDigest: digest(inventory), contracts }));
