import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest';import{transportError}from'../../packages/cli/src/client.js';
describe('treeai 0.6 packaging contracts',()=>{
  it('centralizes bootstrap and managed packages',()=>{const release=JSON.parse(readFileSync('release/manifest.json','utf8'));expect(release.version).toBe('0.8.0');expect(release.debianVersion).toBe('0.8.0-1');expect(release.products[0]).toBe('bootstrap');expect(release.products).toContain('manager');expect(release.products).toContain('host-js-runtime');expect(release.images).toHaveLength(15);expect(release.changedImages).toEqual(['lab-controller','lab-experience-proxy','hermes-agent','lab-web-tool-proxy']);});
  it('uses descriptor ABI v2 with compatibility ranges',()=>{const source=readFileSync('packages/cli/src/descriptors.ts','utf8');expect(source).toContain('stat.uid!==0');expect(source).toContain('stat.mode&0o022');expect(source).toContain('value.executable!==executables[group]');for(const group of['host','platform','update','mode','config','recovery','inference','training','lab']){const descriptor=JSON.parse(readFileSync(`deploy/commands/${group}.json`,'utf8'));expect(descriptor.schemaVersion).toBe('treeai.command-descriptor/v2');expect(descriptor.abi).toBe(2);expect(descriptor.cliRange).toBeTruthy();}});
  it('packages Hermes as a first-class lab command',()=>{const descriptor=JSON.parse(readFileSync('deploy/commands/lab.json','utf8'));expect(descriptor.commands).toContain('hermes');expect(readFileSync('packages/lab/src/cli.ts','utf8')).toContain('treeai lab hermes <status|tools|sessions|verify|rotate-password>');});
  it('publishes only treeai as a public executable',()=>{const packaging=readFileSync('scripts/package-deb.ts','utf8');expect(packaging).toMatch(/["']usr\/bin\/treeai["']/u);expect(packaging).not.toMatch(/["']usr\/bin\/ai-factory-dev["']/u);expect(packaging).not.toMatch(/["']usr\/bin\/ai-factory-lab["']/u);});
  it('uses the private runtime without exact CLI coupling',()=>{for(const product of['host-runtime','inference','training','lab']){const control=readFileSync(`debian/${product}/control`,'utf8');expect(control).toContain('treeseed-ai-host-js-runtime (>= 0.6.0)');expect(control).not.toContain('treeseed-ai-cli (=');}});
  it('keeps publication manual and protected',()=>{const value=readFileSync('.github/workflows/release.yml','utf8');expect(value).toContain('workflow_dispatch:');expect(value).not.toMatch(/^\s+push:/mu);expect(value).toContain('environment: production');expect(value).not.toContain(':latest');});
  it('installs release-script dependencies before publishing',()=>{for(const path of['.github/workflows/release.yml','.github/workflows/repair-release.yml']){const value=readFileSync(path,'utf8'),job=value.split('  github-release:')[1]?.split('  apt-repository:')[0]??'';expect(job).toContain('pnpm/action-setup@v4');expect(job).toContain('actions/setup-node@v4');expect(job).toContain('pnpm install --frozen-lockfile');}});
  it('uses conventional Debian source packaging',()=>{expect(readFileSync('debian/rules','utf8')).toContain('dh $@');expect(readFileSync('debian/source/format','utf8')).toContain('3.0 (quilt)');expect(readFileSync('debian/changelog','utf8')).toMatch(/^treeseed-ai \([^)]+\) (stable|development); urgency=(low|medium|high|critical)$/mu);});
  it('keeps bootstrap APT state generated rather than package-owned',()=>{const packaging=readFileSync('scripts/package-deb.ts','utf8');expect(packaging).not.toContain('"etc/apt/keyrings"');expect(packaging).not.toContain('"etc/apt/preferences.d"');expect(readFileSync('scripts/bootstrap/bootstrap.sh','utf8')).toContain('/usr/share/treeseed-ai/bootstrap/preferences');});
  it('ships only the private Node executable payload',()=>{const packaging=readFileSync('scripts/package-deb.ts','utf8');for(const path of['include','lib','share','bin/corepack','bin/npm','bin/npx'])expect(packaging).toContain(`"${path}"`);expect(readFileSync('debian/treeseed-ai-host-js-runtime.lintian-overrides','utf8')).toContain('embedded-library zlib');});
  it('continues selective role image planning',()=>{const workflow=readFileSync('.github/workflows/release.yml','utf8');expect(workflow).toContain('resolve-images:');expect(workflow).toContain("if: matrix.action == 'built'");expect(workflow).toContain('image-plan.json');});
  it('redacts command arguments from transport failures',()=>{const error=transportError({message:'curl -H Authorization: Bearer secret-value',stderr:'curl: (22) server returned 500',status:22},'https://host/v1/status');expect(error.message).toContain('server returned 500');expect(error.message).not.toContain('secret-value');expect(error.message).not.toContain('Authorization');});
  it('redacts credentials repeated by nested API errors',()=>{const error=transportError({stderr:'curl: (22) server returned 500',stdout:'{"message":"Authorization: Bearer ak_treeai-operator_abcdefghijklmnopqrstuvwxyz"}',status:22},'https://host/v1/status');expect(error.message).toContain('[REDACTED]');expect(error.message).not.toContain('abcdefghijklmnopqrstuvwxyz');expect(error.message).not.toContain('Authorization');});
  it('repairs local build receipt access during manager upgrades',()=>{const postinst=readFileSync('debian/manager/postinst','utf8');expect(postinst).toContain('local-build-receipt.json');expect(postinst).toContain('root:treeseed-ai-manager');expect(postinst).toContain('chmod 0640');});
});
