import{mkdtempSync,readFileSync,statSync,writeFileSync}from'node:fs';import{tmpdir}from'node:os';import{PassThrough}from'node:stream';import{join}from'node:path';import{describe,expect,it,vi}from'vitest';import{collectR2Environment,configureR2,hiddenQuestion,stageR2Environment}from'../../../packages/manager/src/lifecycle/storage/index.js';
const input={TREEAI_R2_ENDPOINT:'https://account.r2.cloudflarestorage.com',TREEAI_R2_TRAINING_BUCKET:'treeai-training',TREEAI_R2_INFERENCE_BUCKET:'treeai-inference',TREEAI_R2_TRAINING_ACCESS_KEY_ID:'training-access',TREEAI_R2_TRAINING_SECRET_ACCESS_KEY:'training-secret',TREEAI_R2_INFERENCE_ACCESS_KEY_ID:'inference-access',TREEAI_R2_INFERENCE_SECRET_ACCESS_KEY:'inference-secret',TREEAI_R2_IMPORT_ACCESS_KEY_ID:'import-access',TREEAI_R2_IMPORT_SECRET_ACCESS_KEY:'import-secret'};
function fixture(){const root=mkdtempSync(join(tmpdir(),'treeai-storage-')),inputPath=join(root,'input.json'),storage=join(root,'storage'),state=join(root,'state');writeFileSync(inputPath,JSON.stringify(input),{mode:0o600});return{root,inputPath,storage,state};}
function factory(){const objects=new Map<string,Uint8Array>();return((_storeId:string,bucket:string,_endpoint:string,_access:string,_secret:string)=>({put:async(key:string,body:Uint8Array)=>{objects.set(`${bucket}/${key}`,body);return{uri:`artifact://${bucket==='treeai-training'?'training':'inference'}/${key}`,key,size:body.byteLength,sha256:'0'.repeat(64)};},bytes:async(uri:string)=>{const[,store,key]=uri.match(/^artifact:\/\/([^/]+)\/(.+)$/u)??[];return objects.get(`${store==='training'?'treeai-training':'treeai-inference'}/${key}`)??new Uint8Array();}}))as never;}
describe('R2 storage configuration',()=>{
	it('uses complete environment input without prompting',async()=>{const ask=vi.fn();expect(await collectR2Environment(input,ask)).toEqual(input);expect(ask).not.toHaveBeenCalled();});
	it('prompts only for missing values and hides secret-key answers',async()=>{const partial={...input,TREEAI_R2_INFERENCE_ACCESS_KEY_ID:'',TREEAI_R2_IMPORT_SECRET_ACCESS_KEY:undefined},ask=vi.fn(async(label:string,secret:boolean)=>label.startsWith('Inference access')&&!secret?'prompted-access':'prompted-secret');const result=await collectR2Environment(partial,ask);expect(result.TREEAI_R2_INFERENCE_ACCESS_KEY_ID).toBe('prompted-access');expect(result.TREEAI_R2_IMPORT_SECRET_ACCESS_KEY).toBe('prompted-secret');expect(ask.mock.calls).toEqual([['Inference access key ID',false],['Import secret access key',true]]);});
	it('re-prompts when interactive input is empty',async()=>{const values=['  ','new-secret'],ask=vi.fn(async()=>values.shift()??'');const result=await collectR2Environment({...input,TREEAI_R2_TRAINING_SECRET_ACCESS_KEY:''},ask);expect(result.TREEAI_R2_TRAINING_SECRET_ACCESS_KEY).toBe('new-secret');expect(ask).toHaveBeenCalledTimes(2);});
	it('restores a paused terminal after reading a hidden value',async()=>{const terminal=Object.assign(new PassThrough(),{isTTY:true,isRaw:false,setRawMode(mode:boolean){this.isRaw=mode;return this;}}),output=Object.assign(new PassThrough(),{isTTY:true});terminal.pause();const answer=hiddenQuestion('Secret',terminal as unknown as NodeJS.ReadStream,output as unknown as NodeJS.WriteStream);terminal.write('protected\r');await expect(answer).resolves.toBe('protected');expect(terminal.isRaw).toBe(false);expect(terminal.isPaused()).toBe(true);expect(output.read()?.toString()).toBe('Secret: \n');});
	it('reports a non-interactive fallback when values are missing',async()=>{await expect(collectR2Environment({...input,TREEAI_R2_ENDPOINT:''})).rejects.toThrow(/interactive terminal.*TREEAI_R2_/u);});
	it('requires local root before staging credentials',()=>{if(process.getuid?.()!==0)expect(()=>stageR2Environment(input)).toThrow(/root/u);});
	it('probes all capabilities and atomically stores only protected secrets',async()=>{const value=fixture(),emit=vi.fn(),receipt=await configureR2({inputPath:value.inputPath,root:value.storage,stateRoot:value.state,factory:factory(),emit});expect(receipt).toMatchObject({status:'ready',backend:'r2'});expect(()=>readFileSync(value.inputPath)).toThrow();const current=join(value.storage,'current');for(const name of['training-access-key','training-secret-key','inference-access-key','inference-secret-key','import-access-key','import-secret-key'])expect(statSync(join(current,name)).mode&0o777).toBe(0o600);const config=readFileSync(join(current,'config.json'),'utf8'),storedReceipt=readFileSync(join(value.state,'storage-receipt.json'),'utf8');for(const secret of['training-secret','inference-secret','import-secret']){expect(config).not.toContain(secret);expect(storedReceipt).not.toContain(secret);}expect(emit).toHaveBeenCalledWith('storage.configured',expect.objectContaining({backend:'r2'}));});
	it('does not activate configuration when connectivity fails',async()=>{const value=fixture(),broken=(()=>({put:async()=>{throw new Error('unavailable');},bytes:async()=>new Uint8Array()}))as never;await expect(configureR2({inputPath:value.inputPath,root:value.storage,stateRoot:value.state,factory:broken,emit:vi.fn()})).rejects.toThrow('unavailable');expect(()=>readFileSync(join(value.storage,'current'))).toThrow();expect(()=>readFileSync(value.inputPath)).toThrow();});
});
