import{mkdtempSync,readFileSync,rmSync}from'node:fs';import{spawnSync}from'node:child_process';import{tmpdir}from'node:os';import{join}from'node:path';
const root=process.cwd(),manifest=JSON.parse(readFileSync(`${root}/release/manifest.json`,'utf8'))as{schemaVersion:string;version:string;dockerNamespace:string;products:string[];functionalProducts:string[];images:string[];apt:{fingerprintFile:string}};
function assert(value:unknown,message:string):asserts value{if(!value)throw new Error(message);}
assert(manifest.schemaVersion==='treeai.release/v1','Invalid release manifest schema.');assert(/^\d+\.\d+\.\d+$/u.test(manifest.version),'Release version must be semantic.');assert(manifest.dockerNamespace==='treeseed','Docker namespace must remain treeseed.');assert(new Set(manifest.images).size===14,'Exactly fourteen unique role images are required.');
for(const product of manifest.products){const control=`${root}/debian/${product}/control`;assert(readFileSync(control,'utf8').includes(`Version: ${manifest.version}`),`${product} control version drifted.`);}
for(const product of manifest.functionalProducts){const names=product==='host-runtime'?['host','factory']:[product];for(const name of names){const descriptor=JSON.parse(readFileSync(`${root}/deploy/commands/${name}.json`,'utf8'))as{version:string;package:string};assert(descriptor.version===manifest.version,`${name} descriptor version drifted.`);assert(descriptor.package===`treeseed-ai-${product}`,`${name} descriptor package drifted.`);}}
for(const name of['package.json',...['common','cli','host-runtime','inference-api','inference-manager','training-api','training-manager','lab'].map((item)=>`packages/${item}/package.json`)]){const value=JSON.parse(readFileSync(`${root}/${name}`,'utf8'))as{version:string};assert(value.version===manifest.version,`${name} version drifted.`);}
if(process.argv.includes('--release')){const fingerprint=readFileSync(`${root}/${manifest.apt.fingerprintFile}`,'utf8').trim(),key=readFileSync(`${root}/release/apt/treeseed-ai-archive-keyring.asc`,'utf8');assert(/^[A-F0-9]{40}$/u.test(fingerprint),'APT release-key fingerprint is not configured.');assert(key.includes('BEGIN PGP PUBLIC KEY BLOCK')&&!key.includes('PRIVATE KEY BLOCK'),'APT archive key must contain public material only.');const home=mkdtempSync(join(tmpdir(),'treeai-gpg-'));try{const result=spawnSync('gpg',['--batch','--homedir',home,'--show-keys','--with-colons',`${root}/release/apt/treeseed-ai-archive-keyring.asc`],{encoding:'utf8'});assert(result.status===0,`Cannot parse APT public key: ${result.stderr.trim()}`);const actual=result.stdout.split('\n').find((line)=>line.startsWith('fpr:'))?.split(':')[9];assert(actual===fingerprint,'APT public key does not match RELEASE_KEY_FINGERPRINT.');}finally{rmSync(home,{recursive:true,force:true});}}
process.stdout.write(`${JSON.stringify({status:'ready',version:manifest.version,products:manifest.products.length,images:manifest.images.length})}\n`);
