import{statfsSync}from'node:fs';import{totalmem}from'node:os';import type{Check,CompatibilityManifest,HostInspection,PackageRecord,SystemAdapter}from'./types.js';import{commandExists}from'./system.js';import{withinRange}from'./version.js';
function osRelease(value:string){return Object.fromEntries(value.split(/\r?\n/u).filter(Boolean).map((line)=>{const [key,...rest]=line.split('=');return[key!,rest.join('=').replace(/^"|"$/gu,'')];}));}
const relevantPackages=new Set(['docker-ce','docker-ce-cli','containerd.io','docker-buildx-plugin','docker-compose-plugin','docker.io','docker-compose','docker-doc','docker-buildx','podman-docker','containerd','runc','nvidia-docker2','nvidia-container-runtime','nvidia-container-toolkit']);
function packages(system:SystemAdapter){const result=system.command('dpkg-query',['-W','-f=${binary:Package}\t${Version}\n']);if(result.code)return[];return result.stdout.split('\n').filter(Boolean).map((line)=>{const[name,version]=line.split('\t');return{name:name!.replace(/:amd64$/u,''),version:version!};}).filter(({name})=>relevantPackages.has(name));}
function output(system:SystemAdapter,file:string,args:string[]=[]){const result=system.command(file,args);return result.code?'':result.stdout;}
export function inspectHost(system:SystemAdapter,manifest:CompatibilityManifest):HostInspection{
	const release=osRelease(system.exists('/etc/os-release')?system.read('/etc/os-release'):'');const architecture=output(system,'dpkg',['--print-architecture'])||process.arch;const key=`${release.ID??''}:${release.VERSION_ID??''}`;const supported=architecture==='amd64'&&Boolean(manifest.supportedPlatforms[key]);const installed=packages(system);const commands={docker:output(system,'docker',['--version']),compose:output(system,'docker',['compose','version','--short']),containerd:output(system,'containerd',['--version']),nvidiaSmi:output(system,'nvidia-smi',['--query-gpu=name,memory.total,driver_version','--format=csv,noheader']),nvidiaCtk:output(system,'nvidia-ctk',['--version']),dockerInfo:output(system,'docker',['info','--format','{{json .Runtimes}}']),dockerRoot:output(system,'docker',['info','--format','{{.DockerRootDir}}']),aptAudit:output(system,'dpkg',['--audit'])};
	let diskGiB=0;try{const disk=statfsSync('/var/lib');diskGiB=Math.round(disk.bavail*disk.bsize/1024**3*10)/10;}catch{/* check reports zero */}let dockerDaemon:unknown=null;try{dockerDaemon=system.exists('/etc/docker/daemon.json')?JSON.parse(system.read('/etc/docker/daemon.json')):{};}catch{dockerDaemon='invalid-json';}
	const secureBoot=commandExists(system,'mokutil')?(output(system,'mokutil',['--sb-state'])||'unknown'):'unavailable';const checks:Check[]=[
		{id:'platform',status:supported?'ready':'unsupported',summary:supported?`${release.PRETTY_NAME??key} amd64`:`Unsupported ${key} ${architecture}`},
		{id:'docker',status:commands.docker&&withinRange(commands.docker,manifest.validatedRanges.docker)?'ready':commands.docker?'warning':'blocked',summary:commands.docker||'Docker is not installed.'},
		{id:'compose',status:commands.compose&&withinRange(commands.compose,manifest.validatedRanges.compose)?'ready':commands.compose?'warning':'blocked',summary:commands.compose||'Docker Compose is not installed.'},
		{id:'gpu-driver',status:commands.nvidiaSmi?'ready':'blocked',summary:commands.nvidiaSmi||'No working NVIDIA driver/GPU detected.',repair:'Install a compatible host driver; check Secure Boot, kernel headers, and reboot state.'},
		{id:'nvidia-toolkit',status:commands.nvidiaCtk&&withinRange(commands.nvidiaCtk,manifest.validatedRanges.toolkit)?'ready':commands.nvidiaCtk?'warning':'blocked',summary:commands.nvidiaCtk||'NVIDIA Container Toolkit is not installed.'},
		{id:'daemon-json',status:dockerDaemon==='invalid-json'?'blocked':'ready',summary:dockerDaemon==='invalid-json'?'Docker daemon.json is invalid JSON.':'Docker daemon configuration parses.'},
		{id:'apt-state',status:commands.aptAudit?'blocked':'ready',summary:commands.aptAudit||'APT/dpkg reports no incomplete package operations.',repair:'Resolve interrupted or unconfigured packages before apply.'},
		{id:'disk',status:diskGiB>=30?'ready':'blocked',summary:`${diskGiB} GiB free under /var/lib`},{id:'memory',status:totalmem()>=16*1024**3?'ready':'warning',summary:`${Math.round(totalmem()/1024**3*10)/10} GiB system memory`},
	];return{checkedAt:system.now(),platform:{id:String(release.ID??''),version:String(release.VERSION_ID??''),codename:String(release.VERSION_CODENAME??''),architecture,supported},root:system.uid()===0,secureBoot,pendingReboot:system.exists('/var/run/reboot-required'),packages:installed,commands,dockerDaemon,diskGiB,memoryGiB:Math.round(totalmem()/1024**3*10)/10,checks};
}
