import type{Check,CompatibilityManifest,HostInspection,HostPlan,MigrationPlan,PlanAction}from'./types.js';import type{RuntimeConfig}from'./config.js';import{packageVersions}from'./config.js';
const official=new Set(['docker-ce','docker-ce-cli','containerd.io','docker-buildx-plugin','docker-compose-plugin']);
export function conflictingPackages(inspection:HostInspection,manifest:CompatibilityManifest){
	const names=new Set(inspection.packages.map(({name})=>name));const workingDocker=Boolean(inspection.commands.docker&&inspection.commands.compose);
	return manifest.knownConflicts.filter((name)=>names.has(name)&&!(workingDocker&&['docker.io','containerd','runc','docker-compose'].includes(name)));
}
export function createMigrationPlan(inspection:HostInspection,manifest:CompatibilityManifest):MigrationPlan{const conflicts=conflictingPackages(inspection,manifest);return{schemaVersion:'ai.host-runtime-migration-plan/v1',createdAt:inspection.checkedAt,conflicts,commands:conflicts.length?[['apt-get','remove',...conflicts]]:[],warnings:['Review backups for /var/lib/docker and /var/lib/containerd before executing any command.','These commands are guidance only and are never executed by this package.']};}
export function createPlan(inspection:HostInspection,manifest:CompatibilityManifest,config:RuntimeConfig):HostPlan{
	const checks:Check[]=[];const actions:PlanAction[]=[];const conflicts=conflictingPackages(inspection,manifest);const names=new Set(inspection.packages.map(({name})=>name));
	if(!inspection.platform.supported)checks.push({id:'supported-platform',status:'unsupported',summary:'Host platform is outside the supported matrix.'});
	if(inspection.dockerDaemon==='invalid-json')checks.push({id:'daemon-json',status:'blocked',summary:'Refusing to modify malformed /etc/docker/daemon.json.'});
	if(inspection.commands.aptAudit)checks.push({id:'apt-state',status:'blocked',summary:'Refusing to run APT while dpkg reports incomplete package operations.'});
	if(conflicts.length)checks.push({id:'package-conflicts',status:'blocked',summary:`Incompatible packages require operator migration: ${conflicts.join(', ')}`,repair:'Run treeseed-ai-host-runtime migration-plan.'});
	if(inspection.commands.docker&&!names.has('docker-ce')&&!names.has('docker.io'))checks.push({id:'manual-docker',status:'blocked',summary:'Docker appears to be manually installed and will not be replaced.'});
	if(inspection.commands.docker&&inspection.checks.find(({id})=>id==='docker')?.status!=='ready')checks.push({id:'docker-version',status:'blocked',summary:'Existing Docker is outside the validated range and will not be replaced.'});
	if(inspection.commands.compose&&inspection.checks.find(({id})=>id==='compose')?.status!=='ready')checks.push({id:'compose-version',status:'blocked',summary:'Existing Compose is outside the validated range and will not be replaced.'});
	if(inspection.commands.nvidiaCtk&&inspection.checks.find(({id})=>id==='nvidia-toolkit')?.status!=='ready')checks.push({id:'toolkit-version',status:'blocked',summary:'Existing NVIDIA Toolkit is outside the validated range and will not be replaced.'});
	if(!inspection.commands.docker&&[...official].some((name)=>names.has(name)))checks.push({id:'broken-docker-install',status:'blocked',summary:'Docker packages are installed but Docker is not functional; repair them before apply.'});
	if(!inspection.commands.nvidiaCtk&&names.has('nvidia-container-toolkit'))checks.push({id:'broken-toolkit-install',status:'blocked',summary:'NVIDIA Toolkit is installed but nvidia-ctk is not functional; repair it before apply.'});
	if(config.source==='local-apt'&&(!config.localApt||Object.values(config.localApt).some((value)=>!value)))checks.push({id:'local-apt',status:'blocked',summary:'local-apt requires url, suite, components, and signedBy configuration.'});
	const platformKey=`${inspection.platform.id}:${inspection.platform.version}`;const versions=packageVersions(manifest,platformKey);const dockerInstallNeeded=!inspection.commands.docker;const composeOnlyNeeded=Boolean(inspection.commands.docker&&!inspection.commands.compose&&names.has('docker-ce'));if(inspection.commands.docker&&!inspection.commands.compose&&!names.has('docker-ce'))checks.push({id:'missing-compose',status:'blocked',summary:'Compose is missing from an operator-managed Docker installation; install it through the same package origin.'});
	if(dockerInstallNeeded||composeOnlyNeeded){const wanted=composeOnlyNeeded?['docker-compose-plugin']:[...official];actions.push({id:'docker-repository',description:'Configure the signed Docker APT repository.',commands:[],mutating:true},{id:'docker-packages',description:`Install pinned Docker packages: ${wanted.map((name)=>`${name}=${versions[name]??'unresolved'}`).join(', ')}`,commands:[],mutating:true});}
	if(!inspection.commands.nvidiaCtk){actions.push({id:'nvidia-repository',description:'Configure the signed NVIDIA Container Toolkit APT repository.',commands:[],mutating:true},{id:'nvidia-package',description:`Install nvidia-container-toolkit=${versions['nvidia-container-toolkit']??'unresolved'}.`,commands:[],mutating:true});}
	if(!inspection.commands.dockerInfo.includes('nvidia'))actions.push({id:'nvidia-runtime',description:'Configure Docker NVIDIA runtime while preserving unrelated daemon settings.',commands:[['nvidia-ctk','runtime','configure','--runtime=docker']],mutating:true});
	if(!inspection.commands.nvidiaSmi)checks.push({id:'gpu-driver',status:'warning',summary:'Docker and Toolkit can be installed, but verification will remain blocked until the host driver works.'});
	const platformArtifacts=manifest.artifacts[platformKey]??[];const artifacts=[...(dockerInstallNeeded?platformArtifacts:composeOnlyNeeded?platformArtifacts.filter(({name})=>name==='docker-compose-plugin'):[]),...(!inspection.commands.nvidiaCtk?(manifest.artifacts.common??[]):[])];const blocked=checks.some(({status})=>status==='blocked'||status==='unsupported');return{schemaVersion:'ai.host-runtime-plan/v1',createdAt:inspection.checkedAt,compatibilityRelease:manifest.release,source:config.source,inspection,artifacts,actions,checks,blocked};
}
