import type{Check,CompatibilityManifest,SystemAdapter,VerificationResult}from'./types.js';import{inspectHost}from'./inspect.js';import{withinRange}from'./version.js';
function check(system:SystemAdapter,id:string,file:string,args:string[],summary:string,repair?:string):Check{const result=system.command(file,args);return{id,status:result.code?'blocked':'ready',summary:result.code?(result.stderr||summary):summary,repair};}
export function verifyHost(system:SystemAdapter,manifest:CompatibilityManifest):VerificationResult{const host=inspectHost(system,manifest);const checks:Check[]=[...host.checks,
	check(system,'docker-enabled','systemctl',['is-enabled','docker.service'],'docker.service is enabled.','Enable docker.service.'),check(system,'docker-active','systemctl',['is-active','docker.service'],'docker.service is active.','Start docker.service.'),
	{id:'docker-version-range',status:host.commands.docker&&withinRange(host.commands.docker,manifest.validatedRanges.docker)?'ready':'blocked',summary:host.commands.docker||'Docker unavailable.'},{id:'compose-version-range',status:host.commands.compose&&withinRange(host.commands.compose,manifest.validatedRanges.compose)?'ready':'blocked',summary:host.commands.compose||'Compose unavailable.'},
	{id:'nvidia-runtime',status:host.commands.dockerInfo.includes('nvidia')?'ready':'blocked',summary:host.commands.dockerInfo.includes('nvidia')?'Docker advertises the NVIDIA runtime.':'Docker does not advertise the NVIDIA runtime.'},
	check(system,'cuda-container','docker',['run','--rm','--pull=never','--gpus','all',manifest.cudaVerificationImage,'nvidia-smi'],'Pinned CUDA image can access the GPU.','Run apply to acquire the pinned image, then correct driver/Toolkit configuration.'),
	check(system,'compose-gpu','docker',['compose','-f','/usr/lib/treeseed-ai/host-runtime/config/gpu-verify.compose.yml','run','--rm','--pull','never','gpu'],'Compose GPU device reservations can access the GPU.'),
	];const chain=system.command('iptables',['-S','DOCKER-USER']);checks.push({id:'docker-user-chain',status:chain.code?'warning':'ready',summary:chain.code?'DOCKER-USER firewall chain was not observed.':'DOCKER-USER chain is available.'});const pending=host.pendingReboot;checks.push({id:'pending-reboot',status:pending?'warning':'ready',summary:pending?'A reboot is pending.':'No pending reboot marker.'},{id:'secure-boot',status:/enabled/iu.test(host.secureBoot)&&!host.commands.nvidiaSmi?'blocked':'ready',summary:host.secureBoot});
	const names=new Set(host.packages.map(({name})=>name));const mixed=(names.has('docker-ce')&&names.has('docker.io'))||(names.has('containerd.io')&&names.has('containerd'));const origins=system.command('apt-cache',['policy','docker-ce','docker-ce-cli','containerd.io','docker.io','containerd']);checks.push({id:'package-origins',status:mixed?'blocked':origins.code?'warning':'ready',summary:mixed?'Mixed Docker/containerd package families are installed.':origins.code?'Unable to inspect Docker/containerd APT origins.':'Docker/containerd package origins are consistent.',observed:origins.stdout});const storage=host.commands.dockerRoot?system.command('df',['-Pk',host.commands.dockerRoot]):{code:1,stdout:'',stderr:''};checks.push({id:'docker-storage',status:storage.code?'warning':'ready',summary:storage.code?'Unable to inspect Docker data-root capacity.':`Docker data root ${host.commands.dockerRoot} is accessible.`,observed:storage.stdout});const firewall=system.command('ufw',['status']);checks.push({id:'firewall-exposure',status:/inactive/iu.test(firewall.stdout)||firewall.code?'warning':'ready',summary:firewall.code?'No supported host firewall status was available.':firewall.stdout.split('\n')[0]||'Firewall inspected.',repair:'Review published Docker ports and host firewall policy.'});
	const overall=checks.some(({status})=>status==='unsupported')?'unsupported':checks.some(({status})=>status==='blocked')?'blocked':checks.some(({status})=>status==='warning')?'warning':'ready';return{schemaVersion:'ai.host-runtime-verification/v1',checkedAt:host.checkedAt,overall,ok:overall==='ready'||overall==='warning',checks};}
