import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { verifyBuildReceipt } from './build.js';
import { loadCompatibility } from '../config.js';
import { NodeSystem } from '../system.js';
import { verifyHost } from '../verify.js';
import { configRoot, deploymentMode, gateway, prepareRuntimeDirectory, productCompose, publicCa, requireRoot, run, setProductEnvironment, stateRoot } from './shared.js';
import { readState } from './state.js';

function environment(name:string){const value=readFileSync('/etc/treeseed-ai/inference/environment','utf8').split('\n').find((line)=>line.startsWith(`${name}=`));return value?.slice(name.length+1).replace(/^['"]|['"]$/gu,'')??'';}
function fingerprint(imageId:string){const gpu=run('nvidia-smi',['--query-gpu=uuid,driver_version','--format=csv,noheader'],'pipe');return{gpu,imageId,model:environment('SOURCE_MODEL'),revision:environment('SOURCE_MODEL_REVISION'),gpuMemoryUtilization:environment('GPU_MEMORY_UTILIZATION')||'0.85'};}
function same(left:Record<string,unknown>,right:Record<string,unknown>){return JSON.stringify(left)===JSON.stringify(right);}
export function qualifyContext(){const receiptPath=`${stateRoot}/context-profile.json`,imageId=deploymentMode()==='development'?verifyBuildReceipt().images.find(({role})=>role==='inference-vllm')!.imageId:run('docker',['image','inspect',environment('INFERENCE_VLLM_IMAGE'),'--format','{{.Id}}'],'pipe'),current=fingerprint(imageId);if(existsSync(receiptPath)){const prior=JSON.parse(readFileSync(receiptPath,'utf8'));if(same(prior.fingerprint,current)){setProductEnvironment('inference','MAX_MODEL_LENGTH',String(prior.maxModelLength));return prior;}}
  const probe="import concurrent.futures,json,sys,urllib.request\nfrom transformers import AutoTokenizer\nn=int(sys.argv[1]); model=sys.argv[2]; rev=sys.argv[3]; t=AutoTokenizer.from_pretrained(model,revision=rev); goal=n-2048; lo,hi=1,goal*4\nwhile lo<hi:\n mid=(lo+hi+1)//2\n if len(t.encode('factory '*mid,add_special_tokens=False))<=goal: lo=mid\n else: hi=mid-1\ntext='factory '*lo; actual=len(t.encode(text,add_special_tokens=False)); assert actual>=goal-64,(actual,goal); body=json.dumps({'model':model,'messages':[{'role':'user','content':text}],'max_tokens':8}).encode()\ndef one(_):\n r=urllib.request.Request('http://127.0.0.1:8000/v1/chat/completions',data=body,headers={'content-type':'application/json'}); urllib.request.urlopen(r,timeout=300).read()\nlist(concurrent.futures.ThreadPoolExecutor(max_workers=2).map(one,range(2)))";
  for(let tokens=65_536;tokens>=16_384;tokens-=4_096){setProductEnvironment('inference','MAX_MODEL_LENGTH',String(tokens));try{productCompose('inference',['up','-d','--wait','--wait-timeout','900','vllm']);productCompose('inference',['exec','-T','vllm','python3','-c',probe,String(tokens),current.model,current.revision]);const receipt={schemaVersion:'ai.factory-context-profile/v1',fingerprint:current,maxModelLength:tokens,maxNumSequences:2,qualifiedAt:new Date().toISOString()};writeFileSync(receiptPath,`${JSON.stringify(receipt,null,2)}\n`,{mode:0o640});return receipt;}catch{try{productCompose('inference',['stop','vllm']);}catch{/* continue with smaller profile */}}}throw new Error('No context profile of at least 16384 tokens passed two-request qualification.');}
function gate(product:'inference'|'training',services:string[]){productCompose(product,['up','-d','--remove-orphans','--wait','--wait-timeout','600',...services]);}
function completionGate(product:'inference'|'training',services:string[]){productCompose(product,['up','-d','--remove-orphans',...services]);const pending=new Set(services),deadline=Date.now()+600_000;while(pending.size&&Date.now()<deadline){for(const service of pending){const container=productCompose(product,['ps','-a','-q',service],'pipe');if(!container)continue;const state=JSON.parse(run('docker',['inspect','--format','{{json .State}}',container],'pipe'))as{Status:string;ExitCode:number;Error?:string};if(state.Status==='exited'&&state.ExitCode===0)pending.delete(service);else if(state.Status==='exited'||state.Status==='dead')throw new Error(`${product} ${service} completion job failed with exit ${state.ExitCode}${state.Error?`: ${state.Error}`:''}. Inspect it with treeai factory logs ${product} ${service}.`);}if(pending.size)run('sh',['-c','sleep 1'],'pipe');}if(pending.size)throw new Error(`Timed out waiting for ${product} completion jobs: ${[...pending].join(', ')}.`);}
function coordinatorGate(){const deadline=Date.now()+600_000;let lastError='coordinator did not answer';while(Date.now()<deadline){try{run('curl',['--silent','--show-error','--fail','--connect-timeout','2','--max-time','5','--cacert',publicCa,'https://localhost:4790/readyz'],'pipe');return;}catch(error){lastError=error instanceof Error?error.message:String(error);run('sh',['-c','sleep 1'],'pipe');}}const active=run('systemctl',['is-active','treeseed-ai-factory.service'],'pipe');throw new Error(`Factory coordinator readiness timed out (systemd: ${active}): ${lastError}`);}
export function startFactory(restart=false){requireRoot();if(!existsSync(`${configRoot}/configuration-receipt.json`))throw new Error('Factory configuration receipt is missing.');const host=verifyHost(new NodeSystem(),loadCompatibility());if(!host.ok)throw new Error(`Host verification is ${host.overall}; correct blocked checks before starting.`);if(deploymentMode()==='development')verifyBuildReceipt();const mode=readState().mode;if(mode!=='awake'&&mode!=='sleep')throw new Error(`Cannot start factory from ${mode} mode.`);if(restart)run('systemctl',['stop','treeseed-ai-factory.service']);for(const unit of['treeseed-ai-inference.service','treeseed-ai-training.service'])run('systemctl',['disable','--now',unit]);
  for(const product of['inference','training']as const)prepareRuntimeDirectory(product,true);gate('inference',['postgres','minio']);gate('training',['postgres','minio']);completionGate('inference',['minio-init','migrations']);completionGate('training',['minio-init','migrations']);gate('inference',['evaluator','manager','api']);gate('training',['artifact','manager','api']);if(mode==='awake')qualifyContext();else gate('training',['marker','axolotl']);gateway(['up','-d','--remove-orphans','--wait','--wait-timeout','120']);run('systemctl',['enable','--now','treeseed-ai-factory.service']);coordinatorGate();}
export function stopFactory(){requireRoot();try{run('systemctl',['stop','treeseed-ai-factory.service']);}finally{try{gateway(['down']);}finally{try{productCompose('training',['down']);}finally{productCompose('inference',['down']);}}}}
