import { existsSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { createFactoryPlan } from './planning.js';
import { configRoot, requireRoot, roles, run, sourceRoot, stateRoot, treeDigest, version } from './shared.js';

const runtimeImages=['caddy:2.10.2-alpine@sha256:4c6e91c6ed0e2fa03efd5b44747b625fec79bc9cd06ac5235a779726618e530d','postgres:17.11-alpine@sha256:18cfe3ef5e6815560c98237d6216d1e5119702fb0f3894c8785dd58b8bbe5d73','minio/minio:RELEASE.2025-07-23T15-54-02Z@sha256:d249d1fb6966de4d8ad26c04754b545205ff15a62e4fd19ebd0f26fa5baacbc0','minio/mc:RELEASE.2025-07-21T05-28-08Z@sha256:fb8f773eac8ef9d6da0486d5dec2f42f219358bcb8de579d1623d518c9ebd4cc'];
const checks:Record<string,string[]>= {
  'inference-api':['node','--check','/app/packages/inference-api/dist/main.js'],'inference-manager':['node','--check','/app/packages/inference-manager/dist/main.js'],
  'training-api':['node','--check','/app/packages/training-api/dist/main.js'],'training-manager':['node','--check','/app/packages/training-manager/dist/main.js'],
  'inference-evaluator':['python','-c',"import ast,pathlib; ast.parse(pathlib.Path('/app/evaluator/worker.py').read_text())"],'artifact-worker':['python','-c',"import ast,pathlib; ast.parse(pathlib.Path('/app/artifact/worker.py').read_text())"],
  'marker-worker':['python3','-c','import marker; import boto3'],'axolotl-worker':['python3','-c','import axolotl, accelerate'],
  'inference-vllm':['python3','-c','import vllm'],'inference-migrations':['sh','-c','test -s /migrations/001_initial.sql'],'training-migrations':['sh','-c','test -s /migrations/001_initial.sql'],
};
const healthWorkers=new Set(['inference-evaluator','artifact-worker','marker-worker','axolotl-worker']);
function smoke(role:string,tag:string){if(!healthWorkers.has(role)){run('docker',['run','--rm','--entrypoint',checks[role]![0]!,tag,...checks[role]!.slice(1)],'pipe');return;}const name=`ai-factory-smoke-${role}-${process.pid}`;run('docker',['run','-d','--name',name,tag],'pipe');let lastError='health probe did not complete';try{for(let attempt=0;attempt<60;attempt++){try{run('docker',['exec',name,checks[role]![0]!,...checks[role]!.slice(1)],'pipe');run('docker',['exec',name,'python3','-c',"import urllib.request; urllib.request.urlopen('http://127.0.0.1:8080/healthz',timeout=2).read()"],'pipe');return;}catch(error){lastError=error instanceof Error?error.message:String(error);run('sh',['-c','sleep 1'],'pipe');}}let state='unavailable',logs='';try{state=run('docker',['inspect','--format','status={{.State.Status}} exit={{.State.ExitCode}} error={{.State.Error}}',name],'pipe');}catch{/* retain diagnostic fallback */}try{logs=run('docker',['logs','--tail','100',name],'pipe');}catch{/* retain diagnostic fallback */}throw new Error(`${role} smoke test failed: ${state}; ${lastError}${logs?`\nContainer logs:\n${logs}`:''}`);}finally{try{run('docker',['rm','-f',name],'pipe');}catch{/* best-effort cleanup of an exact smoke-test container */}}}
function imageDetails(tag:string){return JSON.parse(run('docker',['image','inspect',tag,'--format','{{json .}}'],'pipe'))as{id:string;Id:string;Architecture:string;RepoDigests?:string[];Config?:{Labels?:Record<string,string>}};}
function sourceRevision(root:string){try{return run('git',['-C',root,'rev-parse','HEAD'],'pipe');}catch{return'unknown';}}
function dirty(root:string){try{return Boolean(run('git',['-C',root,'status','--porcelain'],'pipe',{...process.env,GIT_OPTIONAL_LOCKS:'0'}));}catch{return true;}}
export interface BuildReceipt {schemaVersion:'ai.factory-build/v1';status:'ready';version:string;createdAt:string;source:string;sourceRevision:string;sourceDigest:string;sourceDirty:boolean;images:Array<{role:string;tag:string;imageId:string;architecture:string;repoDigests:string[];baseImage:{name:string;digest:string};labels:Record<string,string>;smoke:'passed'}>;runtimeImages:Array<{tag:string;imageId:string;repoDigests:string[]}>}
export function buildFactory(machine=false):BuildReceipt {
  requireRoot();if(!existsSync(`${configRoot}/configuration-receipt.json`))throw new Error('Configure the factory before building images.');const plan=createFactoryPlan();if(plan.blocked){const blocked=plan.checks.filter(({status})=>status==='blocked'||status==='unsupported').map(({id,summary})=>`${id}: ${summary}`).join('\n');throw new Error(`Factory plan is blocked:\n${blocked}`);}
  const root=sourceRoot(),sourceDigest=treeDigest(root),revision=sourceRevision(root),createdAt=new Date().toISOString();
  const env={...process.env,AI_SOURCE_REVISION:revision,AI_SOURCE_DIGEST:sourceDigest,AI_BUILD_DATE:createdAt};
  run('docker',['buildx','bake','--file','deploy/factory/docker-bake.hcl','--load',...(machine?['--progress','quiet']:[]),'factory'],machine?'pipe':'inherit',env,root);
  const images=[] as BuildReceipt['images'];for(const role of roles){const tag=`local/${role}:${version}`;smoke(role,tag);const detail=imageDetails(tag),labels=detail.Config?.Labels??{};images.push({role,tag,imageId:detail.Id,architecture:detail.Architecture,repoDigests:detail.RepoDigests??[],baseImage:{name:labels['org.opencontainers.image.base.name']??'unknown',digest:labels['org.opencontainers.image.base.digest']??'unknown'},labels,smoke:'passed'});}
  const runtime=[] as BuildReceipt['runtimeImages'];for(const tag of runtimeImages){run('docker',['pull',...(machine?['--quiet']:[]),tag],machine?'pipe':'inherit');const detail=imageDetails(tag);runtime.push({tag,imageId:detail.Id,repoDigests:detail.RepoDigests??[]});}
  const receipt:BuildReceipt={schemaVersion:'ai.factory-build/v1',status:'ready',version,createdAt,source:root,sourceRevision:revision,sourceDigest,sourceDirty:dirty(root),images,runtimeImages:runtime};mkdirSync(stateRoot,{recursive:true});const target=`${stateRoot}/build-receipt.json`,temporary=`${target}.tmp-${process.pid}`;writeFileSync(temporary,`${JSON.stringify(receipt,null,2)}\n`,{mode:0o640});renameSync(temporary,target);return receipt;
}
export function verifyBuildReceipt(){const path=`${stateRoot}/build-receipt.json`;if(!existsSync(path))throw new Error('Factory build receipt is missing; run treeai factory build.');const receipt=JSON.parse(readFileSync(path,'utf8'))as BuildReceipt;if(receipt.version!==version)throw new Error(`Build receipt ${receipt.version} is incompatible with ${version}.`);for(const expected of receipt.images){const current=imageDetails(expected.tag);if(current.Id!==expected.imageId)throw new Error(`Image tag moved since build: ${expected.tag}. Rebuild before starting.`);}return receipt;}
