import{randomBytes}from'node:crypto';
import{chmodSync,copyFileSync,existsSync,mkdirSync,mkdtempSync,readFileSync,renameSync,rmSync,writeFileSync}from'node:fs';
import{dirname,join}from'node:path';
import{createFactoryPlan}from'./planning.js';
import{configRoot,credential,deploymentMode,detectedSans,digest,installedFactory,productCompose,publicCa,requireRoot,roles,run,stateRoot,version}from'./shared.js';
import{writeState}from'./state.js';

type Key=ReturnType<typeof credential>;
interface ConfigureResult{schemaVersion:'ai.factory-configuration-result/v1';status:'ready';configured:boolean;receipt:string;ca:string;restartRequired?:boolean}
function upgradeLegacyConfiguration(){for(const product of['inference','training']as const){let content=readFileSync(`/etc/treeseed-ai/${product}/environment`,'utf8');content=envValue(content,'AI_VERSION',version);for(const role of roles.filter((item)=>product==='inference'?item.startsWith('inference-'):!item.startsWith('inference-')))content=envValue(content,`${role.replaceAll('-','_').toUpperCase()}_IMAGE`,`local/${role}:${version}`);atomic(`/etc/treeseed-ai/${product}/environment`,content,0o640);run('chown',[`root:treeseed-ai-${product}`,`/etc/treeseed-ai/${product}/environment`]);}const outcome=rotateOperatorKey(),host=run('hostname',[],'pipe'),client={schemaVersion:'treeai.config/v1',version,deploymentMode:'development',ca:publicCa,endpoints:{factory:`https://${host}:4790`,inference:`https://${host}:4770`,openai:`https://${host}:4771`,training:`https://${host}:4780`,lab:`https://${host}:4793`},installedProducts:['host-runtime','inference','training']};atomic('/etc/treeseed-ai/treeai/config.json',`${JSON.stringify(client,null,2)}\n`,0o644);return outcome;}
function imageReference(role:string){if(deploymentMode()!=='published')return`local/${role}:${version}`;const manifest=JSON.parse(readFileSync('/usr/share/treeseed-ai/release/image-manifest.json','utf8'))as{version:string;images:Record<string,{repository:string;digest:string}>},image=manifest.images[role];if(manifest.version!==version||!image||!/^sha256:[a-f0-9]{64}$/u.test(image.digest))throw new Error(`Published digest is missing for ${role}.`);return`${image.repository}@${image.digest}`;}
function atomic(path:string,value:string,mode=0o600){mkdirSync(dirname(path),{recursive:true});const temporary=`${path}.tmp-${process.pid}`;writeFileSync(temporary,value,{mode});renameSync(temporary,path);chmodSync(path,mode);}
function envValue(content:string,name:string,value:string){const lines=content.split('\n').filter((line)=>line&&!line.startsWith(`${name}=`));lines.push(`${name}=${value}`);return`${lines.join('\n')}\n`;}
function productEnvironment(product:'inference'|'training',keys:Key[],storeSecret:string,rootSecret:string,dbSecret:string){let content=readFileSync(`/etc/treeseed-ai/${product}/environment`,'utf8');const values:Record<string,string>={AI_API_KEYS:`'${JSON.stringify(keys.map((key)=>key.record))}'`,AI_VERSION:version,COMPOSE_PROFILES:'state',DATABASE_URL:`postgresql://${product}:${dbSecret}@postgres:5432/${product}`,POSTGRES_PASSWORD:dbSecret,S3_ENDPOINT:'http://minio:9000',S3_ACCESS_KEY:product,S3_SECRET_KEY:storeSecret,MINIO_ROOT_USER:`${product}-root`,MINIO_ROOT_PASSWORD:rootSecret,AI_FACTORY_MODE_FILE:'/factory/mode.json',AI_FACTORY_STATUS_FILE:'/runtime-status/status.json'};
  if(product==='inference'){values.SOURCE_MODEL='Qwen/Qwen3.5-4B';values.SOURCE_MODEL_REVISION='851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a';for(const role of roles.filter((role)=>role.startsWith('inference-')))values[`${role.replaceAll('-','_').toUpperCase()}_IMAGE`]=imageReference(role);}else{values.SIGNING_KEY_FILE=`${configRoot}/artifact-signing-key.pem`;values.SIGNING_KEY_ID=`training-local-${version}`;for(const role of roles.filter((role)=>!role.startsWith('inference-')))values[`${role.replaceAll('-','_').toUpperCase()}_IMAGE`]=imageReference(role);}for(const[name,value]of Object.entries(values))content=envValue(content,name,value);return content;}
function network(){const inspected=run('docker',['network','inspect','ai-shared','--format','{{.Id}} {{.Driver}} {{.Scope}}'],'pipe');const[id,driver,scope]=inspected.split(' ');if(driver!=='bridge'||scope!=='local')throw new Error(`Existing ai-shared network is incompatible: ${inspected}`);return id!;}
function ensureNetwork(){try{return network();}catch(error){const message=error instanceof Error?error.message:String(error);if(!/No such network|not found/iu.test(message))throw error;run('docker',['network','create','--driver','bridge','--label',`org.treeseed-ai.factory.version=${version}`,'ai-shared'],'pipe');return network();}}
function validate(directory:string){for(const file of['ca.crt','ca.key','server.crt','server.key','artifact-signing-key.pem','artifact-signing-public.pem'])if(!existsSync(join(directory,file)))throw new Error(`Configuration generation did not produce ${file}.`);run('openssl',['verify','-CAfile',join(directory,'ca.crt'),join(directory,'server.crt')],'pipe');run('openssl',['pkey','-in',join(directory,'artifact-signing-key.pem'),'-check'],'pipe');}
function install(source:string,target:string,mode:number){copyFileSync(source,target);chmodSync(target,mode);}
function result(configured=false):ConfigureResult{return{schemaVersion:'ai.factory-configuration-result/v1',status:'ready',configured,receipt:`${configRoot}/configuration-receipt.json`,ca:publicCa};}
function ensureServiceCredentials(){for(const item of[{file:'factory-service-key',path:`${configRoot}/environment`,variable:'AI_FACTORY_API_KEYS',id:'factory-service',scopes:['factory:*']},{file:'inference-service-key',path:'/etc/treeseed-ai/inference/environment',variable:'AI_API_KEYS',id:'lab-inference',scopes:['*']},{file:'training-service-key',path:'/etc/treeseed-ai/training/environment',variable:'AI_API_KEYS',id:'lab-training',scopes:['*']}]){const target=`${configRoot}/${item.file}`;if(existsSync(target))continue;const key=credential(item.id,item.scopes),content=readFileSync(item.path,'utf8'),line=content.split('\n').find((value)=>value.startsWith(`${item.variable}=`))??`${item.variable}=[]`,records=JSON.parse(line.slice(line.indexOf('=')+1).replace(/^'|'$/gu,''))as unknown[];atomic(item.path,envValue(content,item.variable,`'${JSON.stringify([...records,key.record])}'`),item.path.includes('/host-runtime/')?0o600:0o640);atomic(target,`${key.plain}\n`);}}
function active(unit:string){try{run('systemctl',['is-active','--quiet',unit],'pipe');return true;}catch{return false;}}
function activateOperator(plain:string){if(!active('treeseed-ai-factory.service'))return;productCompose('inference',['up','-d','--no-deps','--force-recreate','api']);productCompose('training',['up','-d','--no-deps','--force-recreate','api']);run('systemctl',['restart','treeseed-ai-factory.service']);const checks=[4790,4770,4780];if(active('treeseed-ai-lab.service')){run('docker',['compose','--env-file','/etc/treeseed-ai/lab/environment','-f','/usr/lib/treeseed-ai/lab/compose.yml','up','-d','--no-deps','--force-recreate','controller']);checks.push(4793);}for(const port of checks)run('curl',['--silent','--show-error','--fail','--retry','20','--retry-delay','1','--cacert',publicCa,'-H',`Authorization: Bearer ${plain}`,`https://localhost:${port}${port===4790?'/v1/services':port===4793?'/v1/status':'/v1/version'}`],'pipe');}
export function configureFactory(rotate=false):ConfigureResult{requireRoot();if(rotate)return rotateOperatorKey();const receiptPath=`${configRoot}/configuration-receipt.json`;if(existsSync(receiptPath))return existsSync('/etc/treeseed-ai/treeai/operator.key')?result(false):upgradeLegacyConfiguration();const plan=createFactoryPlan();if(plan.blocked)throw new Error('Factory plan is blocked; run treeai factory plan for details.');for(const product of['inference','training'])if(!existsSync(`/etc/treeseed-ai/${product}/environment`))throw new Error(`${product} package environment is missing.`);
  const stage=mkdtempSync('/etc/treeseed-ai/host-runtime/factory-stage-');chmodSync(stage,0o700);const operator=credential('treeai-operator',['*']),control=credential('factory-service',['factory:*']),inference=credential('lab-inference',['*']),training=credential('lab-training',['*']);const store={inference:randomBytes(32).toString('hex'),training:randomBytes(32).toString('hex')},root={inference:randomBytes(32).toString('hex'),training:randomBytes(32).toString('hex')},database={inference:randomBytes(24).toString('hex'),training:randomBytes(24).toString('hex')},sans=detectedSans(),typed=sans.map((value)=>`${value.includes(':')||/^\d+\.\d+/u.test(value)?'IP':'DNS'}:${value}`),prior=new Map<string,string>();for(const product of['inference','training'])prior.set(product,readFileSync(`/etc/treeseed-ai/${product}/environment`,'utf8'));
  try{atomic(join(stage,'openssl.cnf'),`[req]\ndistinguished_name=dn\nreq_extensions=v3\nprompt=no\n[dn]\nCN=${plan.hostname}\n[v3]\nsubjectAltName=${typed.join(',')}\nbasicConstraints=critical,CA:FALSE\nkeyUsage=critical,digitalSignature,keyEncipherment\nextendedKeyUsage=serverAuth\n`);run('openssl',['req','-x509','-newkey','rsa:3072','-nodes','-days','3650','-keyout',join(stage,'ca.key'),'-out',join(stage,'ca.crt'),'-subj','/CN=AI Factory Development CA','-addext','basicConstraints=critical,CA:TRUE','-addext','keyUsage=critical,keyCertSign,cRLSign'],'pipe');run('openssl',['req','-newkey','rsa:3072','-nodes','-keyout',join(stage,'server.key'),'-out',join(stage,'server.csr'),'-config',join(stage,'openssl.cnf')],'pipe');run('openssl',['x509','-req','-days','825','-in',join(stage,'server.csr'),'-CA',join(stage,'ca.crt'),'-CAkey',join(stage,'ca.key'),'-CAcreateserial','-out',join(stage,'server.crt'),'-extensions','v3','-extfile',join(stage,'openssl.cnf')],'pipe');run('openssl',['genpkey','-algorithm','Ed25519','-out',join(stage,'artifact-signing-key.pem')],'pipe');run('openssl',['pkey','-in',join(stage,'artifact-signing-key.pem'),'-pubout','-out',join(stage,'artifact-signing-public.pem')],'pipe');validate(stage);
    const source={sourceId:'training-local',endpoint:'http://training-minio:9000',bucket:'ai-training',accessKeyId:'training',secretAccessKey:store.training,trustedPublicKey:readFileSync(join(stage,'artifact-signing-public.pem'),'utf8')};atomic(join(stage,'environment'),`AI_FACTORY_API_KEYS='${JSON.stringify([operator.record,control.record])}'\nFACTORY_HOST=0.0.0.0\nFACTORY_PORT=4790\n`);atomic(join(stage,'training-local-source.json'),`${JSON.stringify(source,null,2)}\n`);for(const[name,key]of[['factory-service-key',control],['inference-service-key',inference],['training-service-key',training]]as const)atomic(join(stage,name),`${key.plain}\n`);copyFileSync(join(installedFactory,'Caddyfile'),join(stage,'Caddyfile'));
    const networkId=ensureNetwork();mkdirSync(join(configRoot,'tls'),{recursive:true,mode:0o750});for(const file of['ca.key','server.key','openssl.cnf'])install(join(stage,file),join(configRoot,'tls',file),0o600);for(const file of['ca.crt','server.crt'])install(join(stage,file),join(configRoot,'tls',file),0o644);for(const file of['artifact-signing-key.pem','training-local-source.json','environment','factory-service-key','inference-service-key','training-service-key'])install(join(stage,file),join(configRoot,file),0o600);for(const file of['artifact-signing-public.pem','Caddyfile'])install(join(stage,file),join(configRoot,file),0o644);
    atomic('/etc/treeseed-ai/inference/environment',productEnvironment('inference',[operator,inference],store.inference,randomBytes(32).toString('hex'),database.inference),0o640);atomic('/etc/treeseed-ai/training/environment',productEnvironment('training',[operator,training],store.training,randomBytes(32).toString('hex'),database.training),0o640);for(const product of['inference','training'])run('chown',[`root:treeseed-ai-${product}`,`/etc/treeseed-ai/${product}/environment`]);install(join(stage,'ca.crt'),publicCa,0o644);mkdirSync(stateRoot,{recursive:true,mode:0o750});writeState({schemaVersion:'ai.factory-state/v1',mode:'awake',updatedAt:new Date().toISOString()});
    mkdirSync('/etc/treeseed-ai/treeai',{recursive:true,mode:0o750});atomic('/etc/treeseed-ai/treeai/operator.key',`${operator.plain}\n`,0o640);atomic('/etc/treeseed-ai/treeai/operator-record.json',`${JSON.stringify(operator.record)}\n`,0o640);run('chown',['root:treeseed-ai-operators','/etc/treeseed-ai/treeai/operator.key','/etc/treeseed-ai/treeai/operator-record.json']);const client={schemaVersion:'treeai.config/v1',version,deploymentMode:deploymentMode(),ca:publicCa,endpoints:{factory:`https://${plan.hostname}:4790`,inference:`https://${plan.hostname}:4770`,openai:`https://${plan.hostname}:4771`,training:`https://${plan.hostname}:4780`,lab:`https://${plan.hostname}:4793`},installedProducts:['host-runtime','inference','training']};atomic('/etc/treeseed-ai/treeai/config.json',`${JSON.stringify(client,null,2)}\n`,0o644);const receipt={schemaVersion:'ai.factory-configuration/v1',configuredAt:new Date().toISOString(),version,source:plan.source,sans,network:{name:'ai-shared',id:networkId},keyIds:['treeai-operator','factory-service','lab-inference','lab-training',`training-local-${version}`],digests:{certificate:digest(readFileSync(join(stage,'server.crt'))),publicSigningKey:digest(readFileSync(join(stage,'artifact-signing-public.pem')))}};atomic(receiptPath,`${JSON.stringify(receipt,null,2)}\n`,0o640);return result(true);
  }catch(error){for(const[product,value]of prior)atomic(`/etc/treeseed-ai/${product}/environment`,value,0o640);throw error;}finally{rmSync(stage,{recursive:true,force:true});}}
function rotateOperatorKey(){const receipt=`${configRoot}/configuration-receipt.json`;if(!existsSync(receipt))throw new Error('Factory must be configured before rotating the operator key.');ensureServiceCredentials();const operator=credential('treeai-operator',['*']),targets=[`${configRoot}/environment`,'/etc/treeseed-ai/inference/environment','/etc/treeseed-ai/training/environment',...(existsSync('/etc/treeseed-ai/lab/environment')?['/etc/treeseed-ai/lab/environment']:[])],backup=new Map(targets.map((path)=>[path,readFileSync(path,'utf8')])),oldKey=existsSync('/etc/treeseed-ai/treeai/operator.key')?readFileSync('/etc/treeseed-ai/treeai/operator.key','utf8'):'',recordPath='/etc/treeseed-ai/treeai/operator-record.json',oldRecord=existsSync(recordPath)?readFileSync(recordPath,'utf8'):'';try{for(const path of targets){const variable=path===`${configRoot}/environment`?'AI_FACTORY_API_KEYS':path.includes('/lab/')?'AI_LAB_API_KEYS':'AI_API_KEYS',content=readFileSync(path,'utf8'),line=content.split('\n').find((item)=>item.startsWith(`${variable}=`))??'',records=JSON.parse(line.slice(line.indexOf('=')+1).replace(/^'|'$/gu,''))as Array<{id:string}>;atomic(path,envValue(content,variable,`'${JSON.stringify([operator.record,...records.filter((item)=>item.id!=='treeai-operator')])}'`),path.includes('/host-runtime/')||path.includes('/lab/')?0o600:0o640);}atomic('/etc/treeseed-ai/treeai/operator.key',`${operator.plain}\n`,0o640);atomic(recordPath,`${JSON.stringify(operator.record)}\n`,0o640);run('chown',['root:treeseed-ai-operators','/etc/treeseed-ai/treeai/operator.key',recordPath]);activateOperator(operator.plain);return{...result(false),restartRequired:false};}catch(error){for(const[path,value]of backup)atomic(path,value,path.includes('/host-runtime/')||path.includes('/lab/')?0o600:0o640);atomic('/etc/treeseed-ai/treeai/operator.key',oldKey,0o640);if(oldRecord)atomic(recordPath,oldRecord,0o640);if(oldKey)try{activateOperator(oldKey.trim());}catch{}throw error;}}
