import type { AgentProfileV1 } from "../contracts.js";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { sanitize, digest, stateRoot } from "../shared.js";

export interface AgentContextBudget { schemaVersion:"treeai.agent-context/v1"; contextTokens:number; outputReserve:number; recentHistoryBudget:number; toolResultBudget:number; compactionThreshold:number; }
type Message={role?:string;content?:unknown;tool_call_id?:string;tool_calls?:unknown};
export function estimateTokens(value:unknown){return Math.ceil(Buffer.byteLength(JSON.stringify(value),"utf8")/3.2);}
export function contextBudget(contextTokens=Number(process.env.HERMES_MODEL_CONTEXT_LENGTH??16384)):AgentContextBudget{return{schemaVersion:"treeai.agent-context/v1",contextTokens,outputReserve:Math.max(2048,Math.floor(contextTokens*.125)),recentHistoryBudget:Math.floor(contextTokens*.38),toolResultBudget:Math.floor(contextTokens*.3),compactionThreshold:Math.floor(contextTokens*.82)};}
function groups(messages:Message[]){const result:Message[][]=[];for(let index=0;index<messages.length;index++){const group=[messages[index]!];if(messages[index]!.role==="assistant")while(index+1<messages.length&&messages[index+1]!.role==="tool")group.push(messages[++index]!);result.push(group);}return result;}
function artifactize(message:Message,budget:AgentContextBudget,root=stateRoot){if(message.role!=="tool"||estimateTokens(message.content)<=budget.toolResultBudget)return message;const clean=sanitize(message.content),sha256=digest(clean),directory=`${root}/context-artifacts`,path=`${directory}/${sha256}.json`;mkdirSync(directory,{recursive:true,mode:0o700});if(!existsSync(path))writeFileSync(path,`${JSON.stringify(clean)}\n`,{mode:0o600});return{...message,content:{schemaVersion:"ai.context-artifact-reference/v1",sha256,objectReference:`sha256:${sha256}`,summary:"Tool result exceeded the inline context budget. Retrieve bounded ranges from the context artifact when needed."}};}
export function contextPlan(messages:Message[],budget=contextBudget(),root=stateRoot){const normalized=messages.map(item=>artifactize(item,budget,root));if(estimateTokens(normalized)<=budget.compactionThreshold)return{requiresCompaction:false,older:[]as Message[],recent:normalized};const grouped=groups(normalized),recent:Message[][]=[];let tokens=0;while(grouped.length){const candidate=grouped.at(-1)!,cost=estimateTokens(candidate);if(recent.length&&tokens+cost>budget.recentHistoryBudget)break;recent.unshift(grouped.pop()!);tokens+=cost;}return{requiresCompaction:true,older:grouped.flat(),recent:recent.flat()};}
function deterministicState(messages:Message[]){return{goal:"Continue the user task represented by the retained conversation.",decisions:[],constraints:[],unresolvedQuestions:[],currentPlan:[],toolState:messages.filter(item=>item.role==="tool").slice(-20),artifactReferences:JSON.stringify(messages).match(/sha256:[a-f0-9]{64}/gu)??[]};}
export async function compactContext(messages:Message[],profile:AgentProfileV1,complete:(model:string,prompt:string)=>Promise<string>,budget=contextBudget(),root=stateRoot){const plan=contextPlan(messages,budget,root);if(!plan.requiresCompaction)return messages;const fallback=deterministicState(plan.older),prompt=`Return JSON only with keys goal, decisions, constraints, unresolvedQuestions, currentPlan, toolState, artifactReferences. Preserve facts and references; do not add hidden reasoning.\n${JSON.stringify(plan.older)}`;let state=fallback;try{const proposed=JSON.parse(await complete(profile.modelAlias,prompt))as Record<string,unknown>,validation=JSON.parse(await complete("local-model",`Validate that this compacted state contains exactly the required keys and no unsupported claims. Return {"valid":true|false}.\nSOURCE:${JSON.stringify(plan.older)}\nSTATE:${JSON.stringify(proposed)}`))as{valid?:boolean};if(validation.valid)state=proposed as typeof fallback;}catch{/* deterministic state is safe fallback */}return[{role:"system",content:`[CONTEXT COMPACTION — REFERENCE ONLY]\n${JSON.stringify(state)}`},...plan.recent];}
