import type { AgentProfileV1, AgentRoutingDecisionV1 } from "../contracts.js";
import { appendBounded, appendEvent, atomic, digest, lines, readJson, stateRoot } from "../shared.js";

const allowedTools = new Set(["file", "terminal", "web", "todo", "clarify", "memory", "session_search"]), slugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/u;
type ProfileInput = Partial<AgentProfileV1> & { slug?: string; displayName?: string; modelAlias?: string };
export class AgentProfiles {
	private path: string;
	constructor(private root=stateRoot){this.path=`${root}/agent-profiles.json`;}
	list() { return readJson<AgentProfileV1[]>(this.path, []); }
	get(idOrSlug: string) { return this.list().find((item) => item.id === idOrSlug || item.slug === idOrSlug); }
	private save(profile: AgentProfileV1) { const items = this.list(), index = items.findIndex((item) => item.id === profile.id || item.slug === profile.slug); if (index >= 0) items[index] = profile; else items.push(profile); atomic(this.path, items); appendEvent("agent-profile.changed", { id: profile.id, slug: profile.slug, status: profile.status },this.root); return profile; }
	upsert(input: ProfileInput, status?: AgentProfileV1["status"]) {
		if (!input.slug || !slugPattern.test(input.slug)) throw new Error("Agent slug must use lowercase letters, numbers, and hyphens.");
		if (!input.modelAlias || (!input.modelAlias.startsWith("library/") && input.modelAlias !== "local-model")) throw new Error("Agent model alias is not allowlisted.");
		const prior = this.get(input.id ?? input.slug), tools = input.allowedTools ?? prior?.allowedTools ?? [...allowedTools];
		if (!tools.every((tool) => allowedTools.has(tool))) throw new Error("Agent tool policy contains an unsupported tool.");
		const now = new Date().toISOString(), profile: AgentProfileV1 = { schemaVersion: "ai.agent-profile/v1", id: prior?.id ?? input.id ?? crypto.randomUUID(), slug: input.slug, displayName: input.displayName ?? prior?.displayName ?? input.slug, description: input.description ?? prior?.description ?? "Adapter-backed Hermes agent", ...(input.icon ?? prior?.icon ? { icon: input.icon ?? prior?.icon } : {}), status: status ?? input.status ?? prior?.status ?? "draft", modelAlias: input.modelAlias, adapterArtifactId: input.adapterArtifactId ?? prior?.adapterArtifactId, baseModelRevision: input.baseModelRevision ?? prior?.baseModelRevision ?? process.env.BASE_MODEL_REVISION ?? "unknown", systemInstructions: input.systemInstructions ?? prior?.systemInstructions ?? "Use the selected knowledge adapter and cite available artifact provenance.", allowedTools: tools, memoryPolicy: input.memoryPolicy ?? prior?.memoryPolicy ?? "session", contextPolicy: input.contextPolicy ?? prior?.contextPolicy ?? "agent-long-context", lineage: input.lineage ?? prior?.lineage ?? [], evaluations: input.evaluations ?? prior?.evaluations ?? [], createdAt: prior?.createdAt ?? now, updatedAt: now };
		return this.save(profile);
	}
	draft(input: { libraryId: string; librarySlug: string; candidateId: string; baseModelRevision?: string }) { return this.upsert({ slug: input.librarySlug, displayName: input.librarySlug.split("-").map((part) => part[0]!.toUpperCase() + part.slice(1)).join(" "), modelAlias: `library/${input.librarySlug}`, adapterArtifactId: input.candidateId, baseModelRevision: input.baseModelRevision, lineage: [input.candidateId] }, "draft"); }
	promote(libraryId: string, librarySlug: string, candidateId: string, evaluations: string[] = []) { return this.upsert({ slug: librarySlug, modelAlias: `library/${librarySlug}`, adapterArtifactId: candidateId, lineage: [candidateId], evaluations }, "enabled"); }
	update(id: string, input: ProfileInput) { const prior = this.get(id); if (!prior) throw new Error("Agent profile not found."); return this.upsert({ ...prior, ...input, id: prior.id, slug: input.slug ?? prior.slug, modelAlias: prior.modelAlias }, prior.status); }
	status(id: string, status: "enabled" | "disabled") { const prior = this.get(id); if (!prior) throw new Error("Agent profile not found."); if (status === "enabled" && !prior.evaluations.length) throw new Error("Agent profile has no passing evaluation evidence."); return this.save({ ...prior, status, updatedAt: new Date().toISOString() }); }
	select(requestedModel: string, messages: unknown[], conversationId?: string) {
		const enabled = this.list().filter((item) => item.status === "enabled"), sessions = readJson<Record<string, { profileId: string; segmentId: string }>>(`${this.root}/agent-segments.json`, {});
		let profile: AgentProfileV1 | undefined, reason = "explicit";
		if (requestedModel.startsWith("agent/") && requestedModel !== "agent/auto") profile = this.get(requestedModel.slice(6));
		else if (requestedModel === "agent/auto" && conversationId && sessions[conversationId]) { profile = this.get(sessions[conversationId]!.profileId); reason = "pinned-segment"; }
		else if (requestedModel === "agent/auto") { const text = JSON.stringify(messages).toLowerCase(), words = new Set(text.match(/[a-z0-9]{3,}/gu) ?? []); profile = enabled.map((item) => ({ item, score: [...words].filter((word) => `${item.slug} ${item.displayName} ${item.description}`.toLowerCase().includes(word)).length })).sort((a, b) => b.score - a.score || a.item.slug.localeCompare(b.item.slug))[0]?.item; reason = "deterministic-capability-match"; }
		if (!profile || profile.status !== "enabled") { if (requestedModel === "hermes-agent") return null; throw new Error("Requested agent profile is unavailable."); }
		const segmentId = conversationId && sessions[conversationId]?.profileId === profile.id ? sessions[conversationId]!.segmentId : crypto.randomUUID(), decision: AgentRoutingDecisionV1 = { schemaVersion: "ai.agent-routing-decision/v1", id: crypto.randomUUID(), conversationId, segmentId, requestedModel, candidates: enabled.map((item) => item.id), selectedProfileId: profile.id, selectedModelAlias: profile.modelAlias, confidence: reason === "explicit" ? 1 : .7, rationale: reason, createdAt: new Date().toISOString() };
		if (conversationId) { sessions[conversationId] = { profileId: profile.id, segmentId }; atomic(`${this.root}/agent-segments.json`, sessions); }
		appendBounded(`${this.root}/routing-decisions.jsonl`, decision); appendEvent("agent.routed", { decisionId: decision.id, profileId: profile.id, segmentId },this.root); return { profile, decision };
	}
	handoff(conversationId: string, profileId: string, state: Record<string, unknown>) { const profile = this.get(profileId); if (!profile || profile.status !== "enabled") throw new Error("Handoff target is unavailable."); const segments = readJson<Record<string, { profileId: string; segmentId: string }>>(`${this.root}/agent-segments.json`, {}), prior = segments[conversationId], segmentId = crypto.randomUUID(); segments[conversationId] = { profileId: profile.id, segmentId }; atomic(`${this.root}/agent-segments.json`, segments); const decision: AgentRoutingDecisionV1 = { schemaVersion: "ai.agent-routing-decision/v1", id: crypto.randomUUID(), conversationId, segmentId, requestedModel: "agent/auto", candidates: this.list().filter((item) => item.status === "enabled").map((item) => item.id), selectedProfileId: profile.id, selectedModelAlias: profile.modelAlias, confidence: 1, rationale: "explicit-task-segment-handoff", priorSegmentId: prior?.segmentId, structuredStateDigest: digest(state), createdAt: new Date().toISOString() }; appendBounded(`${this.root}/routing-decisions.jsonl`, decision); return decision; }
	routing() { return lines(`${this.root}/routing-decisions.jsonl`).reverse() as AgentRoutingDecisionV1[]; }
}

export function profileMarker(profile: AgentProfileV1, segmentId: string) { return `[TREEAI_AGENT_PROFILE:${profile.id}:${segmentId}:${profile.modelAlias}]`; }
export function extractProfileMarker(messages: unknown[]) { for (const message of messages) { if (!message || typeof message !== "object") continue; const content = (message as { content?: unknown }).content; if (typeof content !== "string") continue; const match = content.match(/\[TREEAI_AGENT_PROFILE:([0-9a-f-]{36}):([0-9a-f-]{36}):(library\/[a-z0-9-]+|local-model)\]/u); if (match) return { profileId: match[1]!, segmentId: match[2]!, modelAlias: match[3]!, clean: content.replace(match[0], "").trim() }; } return null; }
