import { ArtifactStore,sha256,verifyManifest,type ArtifactManifest,type Job } from '@ai-platform/common';
import { ListObjectsV2Command,type S3ClientConfig } from '@aws-sdk/client-s3';
import { createPublicKey } from 'node:crypto';
import { readFileSync } from 'node:fs';
import type { Pool } from 'pg';

interface SourceRegistry {sourceId:string;endpoint:string;bucket:string;accessKeyId:string;secretAccessKey:string;trustedPublicKey:string}
type StoredObject=Awaited<ReturnType<ArtifactStore['put']>>;
function objectKey(uri:string,bucket:string){const match=uri.match(/^s3:\/\/([^/]+)\/(.+)$/u);if(!match||match[1]!==bucket)throw new Error(`Object URI is outside the registered ${bucket} bucket.`);return match[2]!;}
export function artifactStoreOptions(endpoint:string,accessKeyId:string,secretAccessKey:string):S3ClientConfig{return{endpoint,region:process.env.S3_REGION??'us-east-1',forcePathStyle:true,requestChecksumCalculation:'WHEN_REQUIRED',responseChecksumValidation:'WHEN_REQUIRED',credentials:{accessKeyId,secretAccessKey}};}
function store(bucket:string,endpoint:string,accessKeyId:string,secretAccessKey:string){return new ArtifactStore(bucket,artifactStoreOptions(endpoint,accessKeyId,secretAccessKey));}
function sourceRegistry(){return JSON.parse(readFileSync(process.env.ARTIFACT_SOURCE_REGISTRY!,'utf8'))as SourceRegistry;}
export async function verifyArtifactSource(createStore:typeof store=store){const source=sourceRegistry(),input=createStore(source.bucket,source.endpoint,source.accessKeyId,source.secretAccessKey),listed=await input.client.send(new ListObjectsV2Command({Bucket:source.bucket,MaxKeys:1})),key=listed.Contents?.[0]?.Key;if(key)await input.bytes(key);}
export async function verifyArtifactDestination(createStore:typeof store=store){const output=createStore(process.env.S3_BUCKET??'ai-inference',process.env.S3_ENDPOINT!,process.env.S3_ACCESS_KEY!,process.env.S3_SECRET_KEY!),marker='treeai-product-credential-v1',provisioned=await stage('destination-credential-read',()=>output.bytes('_health/product-credential-v1'));if(Buffer.from(provisioned).toString('utf8')!==marker)throw new Error('Artifact destination credential marker is invalid.');const bytes=new TextEncoder().encode('treeai-artifact-readiness-v1');await stage('destination-write',()=>output.put('_health/artifact-readiness-v1',bytes,'text/plain'));const read=await stage('destination-read',()=>output.bytes('_health/artifact-readiness-v1'));if(sha256(read)!==sha256(bytes))throw new Error('Artifact destination readiness checksum failed.');}
async function putOnce(store:ArtifactStore,key:string,bytes:Uint8Array,contentType?:string){const digest=sha256(bytes);try{const existing=await store.head(key);if(existing.ContentLength===bytes.byteLength&&existing.Metadata?.sha256===digest)return{uri:`s3://${store.bucket}/${key}`,size:bytes.byteLength,sha256:digest};}catch{/* missing or incomplete objects are copied */}return store.put(key,bytes,contentType);}
async function stage<T>(name:string,operation:()=>Promise<T>){try{return await operation();}catch(error){throw new Error(`${name} failed: ${error instanceof Error?error.message:String(error)}`);}}

export function createArtifactImporter(pool:Pool){
  return async(job:Job)=>{
    const request=job.request as{sourceId?:string;manifestUri?:string};
    const source=sourceRegistry();
    if(request.sourceId!==source.sourceId||!request.manifestUri)throw new Error('Unknown artifact source or missing manifest URI.');
    const input=store(source.bucket,source.endpoint,source.accessKeyId,source.secretAccessKey);
    const manifestBytes=await stage('source-manifest-read',()=>input.bytes(objectKey(request.manifestUri!,source.bucket)));
    const manifest=JSON.parse(Buffer.from(manifestBytes).toString('utf8'))as ArtifactManifest&{library?:{id?:string;slug?:string;mode?:string;promotionEligible?:boolean};adapter?:ArtifactManifest['adapter']&{purpose?:string}};
    if(!verifyManifest(manifest,createPublicKey(source.trustedPublicKey)))throw new Error('Artifact manifest signature is invalid.');
    if(!['ai.artifact/v1','ai.artifact/v2','ai.artifact/v3'].includes(manifest.schemaVersion)||manifest.artifactType!=='lora-adapter'||manifest.adapter?.format!=='peft')throw new Error('Manifest is not a compatible PEFT LoRA adapter.');
    if((manifest.adapter as any)?.modality==='composed'&&process.env.TREEAI_MULTIMODAL_LORA_ENABLED!=='true')throw new Error('Multimodal LoRA serving has not passed this host machine profile.');
    if(manifest.baseModel?.id!==(process.env.SOURCE_MODEL??'Qwen/Qwen3.5-4B')||manifest.baseModel?.revision!==(process.env.SOURCE_MODEL_REVISION??'851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a'))throw new Error('Adapter base model revision is incompatible with this inference deployment.');
    const output=store(process.env.S3_BUCKET??'ai-inference',process.env.S3_ENDPOINT!,process.env.S3_ACCESS_KEY!,process.env.S3_SECRET_KEY!);
    const copied:StoredObject[]=[];
    for(const object of manifest.objects){const bytes=await stage('source-adapter-read',()=>input.bytes(objectKey(object.uri,source.bucket)));if(bytes.byteLength!==object.size||sha256(bytes)!==object.sha256)throw new Error(`Checksum verification failed for ${object.uri}.`);copied.push(await stage('destination-adapter-write',()=>putOnce(output,`objects/${object.sha256}`,bytes)));}
    let libraryEvaluationObject:StoredObject|undefined,libraryMultimodalEvaluation:{evaluation:StoredObject;images:Array<StoredObject&{relativePath:string}>}|undefined;
    if(manifest.library){const datasetUri=manifest.datasets?.[0];if(typeof datasetUri!=='string')throw new Error('Library adapter has no immutable dataset manifest.');const datasetBytes=await stage('source-dataset-read',()=>input.bytes(objectKey(datasetUri,source.bucket))),dataset=JSON.parse(Buffer.from(datasetBytes).toString('utf8'))as{schemaVersion?:string;evaluationObject?:{uri:string;size:number;sha256:string};multimodal?:{evaluationObject?:{uri:string;size:number;sha256:string};imageObjects?:Array<{uri:string;relativePath:string;size:number;sha256:string}>}};if(!['ai.library-dataset/v1','ai.library-dataset/v2'].includes(dataset.schemaVersion??''))throw new Error('Library adapter dataset manifest is incompatible.');if(manifest.library.promotionEligible&&!dataset.evaluationObject)throw new Error('Promotable library adapter has no held-out evaluation corpus.');if(dataset.evaluationObject){const heldout=await stage('source-heldout-read',()=>input.bytes(objectKey(dataset.evaluationObject!.uri,source.bucket)));if(heldout.byteLength!==dataset.evaluationObject.size||sha256(heldout)!==dataset.evaluationObject.sha256)throw new Error('Held-out evaluation corpus checksum failed.');libraryEvaluationObject=await stage('destination-heldout-write',()=>putOnce(output,`evaluation/${dataset.evaluationObject!.sha256}.jsonl`,heldout,'application/x-ndjson'));}if((manifest.adapter as any)?.modality==='composed'){const visual=dataset.multimodal?.evaluationObject;if(!visual)throw new Error('Composed promotable adapter has no held-out visual corpus.');const visualBytes=await stage('source-visual-heldout-read',()=>input.bytes(objectKey(visual.uri,source.bucket)));if(visualBytes.byteLength!==visual.size||sha256(visualBytes)!==visual.sha256)throw new Error('Held-out visual corpus checksum failed.');const evaluation=await stage('destination-visual-heldout-write',()=>putOnce(output,`evaluation/${visual.sha256}-multimodal.jsonl`,visualBytes,'application/x-ndjson')),images=[];for(const item of dataset.multimodal?.imageObjects??[]){const bytes=await stage('source-visual-image-read',()=>input.bytes(objectKey(item.uri,source.bucket)));if(bytes.byteLength!==item.size||sha256(bytes)!==item.sha256)throw new Error('Held-out visual image checksum failed.');images.push({...await stage('destination-visual-image-write',()=>putOnce(output,`evaluation/images/${item.sha256}`,bytes)),relativePath:item.relativePath});}libraryMultimodalEvaluation={evaluation,images};}}
    const manifestDigest=sha256(manifestBytes);const stored=await stage('destination-manifest-write',()=>putOnce(output,`manifests/${manifest.artifactId}/${manifestDigest}.json`,manifestBytes,'application/json'));
    if(manifest.library&&(!manifest.library.id||!/^[a-z0-9][a-z0-9-]{0,62}$/u.test(manifest.library.slug??'')||manifest.adapter?.purpose!=='continual-pretraining'))throw new Error('Library adapter metadata is invalid.');
    const candidate=await stage('candidate-persist',()=>pool.query(`INSERT INTO candidates(manifest_uri,manifest,status,purpose,library_id,library_slug) VALUES($1,$2,'inactive',$3,$4,$5) ON CONFLICT(manifest_uri) DO UPDATE SET manifest=excluded.manifest,purpose=excluded.purpose,library_id=excluded.library_id,library_slug=excluded.library_slug RETURNING id`,[stored.uri,{sourceManifest:manifest,copiedObjects:copied,sourceId:source.sourceId,libraryEvaluationObject,libraryMultimodalEvaluation},manifest.adapter?.purpose??null,manifest.library?.id??null,manifest.library?.slug??null]));
    return `candidate://${candidate.rows[0].id}`;
  };
}
