import {atomic,appendEvent,readJson,redactKnownCredentials,required,stateRoot} from './shared.js';
import {AgentProfiles} from './agents/index.js';
type Cycle={id:string;libraryId:string;mode:'smoke'|'standard';state:string;phase:string;snapshotId?:string;trainingRunId?:string;candidateId?:string;error?:string;createdAt:string;updatedAt:string};
const terminal=new Set(['succeeded','rejected','failed','cancelled']),wait=(milliseconds:number)=>new Promise(resolve=>setTimeout(resolve,milliseconds));
export function transitionFailure(mode:'awake'|'sleep',work:any){const details=[work?.error,work?.result?.reason].filter(value=>typeof value==='string'&&value).join('; '),safe=redactKnownCredentials(details).replace(/[\u0000-\u001f\u007f]/gu,' ').slice(0,500);return`Factory ${mode} transition ${String(work?.state??'failed')}${safe?`: ${safe}`:''}`;}
export function transitionObservation(target:'awake'|'sleep',workState:string,observedMode:string,elapsed:number){if(workState==='succeeded'||observedMode===target)return'succeeded';if(['failed','postponed'].includes(workState))return'failed';if(elapsed>10_000&&['queued','running'].includes(workState)&&['awake','sleep','degraded'].includes(observedMode)&&observedMode!==target)return'interrupted';return'pending';}
const processingTypes=new Set(['library.document.classify','library.document.marker']),activeStates=new Set(['queued','claimed','running','cancelling']);
export function processingTimeout(environment:NodeJS.ProcessEnv=process.env){const value=Number(environment.LIBRARY_PROCESSING_TIMEOUT_MS??28_800_000);if(!Number.isSafeInteger(value)||value<3_600_000||value>86_400_000)throw new Error('LIBRARY_PROCESSING_TIMEOUT_MS must be an integer from 3600000 through 86400000');return value;}
function currentRevisions(documents:any[]){return new Map(documents.filter(item=>!['ready','deleted','quarantined'].includes(item.state)&&item.currentRevision?.id).map(item=>[item.currentRevision.id,item]));}
export function processingRetries(documents:any[],jobs:any[]){const revisions=currentRevisions(documents),active=new Set(jobs.filter(item=>processingTypes.has(item.type)&&activeStates.has(item.state)).map(item=>item.request?.revisionId));return jobs.filter(item=>processingTypes.has(item.type)&&item.state==='failed'&&revisions.has(item.request?.revisionId)&&!active.has(item.request?.revisionId)).map(item=>revisions.get(item.request.revisionId)).filter((item,index,items)=>items.findIndex(value=>value.id===item.id)===index);}
export function documentProcessingFailure(documents:any[],jobs:any[]){const revisions=currentRevisions(documents),active=new Set(jobs.filter(item=>processingTypes.has(item.type)&&activeStates.has(item.state)).map(item=>item.request?.revisionId)),failed=jobs.find(item=>processingTypes.has(item.type)&&item.state==='failed'&&revisions.has(item.request?.revisionId)&&!active.has(item.request?.revisionId));if(!failed)return;const detail=redactKnownCredentials(String(failed.error?.message??'unknown worker failure')).replace(/[\u0000-\u001f\u007f]/gu,' ').slice(0,500);return`Document processing failed for job ${String(failed.id)}: ${detail}`;}
export class LibraryCycles{
	private path=`${stateRoot}/library-cycles.json`;
	constructor(private requestFetch:typeof fetch=fetch){for(const cycle of this.list().filter(item=>!terminal.has(item.state))){cycle.error='Lab controller restarted while the library cycle was active; retry explicitly.';this.phase(cycle,'failed','failed');}}
	list(){return readJson<Cycle[]>(this.path,[]);} get(id:string){return this.list().find(item=>item.id===id);}
	private save(cycle:Cycle){const values=this.list(),index=values.findIndex(item=>item.id===cycle.id);if(index>=0)values[index]=cycle;else values.push(cycle);atomic(this.path,values.slice(-1000));appendEvent('library-cycle.phase',{id:cycle.id,libraryId:cycle.libraryId,state:cycle.state,phase:cycle.phase});}
	private phase(cycle:Cycle,phase:string,state=cycle.state){cycle.phase=phase;cycle.state=state;cycle.updatedAt=new Date().toISOString();this.save(cycle);}
	private async api(base:string,keyName:string,path:string,method='GET',body?:unknown,idempotencyKey?:string){const response=await this.requestFetch(`${base}${path}`,{method,headers:{authorization:`Bearer ${required(keyName)}`,'content-type':'application/json',...(idempotencyKey?{'idempotency-key':idempotencyKey}:{})},body:body===undefined?undefined:JSON.stringify(body)}),value=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`${method} ${path} returned ${response.status}: ${JSON.stringify(value)}`);return value as any;}
	private training(path:string,method='GET',body?:unknown,key?:string){return this.api(process.env.TRAINING_URL??'http://training-api:4780','AI_FACTORY_TRAINING_KEY',path,method,body,key);} private inference(path:string,method='GET',body?:unknown,key?:string){return this.api(process.env.INFERENCE_CONTROL_URL??'http://inference-api:4770','AI_FACTORY_INFERENCE_KEY',path,method,body,key);} private factory(path:string,method='GET',body?:unknown,key?:string){return this.api(process.env.FACTORY_URL??'https://host.docker.internal:4790','AI_FACTORY_CONTROL_KEY',path,method,body,key);}
	private async job(product:'training'|'inference',id:string,timeout=86_400_000){const started=Date.now();while(Date.now()-started<timeout){const value=await(product==='training'?this.training(`/v1/jobs/${id}`):this.inference(`/v1/jobs/${id}`));if(value.state==='succeeded')return value;if(['failed','cancelled'].includes(value.state))throw new Error(`${product} job ${id} ${value.state}: ${JSON.stringify(value.error??{})}`);await wait(2000);}throw new Error(`${product} job ${id} timed out`);}
	private async mode(value:'awake'|'sleep',cycle:Cycle){this.phase(cycle,`mode-${value}`);const transition=await this.factory('/v1/mode','POST',{mode:value,idempotencyKey:`library-cycle:${cycle.id}:${value}`}),started=Date.now();while(Date.now()-started<600_000){const current=await this.factory(`/v1/transitions/${transition.id}`),observed=await this.factory('/v1/mode'),outcome=transitionObservation(value,String(current.state),String(observed.mode),Date.now()-started);if(outcome==='succeeded')return;if(outcome==='failed')throw new Error(transitionFailure(value,current));if(outcome==='interrupted')throw new Error(`Factory ${value} transition was interrupted; observed mode is ${String(observed.mode)}`);await wait(2000);}throw new Error(`Factory ${value} transition timed out`);}
	start(libraryId:string,mode:'smoke'|'standard',idempotencyKey:string){const existing=this.list().find(item=>item.id===idempotencyKey);if(existing)return existing;if(this.list().some(item=>!terminal.has(item.state)))throw new Error('A library cycle is already active');const now=new Date().toISOString(),cycle:Cycle={id:idempotencyKey,libraryId,mode,state:'running',phase:'freeze',createdAt:now,updatedAt:now};this.save(cycle);void this.run(cycle);return cycle;}
	private async waitDocuments(cycle:Cycle){this.phase(cycle,'process');const initialDocuments=(await this.training(`/v1/libraries/${cycle.libraryId}/documents`)).items??[],initialJobs=(await this.training('/v1/jobs')).items??[];if(initialDocuments.some((item:any)=>item.state==='quarantined'))throw new Error('Snapshot contains a quarantined document');for(const document of processingRetries(initialDocuments,initialJobs))await this.training(`/v1/libraries/${cycle.libraryId}/documents/${document.id}/retry`,'POST',{},`${cycle.id}:document-retry:${document.id}`);const started=Date.now(),timeout=processingTimeout();while(Date.now()-started<timeout){const documents=(await this.training(`/v1/libraries/${cycle.libraryId}/documents`)).items??[];if(documents.some((item:any)=>item.state==='quarantined'))throw new Error('Snapshot contains a quarantined document');const failure=documentProcessingFailure(documents,(await this.training('/v1/jobs')).items??[]);if(failure)throw new Error(failure);if(documents.length&&documents.every((item:any)=>['ready','deleted'].includes(item.state)))return;await wait(3000);}throw new Error(`Library document processing timed out after ${timeout}ms`);}
	private async prepare(cycle:Cycle,snapshotId:string){this.phase(cycle,'dataset');let sequenceLength=4096,prepared=await this.training(`/v1/libraries/${cycle.libraryId}/snapshots/${snapshotId}/prepare`,'POST',{sequenceLength},`${cycle.id}:dataset-qualification`);await this.job('training',prepared.id);let snapshot=((await this.training(`/v1/libraries/${cycle.libraryId}/snapshots`)).items??[]).find((item:any)=>item.id===snapshotId);if(!snapshot?.trainUri)throw new Error('Prepared snapshot has no immutable training object');this.phase(cycle,'qualify');const qualification=await this.training('/v1/library-training-profile/qualify','POST',{trainUri:snapshot.trainUri},`${cycle.id}:qualify`),qualified=await this.job('training',qualification.id);sequenceLength=Number(String(qualified.resultManifest).replace(/^profile:\/\//u,''));if(sequenceLength!==4096){this.phase(cycle,'dataset-qualified');prepared=await this.training(`/v1/libraries/${cycle.libraryId}/snapshots/${snapshotId}/prepare`,'POST',{sequenceLength},`${cycle.id}:dataset-${sequenceLength}`);await this.job('training',prepared.id);snapshot=((await this.training(`/v1/libraries/${cycle.libraryId}/snapshots`)).items??[]).find((item:any)=>item.id===snapshotId);}return{snapshot,sequenceLength};}
	private async train(cycle:Cycle,snapshot:any,sequenceLength:number){this.phase(cycle,'training-language');let run=await this.training('/v1/library-runs','POST',{libraryId:cycle.libraryId,snapshotId:snapshot.id,sequenceLength},`${cycle.id}:training-language`);cycle.trainingRunId=run.id;this.save(cycle);await this.job('training',run.phaseJobId);if(Number(snapshot.multimodalExampleCount)>0){this.phase(cycle,'qualify-multimodal');const qualified=await this.job('training',(await this.training('/v1/library-multimodal-profile/qualify','POST',{datasetManifest:snapshot.manifestUri},`${cycle.id}:qualify-multimodal`)).id),match=String(qualified.resultManifest).match(/^multimodal-profile:\/\/(\d+)\/(\d+)$/u);if(!match)throw new Error('Multimodal qualification returned an invalid profile');this.phase(cycle,'training-multimodal');run=await this.training(`/v1/library-runs/${run.id}/multimodal`,'POST',{sequenceLength:Number(match[1]),maxPixels:Number(match[2])},`${cycle.id}:training-multimodal`);await this.job('training',run.visionPhaseJobId);this.phase(cycle,'compose');run=await this.training(`/v1/library-runs/${run.id}/compose`,'POST',{},`${cycle.id}:compose`);await this.job('training',run.compositionPhaseJobId);}return this.training(`/v1/library-runs/${run.id}`);}
	private async import(cycle:Cycle,run:any){this.phase(cycle,'import');const manifestUri=run.composedAdapterManifestUri??run.adapterManifestUri,job=await this.inference('/v1/adapters/import','POST',{idempotencyKey:`${cycle.id}:import`,input:{sourceId:'training-local',manifestUri}}),done=await this.job('inference',job.id),candidateId=String(done.resultManifest).replace(/^candidate:\/\//u,''),library=await this.training(`/v1/libraries/${cycle.libraryId}`);new AgentProfiles().draft({libraryId:cycle.libraryId,librarySlug:String(library.slug),candidateId,baseModelRevision:run.baseModelRevision});cycle.candidateId=candidateId;this.save(cycle);return candidateId;}
	private async evaluate(cycle:Cycle,candidateId:string){const candidate=await this.inference(`/v1/adapters/${candidateId}`),current=await this.inference(`/v1/library-deployments/${cycle.libraryId}`).catch(()=>null)as any,activeId=current?.candidateId??(process.env.BASE_MODEL??'Qwen/Qwen3.5-4B'),visual=candidate.manifest.libraryMultimodalEvaluation;this.phase(cycle,'evaluate');const general=await this.job('inference',(await this.inference('/v1/evaluations','POST',{idempotencyKey:`${cycle.id}:general`,input:{candidates:[activeId,{model:candidateId,manifest:candidate.manifest}],suite:'default-v1'}})).id);let visualResults:{}={};if(visual){const base=await this.job('inference',(await this.inference('/v1/evaluations','POST',{idempotencyKey:`${cycle.id}:base-visual`,input:{metric:'visual-grounding',candidateId:activeId,evaluationObject:visual}})).id),next=await this.job('inference',(await this.inference('/v1/evaluations','POST',{idempotencyKey:`${cycle.id}:candidate-visual`,input:{metric:'visual-grounding',candidateId,evaluationObject:visual}})).id);visualResults={baseVisualManifest:base.resultManifest,candidateVisualManifest:next.resultManifest};}const ranking=await this.inference('/v1/rankings','POST',{idempotencyKey:`${cycle.id}:ranking`,input:{policy:'library-strict-improvement-v1',candidateId,generalManifest:general.resultManifest,...visualResults}});return this.job('inference',ranking.id);}
	private async run(cycle:Cycle){let sleeping=false;try{await this.training(`/v1/libraries/${cycle.libraryId}`);const snapshot=await this.training(`/v1/libraries/${cycle.libraryId}/snapshots`,'POST',{mode:cycle.mode},`${cycle.id}:freeze`);cycle.snapshotId=snapshot.id;this.phase(cycle,'drain');await this.mode('sleep',cycle);sleeping=true;await this.waitDocuments(cycle);const prepared=await this.prepare(cycle,snapshot.id),run=await this.train(cycle,prepared.snapshot,prepared.sequenceLength);this.phase(cycle,'awake');await this.mode('awake',cycle);sleeping=false;const candidateId=await this.import(cycle,run);if(cycle.mode==='smoke'){this.phase(cycle,'complete','succeeded');return;}const ranking=await this.evaluate(cycle,candidateId);this.phase(cycle,'promote');const promotion=await this.inference('/v1/promotions','POST',{idempotencyKey:`${cycle.id}:promotion`,input:{candidateId,libraryId:cycle.libraryId,rankingManifest:ranking.resultManifest}});try{await this.job('inference',promotion.id);this.phase(cycle,'complete','succeeded');}catch{this.phase(cycle,'complete','rejected');}}catch(error){cycle.error=error instanceof Error?error.message:String(error);if(sleeping)try{await this.mode('awake',cycle);}catch(awakeError){cycle.error+=`; awake recovery failed: ${String(awakeError)}`;}this.phase(cycle,'failed','failed');}}
}
