#!/usr/bin/env node
import{serve}from'@hono/node-server';import{createHash}from'node:crypto';import{readFileSync}from'node:fs';import{Hono}from'hono';
type Options={fetch?:typeof fetch;openWebUiUrl?:string;trainingUrl?:string;trainingKey?:string;onError?:(error:unknown)=>void};
function slug(value:string){const result=value.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/gu,'-').replace(/^-|-$/gu,'').slice(0,63);return result||'library';}
function json(value:FormDataEntryValue|null){if(typeof value!=='string')return{};try{return JSON.parse(value)as Record<string,unknown>;}catch{return{};}}
function safeHeaders(input:Headers){const result=new Headers(input);result.delete('host');result.delete('content-length');return result;}
function trainingHeaders(key:string,idempotency:string,contentType='application/json'){return{authorization:`Bearer ${key}`,'idempotency-key':idempotency,'content-type':contentType};}
export function createLibraryBridge(options:Options={}){
	const app=new Hono(),requestFetch=options.fetch??fetch,upstream=options.openWebUiUrl??process.env.OPEN_WEBUI_URL??'http://open-webui:8080',training=options.trainingUrl??process.env.TRAINING_URL??'http://training-api:4780',key=options.trainingKey??readFileSync(process.env.TRAINING_INGEST_KEY_FILE??'/run/secrets/training-ingest-key','utf8').trim(),report=options.onError??((error)=>process.stderr.write(`${error instanceof Error?error.message:String(error)}\n`));
	async function call(path:string,init:RequestInit){const response=await requestFetch(`${training}${path}`,init);if(!response.ok)throw new Error(`Training library request failed with ${response.status}`);return response.json()as Promise<Record<string,unknown>>;}
	async function library(id:string,authorization:string){const response=await requestFetch(`${upstream}/api/v1/knowledge/${encodeURIComponent(id)}`,{headers:{authorization}});if(!response.ok)throw new Error(`Open WebUI knowledge lookup failed with ${response.status}`);const value=await response.json()as Record<string,unknown>,name=String(value.name??value.title??id);return call('/v1/libraries',{method:'POST',headers:trainingHeaders(key,`open-webui-library:${id}`),body:JSON.stringify({sourceKind:'open-webui',externalId:id,slug:slug(name),name,description:String(value.description??'')})});}
	async function observeUpload(request:Request,response:Response){
		if(!response.ok||request.method!=='POST'||!/^\/api\/v1\/files\/?$/u.test(new URL(request.url).pathname))return;
		const contentLength=Number(request.headers.get('content-length')??0);if(contentLength>100*1024*1024)return;
		const form=await request.formData(),file=form.get('file');if(!(file instanceof File))return;const values=json(form.get('metadata')),knowledgeId=String(values.knowledge_id??values.knowledgeId??'');if(!knowledgeId)return;
		const authorization=request.headers.get('authorization')??'';if(!authorization)return;const upstreamValue=await response.clone().json()as Record<string,unknown>,externalId=String(upstreamValue.id??'');if(!externalId)return;
		const registered=await library(knowledgeId,authorization),libraryId=String(registered.id),bytes=new Uint8Array(await file.arrayBuffer()),sha256=createHash('sha256').update(bytes).digest('hex'),directoryExternalId=values.directory_id?String(values.directory_id):undefined,relativePath=String(values.path??file.name);
		const document=Buffer.from(JSON.stringify({externalId,filename:file.name,relativePath,directoryExternalId,declaredMimeType:file.type||'application/octet-stream',provenance:{source:'open-webui',knowledgeId}})).toString('base64url');
		await call(`/v1/libraries/${encodeURIComponent(libraryId)}/documents`,{method:'POST',headers:{...trainingHeaders(key,`open-webui-file:${externalId}:${sha256}`,file.type||'application/octet-stream'),'x-content-sha256':sha256,'x-treeai-document':document},body:bytes});
	}
	async function observeRelationship(request:Request,response:Response){
		if(!response.ok||!['POST','PUT','PATCH','DELETE'].includes(request.method))return;const path=new URL(request.url).pathname,match=path.match(/^\/api\/v1\/knowledge\/([^/]+)\/(.+)$/u);if(!match)return;const authorization=request.headers.get('authorization')??'';if(!authorization)return;const registered=await library(decodeURIComponent(match[1]!),authorization),libraryId=String(registered.id),operation=match[2]!,body=await request.json().catch(()=>({}))as Record<string,unknown>;
		if(operation==='file/move'){const externalId=String(body.file_id??''),directoryExternalId=body.directory_id?String(body.directory_id):undefined;if(externalId)await call(`/v1/libraries/${libraryId}/relationships`,{method:'POST',headers:trainingHeaders(key,`open-webui-move:${externalId}:${directoryExternalId??'root'}`),body:JSON.stringify({documents:[{externalId,directoryExternalId}]})});return;}
		if(operation==='file/remove'){const externalId=String(body.file_id??'');if(externalId)await call(`/v1/libraries/${libraryId}/documents/external/${encodeURIComponent(externalId)}`,{method:'DELETE',headers:trainingHeaders(key,`open-webui-delete:${externalId}`)});return;}
		const directory=operation.match(/^dirs(?:\/([^/]+)\/update|\/create)$/u);if(!directory)return;const responseValue=await response.clone().json().catch(()=>({}))as Record<string,unknown>,externalId=directory[1]??String(responseValue.id??'');if(!externalId)return;await call(`/v1/libraries/${libraryId}/relationships`,{method:'POST',headers:trainingHeaders(key,`open-webui-directory:${externalId}:${String(body.name??'')}:${String(body.parent_id??'root')}`),body:JSON.stringify({directories:[{externalId,name:String(body.name??responseValue.name??externalId),parentExternalId:body.parent_id?String(body.parent_id):undefined,relativePath:String(body.path??body.name??responseValue.name??externalId),deleted:false}]})});
	}
	app.get('/healthz',context=>context.json({ok:true}));app.all('*',async context=>{const uploadCapture=context.req.raw.clone(),relationshipCapture=context.req.raw.clone(),headers=safeHeaders(context.req.raw.headers),init:RequestInit&{duplex:'half'}={method:context.req.method,headers,body:['GET','HEAD'].includes(context.req.method)?undefined:context.req.raw.body,duplex:'half',signal:context.req.raw.signal},response=await requestFetch(`${upstream}${context.req.path}${new URL(context.req.url).search}`,init);void Promise.all([observeUpload(uploadCapture,response.clone()),observeRelationship(relationshipCapture,response.clone())]).catch(report);return new Response(response.body,{status:response.status,headers:response.headers});});return app;
}
if(process.env.NODE_ENV!=='test')serve({fetch:createLibraryBridge().fetch,hostname:'0.0.0.0',port:Number(process.env.PORT??8082)});
