#!/usr/bin/env node
import{serve}from'@hono/node-server';import{createHash}from'node:crypto';import{readFileSync}from'node:fs';import{Hono}from'hono';
type Options={fetch?:typeof fetch;openWebUiUrl?:string;trainingUrl?:string;trainingKey?:string;controllerUrl?:string;actionKey?:string;onError?:(error:unknown)=>void};
function slug(value:string){const result=value.normalize('NFKD').toLowerCase().replace(/[^a-z0-9]+/gu,'-').replace(/^-|-$/gu,'').slice(0,63);return result||'library';}
function json(value:FormDataEntryValue|null){if(typeof value!=='string')return{};try{return JSON.parse(value)as Record<string,unknown>;}catch{return{};}}
function safeHeaders(input:Headers){const result=new Headers(input);result.delete('host');result.delete('content-length');return result;}
function trainingHeaders(key:string,idempotency:string,contentType='application/json'){return{authorization:`Bearer ${key}`,'idempotency-key':idempotency,'content-type':contentType};}
function relationshipPath(...values:unknown[]){for(const value of values){if(typeof value!=='string'||!value.trim())continue;const path=value.trim().replaceAll('\\','/'),parts=path.split('/');if(path.startsWith('/')||parts.some(part=>part==='..'))throw new Error('Open WebUI relationship path must remain relative');const normalized=parts.filter(part=>part&&part!=='.').join('/');if(normalized)return normalized;}throw new Error('Open WebUI file has no safe relationship path');}
async function trainingError(response:Response){const value=await response.clone().json().catch(()=>null)as{error?:{code?:unknown;message?:unknown}}|null,code=value?.error?.code,message=value?.error?.message;if(typeof code==='string'&&/^[a-z][a-z0-9_]{0,63}$/u.test(code)&&typeof message==='string'){const safe=message.replace(/[\u0000-\u001f\u007f]/gu,' ').slice(0,500);return`Training library request failed (${code}): ${safe}`;}return`Training library request failed with ${response.status}`;}
export function createLibraryBridge(options:Options={}){
	const app=new Hono(),requestFetch=options.fetch??fetch,upstream=options.openWebUiUrl??process.env.OPEN_WEBUI_URL??'http://open-webui:8080',training=options.trainingUrl??process.env.TRAINING_URL??'http://training-api:4780',key=options.trainingKey??readFileSync(process.env.TRAINING_INGEST_KEY_FILE??'/run/secrets/training-ingest-key','utf8').trim(),report=options.onError??((error)=>process.stderr.write(`${error instanceof Error?error.message:String(error)}\n`));
	const controller=options.controllerUrl??process.env.LAB_CONTROLLER_URL??'http://controller:8081',actionKey=()=>options.actionKey??readFileSync(process.env.LAB_LIBRARY_ACTION_KEY_FILE??'/run/secrets/lab-library-action-key','utf8').trim();
	async function call(path:string,init:RequestInit){const response=await requestFetch(`${training}${path}`,init);if(!response.ok)throw new Error(await trainingError(response));return response.json()as Promise<Record<string,unknown>>;}
	async function library(id:string,authorization:string){const response=await requestFetch(`${upstream}/api/v1/knowledge/${encodeURIComponent(id)}`,{headers:{authorization}});if(!response.ok)throw new Error(`Open WebUI knowledge lookup failed with ${response.status}`);const value=await response.json()as Record<string,unknown>,name=String(value.name??value.title??id);return call('/v1/libraries',{method:'POST',headers:trainingHeaders(key,`open-webui-library:${id}`),body:JSON.stringify({sourceKind:'open-webui',externalId:id,slug:slug(name),name,description:String(value.description??'')})});}
	async function ingest(libraryId:string,knowledgeId:string,externalId:string,filename:string,relativePath:string,mime:string,bytes:Uint8Array,directoryExternalId?:string){if(bytes.byteLength>100*1024*1024)throw new Error('Open WebUI file exceeds 100 MiB');const sha256=createHash('sha256').update(bytes).digest('hex'),document=Buffer.from(JSON.stringify({externalId,filename,relativePath,directoryExternalId,declaredMimeType:mime||'application/octet-stream',provenance:{source:'open-webui',knowledgeId}})).toString('base64url');return call(`/v1/libraries/${encodeURIComponent(libraryId)}/documents`,{method:'POST',headers:{...trainingHeaders(key,`open-webui-file:${externalId}:${sha256}`,mime||'application/octet-stream'),'x-content-sha256':sha256,'x-treeai-document':document},body:Buffer.from(bytes)});}
	async function observeUpload(request:Request,response:Response){
		if(!response.ok||request.method!=='POST'||!/^\/api\/v1\/files\/?$/u.test(new URL(request.url).pathname))return;
		const contentLength=Number(request.headers.get('content-length')??0);if(contentLength>100*1024*1024)return;
		const form=await request.formData(),file=form.get('file');if(!(file instanceof File))return;const values=json(form.get('metadata')),knowledgeId=String(values.knowledge_id??values.knowledgeId??'');if(!knowledgeId)return;
		const authorization=request.headers.get('authorization')??'';if(!authorization)return;const upstreamValue=await response.clone().json()as Record<string,unknown>,externalId=String(upstreamValue.id??'');if(!externalId)return;
		const registered=await library(knowledgeId,authorization),libraryId=String(registered.id),bytes=new Uint8Array(await file.arrayBuffer()),directoryExternalId=values.directory_id?String(values.directory_id):undefined,relativePath=relationshipPath(values.path,file.name);await ingest(libraryId,knowledgeId,externalId,file.name,relativePath,file.type,bytes,directoryExternalId);
	}
	async function observeRelationship(request:Request,response:Response){
		if(!response.ok||!['POST','PUT','PATCH','DELETE'].includes(request.method))return;const path=new URL(request.url).pathname,match=path.match(/^\/api\/v1\/knowledge\/([^/]+)\/(.+)$/u);if(!match)return;const authorization=request.headers.get('authorization')??'';if(!authorization)return;const registered=await library(decodeURIComponent(match[1]!),authorization),libraryId=String(registered.id),operation=match[2]!,body=await request.json().catch(()=>({}))as Record<string,unknown>;
		if(operation==='file/move'){const externalId=String(body.file_id??''),directoryExternalId=body.directory_id?String(body.directory_id):undefined;if(externalId)await call(`/v1/libraries/${libraryId}/relationships`,{method:'POST',headers:trainingHeaders(key,`open-webui-move:${externalId}:${directoryExternalId??'root'}`),body:JSON.stringify({documents:[{externalId,directoryExternalId}]})});return;}
		if(operation==='file/remove'){const externalId=String(body.file_id??'');if(externalId)await call(`/v1/libraries/${libraryId}/documents/external/${encodeURIComponent(externalId)}`,{method:'DELETE',headers:trainingHeaders(key,`open-webui-delete:${externalId}`)});return;}
		const directory=operation.match(/^dirs(?:\/([^/]+)\/update|\/create)$/u);if(!directory)return;const responseValue=await response.clone().json().catch(()=>({}))as Record<string,unknown>,externalId=directory[1]??String(responseValue.id??'');if(!externalId)return;await call(`/v1/libraries/${libraryId}/relationships`,{method:'POST',headers:trainingHeaders(key,`open-webui-directory:${externalId}:${String(body.name??'')}:${String(body.parent_id??'root')}`),body:JSON.stringify({directories:[{externalId,name:String(body.name??responseValue.name??externalId),parentExternalId:body.parent_id?String(body.parent_id):undefined,relativePath:String(body.path??body.name??responseValue.name??externalId),deleted:false}]})});
	}
	async function chatLibrary(chatId:string,authorization:string){const response=await requestFetch(`${upstream}/api/v1/chats/${encodeURIComponent(chatId)}`,{headers:{authorization}});if(!response.ok)throw new Error('Open WebUI chat authorization failed');const value=await response.json()as Record<string,unknown>,chat=(value.chat??value)as Record<string,unknown>,files=(chat.files??[])as Array<Record<string,unknown>>,ids=[...new Set(files.filter(item=>item.type==='collection').map(item=>String(item.id??item.collection_id??'')).filter(Boolean))];if(ids.length!==1)throw new Error(`Train Library requires exactly one attached Knowledge Base; found ${ids.length}.`);return ids[0]!;}
	async function preview(knowledgeId:string,authorization:string){const registered=await library(knowledgeId,authorization),libraryId=String(registered.id),value=await call(`/v1/libraries/${encodeURIComponent(libraryId)}/documents`,{method:'GET',headers:trainingHeaders(key,`open-webui-preview:${knowledgeId}`)}),documents=(value.items??[])as Array<Record<string,any>>,ready=documents.filter(item=>item.state==='ready').length,rejected=documents.filter(item=>['quarantined','deleted'].includes(String(item.state))).length,pending=documents.length-ready-rejected,estimatedTokens=documents.reduce((total,item)=>total+Number(item.currentRevision?.tokenCount??0),0);return{id:libraryId,knowledgeId,name:String(registered.name),counts:{ready,pending,rejected,total:documents.length},estimatedTokens};}
	async function knowledgeFiles(knowledgeId:string,authorization:string){const items:Array<Record<string,unknown>>=[];for(let page=1;page<=1000;page++){const response=await requestFetch(`${upstream}/api/v1/knowledge/${encodeURIComponent(knowledgeId)}/files?page=${page}&limit=100`,{headers:{authorization}});if(!response.ok)throw new Error('Open WebUI knowledge files cannot be listed');const value=await response.json()as Record<string,unknown>,batch=value.items;if(!Array.isArray(batch))throw new Error('Open WebUI knowledge files response is malformed');items.push(...batch as Array<Record<string,unknown>>);const total=Number(value.total);if(!Number.isSafeInteger(total)||total<0)throw new Error('Open WebUI knowledge file total is invalid');if(items.length>=total)return items;if(batch.length===0)throw new Error('Open WebUI knowledge file pagination ended before its declared total');}throw new Error('Open WebUI knowledge file pagination exceeded 1000 pages');}
	async function reconcile(knowledgeId:string,authorization:string){const registered=await library(knowledgeId,authorization),files=await knowledgeFiles(knowledgeId,authorization);let accepted=0;for(const item of files){const externalId=String(item.id??item.file_id??'');if(!externalId)continue;const metadataResponse=await requestFetch(`${upstream}/api/v1/files/${encodeURIComponent(externalId)}`,{headers:{authorization}}),contentResponse=await requestFetch(`${upstream}/api/v1/files/${encodeURIComponent(externalId)}/content`,{headers:{authorization}});if(!metadataResponse.ok||!contentResponse.ok)throw new Error(`Open WebUI file ${externalId} cannot be reconciled`);const metadata=await metadataResponse.json()as Record<string,unknown>,meta=(metadata.meta??{})as Record<string,unknown>,relationship=(meta.data??{})as Record<string,unknown>,filename=String(metadata.filename??metadata.name??item.filename??externalId),bytes=new Uint8Array(await contentResponse.arrayBuffer()),relativePath=relationshipPath(relationship.path,item.path,filename),directoryExternalId=relationship.directory_id??metadata.directory_id;await ingest(String(registered.id),knowledgeId,externalId,filename,relativePath,contentResponse.headers.get('content-type')??String(meta.content_type??'application/octet-stream'),bytes,directoryExternalId?String(directoryExternalId):undefined);accepted++;}return{library:registered,accepted,total:files.length};}
	async function train(context:any,knowledgeId:string){const authorization=context.req.header('authorization')??'',body=await context.req.json()as{mode?:string},mode=body.mode;if(!authorization)return context.json({error:{code:'unauthorized',message:'Open WebUI authorization is required.'}},401);if(!['smoke','standard'].includes(mode??''))return context.json({error:{code:'invalid_request',message:'mode must be smoke or standard.'}},400);const synchronized=await reconcile(knowledgeId,authorization),response=await requestFetch(`${controller}/v1/libraries/${encodeURIComponent(String((synchronized.library as any).id))}/train`,{method:'POST',headers:{authorization:`Bearer ${actionKey()}`,'content-type':'application/json','idempotency-key':context.req.header('idempotency-key')??crypto.randomUUID()},body:JSON.stringify({mode})}),value=await response.json();return context.json({synchronized,cycle:value},response.status as 202);}
	app.get('/healthz',context=>context.json({ok:true}));app.get('/treeai/v1/chats/:id/library',async context=>{const authorization=context.req.header('authorization')??'';if(!authorization)return context.json({error:{code:'unauthorized',message:'Open WebUI authorization is required.'}},401);try{return context.json(await preview(await chatLibrary(context.req.param('id'),authorization),authorization));}catch(error){return context.json({error:{code:'library_selection_invalid',message:error instanceof Error?error.message:String(error)}},409);}});app.post('/treeai/v1/chats/:id/train',async context=>{try{return await train(context,await chatLibrary(context.req.param('id'),context.req.header('authorization')??''));}catch(error){return context.json({error:{code:'library_train_failed',message:error instanceof Error?error.message:String(error)}},422);}});app.post('/treeai/v1/knowledge/:id/train',async context=>{try{return await train(context,context.req.param('id'));}catch(error){return context.json({error:{code:'library_train_failed',message:error instanceof Error?error.message:String(error)}},422);}});app.all('*',async context=>{const uploadCapture=context.req.raw.clone(),relationshipCapture=context.req.raw.clone(),headers=safeHeaders(context.req.raw.headers),init:RequestInit&{duplex:'half'}={method:context.req.method,headers,body:['GET','HEAD'].includes(context.req.method)?undefined:context.req.raw.body,duplex:'half',signal:context.req.raw.signal},response=await requestFetch(`${upstream}${context.req.path}${new URL(context.req.url).search}`,init);void Promise.all([observeUpload(uploadCapture,response.clone()),observeRelationship(relationshipCapture,response.clone())]).catch(report);return new Response(response.body,{status:response.status,headers:response.headers});});return app;
}
if(process.env.NODE_ENV!=='test')serve({fetch:createLibraryBridge().fetch,hostname:'0.0.0.0',port:Number(process.env.PORT??8082)});
