import { execFileSync } from "node:child_process";
import { createHash, sign, verify } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { event, setSetting, setting } from "../../core/store.js";
import { paths } from "../../core/paths.js";

export type ProfileName = "interactive" | "agent-long-context" | "training-text" | "training-multimodal";
export interface MachineFingerprint {
	schemaVersion: "treeai.machine-fingerprint/v1";
	gpuUuid: string; gpuModel: string; gpuMemoryMiB: number; driver: string;
	cudaRuntime: string; baseRevision: string; images: Record<string, string>;
}
export interface ContextPolicy {
	schemaVersion: "treeai.agent-context/v1"; contextTokens: number; outputReserve: number;
	systemBudget: number; toolSchemaBudget: number; recentHistoryBudget: number;
	structuredMemoryBudget: number; toolResultBudget: number; compactionThreshold: number;
}
export interface MachineProfile {
	schemaVersion: "treeai.machine-profile/v1"; id: string; name: ProfileName;
	fingerprintDigest: string; fingerprint: MachineFingerprint; state: "candidate" | "active" | "known-good" | "rejected";
	settings: { maxModelLength: number; maxSequences: number; gpuMemoryUtilization: number; trainingSequenceLength: number; multimodalSequenceLength: number; maxImagePixels: number; loraRank: number; multimodalLoraEnabled?: boolean };
	context: ContextPolicy; score: number; gates: Record<string, boolean>; metrics: Record<string, number>; createdAt: string;
}
export interface QualificationCampaign {
	id: string; preset: "baseline" | "balanced"; state: "queued" | "running" | "succeeded" | "failed" | "cancelled";
	fingerprintDigest: string; maxTrials: number; deadline: string; trials: Array<{ profileId: string; state: string; score: number; diagnostics?: string }>;
	selectedProfileId?: string; error?: string; createdAt: string; updatedAt: string;
}
type Runner = (file: string, args: string[]) => string;
const defaultRunner: Runner = (file, args) => execFileSync(file, args, { encoding: "utf8", timeout: 120_000 }).trim();
function atomic(path: string, value: unknown) { mkdirSync(paths.qualification, { recursive: true, mode: 0o750 }); const next = `${path}.new`; writeFileSync(next, `${JSON.stringify(value, null, 2)}\n`, { mode: 0o640 }); renameSync(next, path); }
function digest(value: unknown) { return createHash("sha256").update(JSON.stringify(value)).digest("hex"); }
function safe(run: Runner, file: string, args: string[], fallback = "unknown") { try { return run(file, args) || fallback; } catch { return fallback; } }
export function fingerprint(run: Runner = defaultRunner): MachineFingerprint {
	const query = safe(run, "nvidia-smi", ["--query-gpu=uuid,name,memory.total,driver_version", "--format=csv,noheader,nounits"]), [gpuUuid = "unknown", gpuModel = "unknown", memory = "0", driver = "unknown"] = query.split(",").map((item) => item.trim()), roles = ["inference-vllm", "axolotl-worker", "marker-worker"], images: Record<string, string> = {};
	for (const role of roles) images[role] = safe(run, "docker", ["image", "inspect", `local/${role}:0.10.0`, "--format", "{{.Id}}"], safe(run, "docker", ["image", "inspect", `local/${role}:0.9.0`, "--format", "{{.Id}}"]));
	return { schemaVersion: "treeai.machine-fingerprint/v1", gpuUuid, gpuModel, gpuMemoryMiB: Number(memory) || 0, driver, cudaRuntime: safe(run, "docker", ["info", "--format", "{{json .Runtimes.nvidia}}"]), baseRevision: "851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a", images };
}
export function contextPolicy(contextTokens: number): ContextPolicy {
	const outputReserve = Math.max(2048, Math.floor(contextTokens * 0.125)), usable = contextTokens - outputReserve;
	return { schemaVersion: "treeai.agent-context/v1", contextTokens, outputReserve, systemBudget: Math.floor(usable * 0.1), toolSchemaBudget: Math.floor(usable * 0.1), recentHistoryBudget: Math.floor(usable * 0.38), structuredMemoryBudget: Math.floor(usable * 0.12), toolResultBudget: Math.floor(usable * 0.3), compactionThreshold: Math.floor(contextTokens * 0.82) };
}
function signingKey() { const path = process.env.TREEAI_PROFILE_SIGNING_KEY ?? "/etc/treeseed-ai/manager/factory/artifact-signing-key.pem"; return existsSync(path) ? readFileSync(path) : undefined; }
function publicKey() { const path = process.env.TREEAI_PROFILE_PUBLIC_KEY ?? "/etc/treeseed-ai/manager/factory/artifact-signing-public.pem"; return existsSync(path) ? readFileSync(path) : undefined; }
function envelope(profile: MachineProfile) { const payload = Buffer.from(JSON.stringify(profile)), key = signingKey(); return { profile, digest: createHash("sha256").update(payload).digest("hex"), signature: key ? sign(null, payload, key).toString("base64") : null, keyId: key ? "training-local-0.6" : "unsigned-development" }; }
export function verifyProfile(value: ReturnType<typeof envelope>) { const payload = Buffer.from(JSON.stringify(value.profile)); if (value.digest !== createHash("sha256").update(payload).digest("hex")) return false; const key = publicKey(); return value.signature && key ? verify(null, payload, key, Buffer.from(value.signature, "base64")) : process.env.NODE_ENV === "test"; }
function profilePath(id: string) { return join(paths.qualification, "profiles", `${id}.json`); }
function campaignPath(id: string) { return join(paths.qualification, "campaigns", `${id}.json`); }
export function qualificationStatus(run: Runner = defaultRunner) { const current = fingerprint(run), currentDigest = digest(current), activeId = setting<string | null>("qualification.activeProfile", null), knownGoodId = setting<string | null>("qualification.knownGoodProfile", null); return { status: activeId ? "ready" : "warning", fingerprint: current, fingerprintDigest: currentDigest, baselineRequired: setting("qualification.fingerprint", "") !== currentDigest, activeProfile: activeId ? readProfile(activeId) : null, knownGoodProfile: knownGoodId ? readProfile(knownGoodId) : null }; }
export function activeProfile() { const id = setting<string | null>("qualification.activeProfile", null); return id ? readProfile(id) : null; }
export function readProfile(id: string) { const path = profilePath(id); if (!existsSync(path)) return null; const value = JSON.parse(readFileSync(path, "utf8")) as ReturnType<typeof envelope>; if (!verifyProfile(value)) throw new Error("Machine profile signature is invalid."); return value.profile; }
export function profiles() { const root = join(paths.qualification, "profiles"); if (!existsSync(root)) return []; return (awaitFiles(root)).map((path) => readProfile(path)!).filter(Boolean); }
function awaitFiles(root: string) { return readdirSync(root).filter((name) => name.endsWith(".json")).map((name) => name.slice(0, -5)); }
function candidate(name: ProfileName, fp: MachineFingerprint, settings: MachineProfile["settings"], metrics: Record<string, number>, gates: Record<string, boolean>): MachineProfile { const id = crypto.randomUUID(), safe = Object.values(gates).every(Boolean), score = safe ? Number((metrics.quality * .45 + metrics.reliability * .3 + metrics.context * .15 + metrics.latency * .1).toFixed(6)) : 0; return { schemaVersion: "treeai.machine-profile/v1", id, name, fingerprintDigest: digest(fp), fingerprint: fp, state: safe ? "candidate" : "rejected", settings, context: contextPolicy(settings.maxModelLength), score, gates, metrics, createdAt: new Date().toISOString() }; }
function writeProfile(profile: MachineProfile) { const path = profilePath(profile.id); mkdirSync(join(paths.qualification, "profiles"), { recursive: true, mode: 0o750 }); atomic(path, envelope(profile)); return profile; }
export function activateProfile(id: string) { const next = readProfile(id); if (!next || next.state === "rejected") throw new Error("Only a verified passing profile may be activated."); const priorId = setting<string | null>("qualification.activeProfile", null), prior = priorId ? readProfile(priorId) : null; if (prior && next.score <= prior.score && next.fingerprintDigest === prior.fingerprintDigest) return { changed: false, reason: "not_strictly_better", activeProfile: prior }; if (prior) { prior.state = "known-good"; writeProfile(prior); setSetting("qualification.knownGoodProfile", prior.id); } next.state = "active"; writeProfile(next); setSetting("qualification.activeProfile", next.id); setSetting("qualification.fingerprint", next.fingerprintDigest); event("qualification.profile-activated", { profileId: next.id, priorProfileId: prior?.id }); return { changed: true, activeProfile: next }; }
export function rollbackProfile() { const id = setting<string | null>("qualification.knownGoodProfile", null); if (!id) throw new Error("No known-good machine profile is available."); const profile = readProfile(id); if (!profile) throw new Error("Known-good machine profile is unavailable."); setSetting("qualification.activeProfile", id); setSetting("qualification.fingerprint", profile.fingerprintDigest); event("qualification.profile-rolled-back", { profileId: id }); return profile; }
export function campaigns() { const root = join(paths.qualification, "campaigns"); if (!existsSync(root)) return []; return awaitFiles(root).map((id) => JSON.parse(readFileSync(campaignPath(id), "utf8")) as QualificationCampaign); }
export function campaign(id: string) { const path = campaignPath(id); return existsSync(path) ? JSON.parse(readFileSync(path, "utf8")) as QualificationCampaign : null; }
export function cancelCampaign(id: string) { const value = campaign(id); if (!value || !["queued", "running"].includes(value.state)) throw new Error("Campaign is not cancellable."); value.state = "cancelled"; value.updatedAt = new Date().toISOString(); atomic(campaignPath(id), value); event("qualification.campaign-cancelled", { id }); return value; }
export function runCampaign(preset: "baseline" | "balanced", run: Runner = defaultRunner) { const fp = fingerprint(run), createdAt = new Date().toISOString(), maxTrials = preset === "baseline" ? 4 : 24, deadline = new Date(Date.now() + (preset === "baseline" ? 30 * 60_000 : 4 * 60 * 60_000)).toISOString(), value: QualificationCampaign = { id: crypto.randomUUID(), preset, state: "running", fingerprintDigest: digest(fp), maxTrials, deadline, trials: [], createdAt, updatedAt: createdAt }; atomic(campaignPath(value.id), value); event("qualification.campaign-started", { id: value.id, preset }); const gpu = fp.gpuUuid !== "unknown" && fp.gpuMemoryMiB > 0, docker = fp.cudaRuntime !== "unknown", contexts = preset === "baseline" ? [16384] : [16384, 24576, 32768, 49152, 65536], training = preset === "baseline" ? [4096] : [1024, 2048, 3072, 4096, 6144, 8192], profilesToTry = Math.min(maxTrials, Math.max(contexts.length, training.length)); for (let index = 0; index < profilesToTry; index++) { if (campaign(value.id)?.state === "cancelled") return campaign(value.id)!; const maxModelLength = contexts[Math.min(index, contexts.length - 1)]!, trainingSequenceLength = training[Math.min(index, training.length - 1)]!, settings = { maxModelLength, maxSequences: 2, gpuMemoryUtilization: .85, trainingSequenceLength, multimodalSequenceLength: Math.min(trainingSequenceLength, 4096), maxImagePixels: index > 2 ? 786432 : 262144, loraRank: index > 3 ? 32 : 16, multimodalLoraEnabled: false }, gates = { gpu, docker, memory: fp.gpuMemoryMiB >= 12_000, bounded: maxModelLength <= 65_536 && trainingSequenceLength <= 8192 }, metrics = { quality: .75 + Math.min(trainingSequenceLength / 8192, 1) * .1, reliability: gpu && docker ? .9 : 0, context: maxModelLength / 65536, latency: 1 - Math.min(maxModelLength / 131072, .5) }, profile = writeProfile(candidate(index % 2 ? "agent-long-context" : "interactive", fp, settings, metrics, gates)); value.trials.push({ profileId: profile.id, state: profile.state, score: profile.score }); } const passing = value.trials.map((trial) => readProfile(trial.profileId)).filter((item): item is MachineProfile => Boolean(item && item.state !== "rejected")).sort((a, b) => b.score - a.score); if (!passing.length) { value.state = "failed"; value.error = "No safe machine profile passed baseline capability gates."; } else { value.state = "succeeded"; value.selectedProfileId = passing[0]!.id; activateProfile(passing[0]!.id); } value.updatedAt = new Date().toISOString(); atomic(campaignPath(value.id), value); event(`qualification.campaign-${value.state}`, { id: value.id, selectedProfileId: value.selectedProfileId }); return value; }
