import { apiKeyAuthorization,jsonObjectSchema,openApiDocument,requireScope,type ApiKeyResolver,type JobRepository,type RouteSpec } from '@ai-platform/common';
import { Hono } from 'hono';
import { streamSSE } from 'hono/streaming';
import { existsSync,readFileSync } from 'node:fs';

const submitSchema={type:'object',required:['idempotencyKey'],properties:{idempotencyKey:{type:'string',minLength:1},input:jsonObjectSchema}};
function jobStateCounts(jobs:Array<{state:string}>){return jobs.reduce<Record<string,number>>((counts,job)=>{counts[job.state]=(counts[job.state]??0)+1;return counts;},{});}
function runtimeMetrics(){let mode='unknown',active=0;try{mode=JSON.parse(readFileSync(process.env.AI_FACTORY_MODE_FILE!,'utf8')).mode;}catch{}try{active=Number(JSON.parse(readFileSync(process.env.AI_FACTORY_STATUS_FILE!,'utf8')).activeGpuJobs??0);}catch{}return[`ai_factory_mode{product="training",mode="${mode}"} 1`,`ai_training_active_gpu_jobs ${active}`];}
export const trainingRoutes:RouteSpec[]=[
	{method:'GET',path:'/healthz',summary:'Liveness'},{method:'GET',path:'/readyz',summary:'Readiness'},{method:'GET',path:'/v1/version',summary:'Version',scope:'training:read'},
	{method:'GET',path:'/v1/jobs',summary:'List jobs',scope:'jobs:read'},{method:'GET',path:'/v1/jobs/:id',summary:'Get job',scope:'jobs:read'},{method:'GET',path:'/v1/jobs/:id/events',summary:'Job events',scope:'jobs:read'},{method:'POST',path:'/v1/jobs/:id/cancel',summary:'Cancel job',scope:'jobs:write'},
	{method:'GET',path:'/v1/jobs/:id/events/stream',summary:'Stream job events',scope:'jobs:read'},{method:'GET',path:'/v1/events/stream',summary:'Stream job changes',scope:'jobs:read'},{method:'GET',path:'/v1/metrics',summary:'Prometheus metrics',scope:'metrics:read'},
	{method:'POST',path:'/v1/documents',summary:'Process PDF',scope:'documents:write',requestSchema:submitSchema},{method:'POST',path:'/v1/datasets',summary:'Prepare dataset',scope:'datasets:write',requestSchema:submitSchema},{method:'POST',path:'/v1/training-runs',summary:'Start QLoRA SFT',scope:'training:write',requestSchema:submitSchema},
	{method:'POST',path:'/v1/experience-batches',summary:'Register immutable experience batch',scope:'datasets:write',requestSchema:submitSchema},{method:'GET',path:'/v1/experience-batches/:id',summary:'Get experience batch job',scope:'datasets:read'},{method:'POST',path:'/v1/experience-batches/:id/prepare',summary:'Prepare experience dataset',scope:'datasets:write',requestSchema:submitSchema},
	{method:'GET',path:'/v1/artifacts',summary:'List artifacts',scope:'artifacts:read'},{method:'POST',path:'/v1/artifacts/:id/verify',summary:'Verify artifact',scope:'artifacts:write',requestSchema:submitSchema},{method:'POST',path:'/v1/archives',summary:'Archive artifacts',scope:'archives:write',requestSchema:submitSchema},{method:'POST',path:'/v1/archives/:id/restore',summary:'Restore archive',scope:'archives:write',requestSchema:submitSchema},{method:'GET',path:'/v1/signing-keys',summary:'List public signing keys',scope:'artifacts:read'},
];

export function createTrainingControlApp(input:{jobs:JobRepository;resolveKey:ApiKeyResolver;version?:string;ready?:()=>Promise<boolean>}){
	const app=new Hono();const version=input.version??'0.7.0';const document=openApiDocument({title:'AI Training and Artifact Control API',version,routes:trainingRoutes});
	app.get('/healthz',(context)=>context.json({ok:true,service:'training-control'}));app.get('/readyz',async(context)=>{const ok=await(input.ready?.()??true);return context.json({ok},ok?200:503);});app.get('/openapi.json',(context)=>context.json(document));app.get('/docs',(context)=>context.html('<!doctype html><title>AI Training API</title><script id="api-reference" data-url="/openapi.json"></script><script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>'));
	app.use('/v1/*',apiKeyAuthorization(input.resolveKey));app.get('/v1/version',requireScope('training:read'),(context)=>context.json({version,api:'v1'}));
	app.get('/v1/jobs',requireScope('jobs:read'),async(context)=>context.json({items:await input.jobs.list(Number(context.req.query('limit')??100))}));app.get('/v1/jobs/:id',requireScope('jobs:read'),async(context)=>{const job=await input.jobs.get(context.req.param('id'));return job?context.json(job):context.json({error:{code:'not_found',message:'Job not found.'}},404);});app.get('/v1/jobs/:id/events',requireScope('jobs:read'),async(context)=>context.json({items:await input.jobs.events(context.req.param('id'))}));app.get('/v1/jobs/:id/events/stream',requireScope('jobs:read'),(context)=>streamSSE(context,async stream=>{let cursor=Number(context.req.header('last-event-id')??0);while(!stream.closed){const events=await input.jobs.events(context.req.param('id'));for(const event of events.filter(({id})=>id>cursor)){await stream.writeSSE({id:String(event.id),event:event.type,data:JSON.stringify(event)});cursor=event.id;}await stream.writeSSE({event:'heartbeat',data:'{}'});await stream.sleep(2000);}}));app.get('/v1/events/stream',requireScope('jobs:read'),(context)=>streamSSE(context,async stream=>{let cursor=context.req.header('last-event-id')??'',prior='';while(!stream.closed){const jobs=await input.jobs.list(100),value=JSON.stringify(jobs.map(({id,state,progress,updatedAt})=>({id,state,progress,updatedAt}))),id=String(Math.max(0,...jobs.map(({updatedAt})=>Date.parse(updatedAt))));if(value!==prior&&id!==cursor){await stream.writeSSE({id,event:'jobs',data:value});cursor=id;prior=value;}else await stream.writeSSE({event:'heartbeat',data:'{}'});await stream.sleep(2000);}}));app.get('/v1/metrics',requireScope('metrics:read'),async context=>{const jobs=await input.jobs.list(1000),counts=Object.entries(jobStateCounts(jobs)).map(([state,count])=>`ai_jobs{product="training",state="${state}"} ${count}`);return context.text(`${[...counts,...runtimeMetrics()].join('\n')}\n`,200,{'content-type':'text/plain; version=0.0.4'});});app.post('/v1/jobs/:id/cancel',requireScope('jobs:write'),async(context)=>{const job=await input.jobs.cancel(context.req.param('id'));return job?context.json(job):context.json({error:{code:'not_found',message:'Job not found.'}},404);});
	app.get('/v1/artifacts',requireScope('artifacts:read'),(context)=>context.json({items:[]}));app.get('/v1/signing-keys',requireScope('artifacts:read'),(context)=>{const path=process.env.SIGNING_PUBLIC_KEY_FILE;return context.json({items:path&&existsSync(path)?[{id:process.env.SIGNING_KEY_ID??'default',algorithm:'Ed25519',publicKey:readFileSync(path,'utf8')}]:[]});});
	app.get('/v1/experience-batches/:id',requireScope('datasets:read'),async(context)=>{const job=await input.jobs.get(context.req.param('id'));return job&&job.type.startsWith('experience.')?context.json(job):context.json({error:{code:'not_found',message:'Experience batch not found.'}},404);});
	const submit=(type:string,scope:string,extra:Record<string,string>={})=>[requireScope(scope),async(context:any)=>{const body=await context.req.json();if(!body.idempotencyKey)return context.json({error:{code:'invalid_request',message:'idempotencyKey is required.'}},400);const request={...(body.input??{}),...Object.fromEntries(Object.entries(extra).map(([key,param])=>[key,context.req.param(param)]))};const job=await input.jobs.submit({type,request,idempotencyKey:body.idempotencyKey,priority:body.priority});return context.json(job,202);} ] as const;
	app.post('/v1/documents',...submit('document.process','documents:write'));app.post('/v1/datasets',...submit('dataset.prepare','datasets:write'));app.post('/v1/training-runs',...submit('training.qlora','training:write'));app.post('/v1/experience-batches',...submit('experience.register','datasets:write'));app.post('/v1/experience-batches/:id/prepare',...submit('experience.prepare','datasets:write',{batchJobId:'id'}));app.post('/v1/artifacts/:id/verify',...submit('artifact.verify','artifacts:write',{artifactId:'id'}));app.post('/v1/archives',...submit('archive.create','archives:write'));app.post('/v1/archives/:id/restore',...submit('archive.restore','archives:write',{archiveId:'id'}));
	app.notFound((context)=>context.json({error:{code:'not_found',message:'Route not found.'}},404));app.onError((error,context)=>context.json({error:{code:'internal_error',message:error.message}},500));return app;
}
