import { apiKeyAuthorization,jsonObjectSchema,openApiDocument,requireScope,type ApiKeyResolver,type JobRepository,type RouteSpec } from '@ai-platform/common';
import { Hono } from 'hono';
import { streamSSE } from 'hono/streaming';
import { existsSync,readFileSync } from 'node:fs';
import { rm } from 'node:fs/promises';
import { metadata,spool } from './intake.js';
import type { LibraryRepository } from './libraries.js';
type LibraryApi=Pick<LibraryRepository,'list'|'get'|'upsert'|'documents'|'ingest'|'deleteDocument'|'deleteExternalDocument'|'relationships'|'snapshots'|'freezeSnapshot'|'runs'|'createRun'|'updateRunJob'>;

const submitSchema={type:'object',required:['idempotencyKey'],properties:{idempotencyKey:{type:'string',minLength:1},input:jsonObjectSchema}};
function jobStateCounts(jobs:Array<{state:string}>){return jobs.reduce<Record<string,number>>((counts,job)=>{counts[job.state]=(counts[job.state]??0)+1;return counts;},{});}
function runtimeMetrics(){let mode='unknown',active=0;try{mode=JSON.parse(readFileSync(process.env.AI_FACTORY_MODE_FILE!,'utf8')).mode;}catch{}try{active=Number(JSON.parse(readFileSync(process.env.AI_FACTORY_STATUS_FILE!,'utf8')).activeGpuJobs??0);}catch{}return[`ai_factory_mode{product="training",mode="${mode}"} 1`,`ai_training_active_gpu_jobs ${active}`];}
export const trainingRoutes:RouteSpec[]=[
	{method:'GET',path:'/healthz',summary:'Liveness'},{method:'GET',path:'/readyz',summary:'Readiness'},{method:'GET',path:'/v1/version',summary:'Version',scope:'training:read'},
	{method:'GET',path:'/v1/jobs',summary:'List jobs',scope:'jobs:read'},{method:'GET',path:'/v1/jobs/:id',summary:'Get job',scope:'jobs:read'},{method:'GET',path:'/v1/jobs/:id/events',summary:'Job events',scope:'jobs:read'},{method:'POST',path:'/v1/jobs/:id/cancel',summary:'Cancel job',scope:'jobs:write'},
	{method:'GET',path:'/v1/jobs/:id/events/stream',summary:'Stream job events',scope:'jobs:read'},{method:'GET',path:'/v1/events/stream',summary:'Stream job changes',scope:'jobs:read'},{method:'GET',path:'/v1/metrics',summary:'Prometheus metrics',scope:'metrics:read'},
	{method:'POST',path:'/v1/documents',summary:'Process PDF',scope:'documents:write',requestSchema:submitSchema},{method:'POST',path:'/v1/datasets',summary:'Prepare dataset',scope:'datasets:write',requestSchema:submitSchema},{method:'POST',path:'/v1/training-runs',summary:'Start QLoRA SFT',scope:'training:write',requestSchema:submitSchema},
	{method:'GET',path:'/v1/libraries',summary:'List training libraries',scope:'libraries:read'},{method:'POST',path:'/v1/libraries',summary:'Create or synchronize a training library',scope:'libraries:write',requestSchema:jsonObjectSchema},{method:'GET',path:'/v1/libraries/:id',summary:'Get a training library',scope:'libraries:read'},
	{method:'GET',path:'/v1/libraries/:id/documents',summary:'List library documents',scope:'libraries:read'},{method:'POST',path:'/v1/libraries/:id/documents',summary:'Upload an immutable library document',scope:'libraries:write',requestContentType:'application/octet-stream',requestSchema:{type:'string',format:'binary'}},{method:'DELETE',path:'/v1/libraries/:id/documents/:documentId',summary:'Exclude a document from future snapshots',scope:'libraries:write'},
	{method:'DELETE',path:'/v1/libraries/:id/documents/external/:externalId',summary:'Exclude an externally identified document',scope:'libraries:write'},
	{method:'POST',path:'/v1/libraries/:id/relationships',summary:'Synchronize library directories',scope:'libraries:write',requestSchema:jsonObjectSchema},
	{method:'GET',path:'/v1/libraries/:id/snapshots',summary:'List immutable library snapshots',scope:'libraries:read'},{method:'POST',path:'/v1/libraries/:id/snapshots',summary:'Freeze a library snapshot',scope:'libraries:train',requestSchema:jsonObjectSchema},
	{method:'POST',path:'/v1/libraries/:id/snapshots/:snapshotId/prepare',summary:'Prepare an immutable completion dataset',scope:'libraries:train',requestSchema:jsonObjectSchema},
	{method:'GET',path:'/v1/library-runs',summary:'List library training runs',scope:'libraries:read'},{method:'POST',path:'/v1/library-runs',summary:'Start fixed continual-pretraining QLoRA',scope:'libraries:train',requestSchema:jsonObjectSchema},{method:'GET',path:'/v1/library-runs/:id',summary:'Get library training run',scope:'libraries:read'},
	{method:'POST',path:'/v1/library-training-profile/qualify',summary:'Qualify the largest safe training sequence',scope:'libraries:train',requestSchema:jsonObjectSchema},
	{method:'POST',path:'/v1/experience-batches',summary:'Register immutable experience batch',scope:'datasets:write',requestSchema:submitSchema},{method:'GET',path:'/v1/experience-batches/:id',summary:'Get experience batch job',scope:'datasets:read'},{method:'POST',path:'/v1/experience-batches/:id/prepare',summary:'Prepare experience dataset',scope:'datasets:write',requestSchema:submitSchema},
	{method:'GET',path:'/v1/artifacts',summary:'List artifacts',scope:'artifacts:read'},{method:'POST',path:'/v1/artifacts/:id/verify',summary:'Verify artifact',scope:'artifacts:write',requestSchema:submitSchema},{method:'POST',path:'/v1/archives',summary:'Archive artifacts',scope:'archives:write',requestSchema:submitSchema},{method:'POST',path:'/v1/archives/:id/restore',summary:'Restore archive',scope:'archives:write',requestSchema:submitSchema},{method:'GET',path:'/v1/signing-keys',summary:'List public signing keys',scope:'artifacts:read'},
];

export function createTrainingControlApp(input:{jobs:JobRepository;resolveKey:ApiKeyResolver;version?:string;ready?:()=>Promise<boolean>;libraries?:LibraryApi}){
	const app=new Hono();const version=input.version??'0.8.0';const document=openApiDocument({title:'AI Training and Artifact Control API',version,routes:trainingRoutes});
	app.get('/healthz',(context)=>context.json({ok:true,service:'training-control'}));app.get('/readyz',async(context)=>{const ok=await(input.ready?.()??true);return context.json({ok},ok?200:503);});app.get('/openapi.json',(context)=>context.json(document));app.get('/docs',(context)=>context.html('<!doctype html><title>AI Training API</title><script id="api-reference" data-url="/openapi.json"></script><script src="https://cdn.jsdelivr.net/npm/@scalar/api-reference"></script>'));
	app.use('/v1/*',apiKeyAuthorization(input.resolveKey));app.get('/v1/version',requireScope('training:read'),(context)=>context.json({version,api:'v1'}));
	app.get('/v1/jobs',requireScope('jobs:read'),async(context)=>context.json({items:await input.jobs.list(Number(context.req.query('limit')??100))}));app.get('/v1/jobs/:id',requireScope('jobs:read'),async(context)=>{const job=await input.jobs.get(context.req.param('id'));return job?context.json(job):context.json({error:{code:'not_found',message:'Job not found.'}},404);});app.get('/v1/jobs/:id/events',requireScope('jobs:read'),async(context)=>context.json({items:await input.jobs.events(context.req.param('id'))}));app.get('/v1/jobs/:id/events/stream',requireScope('jobs:read'),(context)=>streamSSE(context,async stream=>{let cursor=Number(context.req.header('last-event-id')??0);while(!stream.closed){const events=await input.jobs.events(context.req.param('id'));for(const event of events.filter(({id})=>id>cursor)){await stream.writeSSE({id:String(event.id),event:event.type,data:JSON.stringify(event)});cursor=event.id;}await stream.writeSSE({event:'heartbeat',data:'{}'});await stream.sleep(2000);}}));app.get('/v1/events/stream',requireScope('jobs:read'),(context)=>streamSSE(context,async stream=>{let cursor=context.req.header('last-event-id')??'',prior='';while(!stream.closed){const jobs=await input.jobs.list(100),value=JSON.stringify(jobs.map(({id,state,progress,updatedAt})=>({id,state,progress,updatedAt}))),id=String(Math.max(0,...jobs.map(({updatedAt})=>Date.parse(updatedAt))));if(value!==prior&&id!==cursor){await stream.writeSSE({id,event:'jobs',data:value});cursor=id;prior=value;}else await stream.writeSSE({event:'heartbeat',data:'{}'});await stream.sleep(2000);}}));app.get('/v1/metrics',requireScope('metrics:read'),async context=>{const jobs=await input.jobs.list(1000),counts=Object.entries(jobStateCounts(jobs)).map(([state,count])=>`ai_jobs{product="training",state="${state}"} ${count}`);return context.text(`${[...counts,...runtimeMetrics()].join('\n')}\n`,200,{'content-type':'text/plain; version=0.0.4'});});app.post('/v1/jobs/:id/cancel',requireScope('jobs:write'),async(context)=>{const job=await input.jobs.cancel(context.req.param('id'));return job?context.json(job):context.json({error:{code:'not_found',message:'Job not found.'}},404);});
	app.get('/v1/artifacts',requireScope('artifacts:read'),(context)=>context.json({items:[]}));app.get('/v1/signing-keys',requireScope('artifacts:read'),(context)=>{const path=process.env.SIGNING_PUBLIC_KEY_FILE;return context.json({items:path&&existsSync(path)?[{id:process.env.SIGNING_KEY_ID??'default',algorithm:'Ed25519',publicKey:readFileSync(path,'utf8')}]:[]});});
	app.get('/v1/experience-batches/:id',requireScope('datasets:read'),async(context)=>{const job=await input.jobs.get(context.req.param('id'));return job&&job.type.startsWith('experience.')?context.json(job):context.json({error:{code:'not_found',message:'Experience batch not found.'}},404);});
	app.get('/v1/libraries',requireScope('libraries:read'),async(context)=>context.json({items:await input.libraries?.list()??[]}));
	app.post('/v1/libraries',requireScope('libraries:write'),async context=>{if(!input.libraries)return context.json({error:{code:'unavailable',message:'Library storage is unavailable.'}},503);const key=context.req.header('idempotency-key');if(!key)return context.json({error:{code:'invalid_request',message:'Idempotency-Key is required.'}},400);try{return context.json(await input.libraries.upsert(await context.req.json()),201);}catch(error){return context.json({error:{code:'invalid_request',message:error instanceof Error?error.message:String(error)}},400);}});
	app.get('/v1/libraries/:id',requireScope('libraries:read'),async context=>{const library=await input.libraries?.get(context.req.param('id'));return library?context.json(library):context.json({error:{code:'not_found',message:'Library not found.'}},404);});
	app.get('/v1/libraries/:id/documents',requireScope('libraries:read'),async context=>context.json({items:await input.libraries?.documents(context.req.param('id'))??[]}));
	app.post('/v1/libraries/:id/documents',requireScope('libraries:write'),async context=>{if(!input.libraries)return context.json({error:{code:'unavailable',message:'Library storage is unavailable.'}},503);const idempotencyKey=context.req.header('idempotency-key');if(!idempotencyKey)return context.json({error:{code:'invalid_request',message:'Idempotency-Key is required.'}},400);let temporary:Awaited<ReturnType<typeof spool>>|undefined;try{const details=metadata(context.req.header('x-treeai-document'));temporary=await spool(context.req.raw.body,context.req.header('x-content-sha256'));const document=await input.libraries.ingest(context.req.param('id'),{...details,declaredMimeType:details.declaredMimeType??context.req.header('content-type')??'application/octet-stream',detectedMimeType:'application/octet-stream',sha256:temporary.sha256,size:temporary.size},temporary.path),revision=document?.currentRevision;const job=await input.jobs.submit({type:'library.document.classify',request:{libraryId:context.req.param('id'),documentId:document?.id,revisionId:revision?.id,objectUri:revision?.objectUri,sha256:revision?.sha256,filename:revision?.filename,relativePath:revision?.relativePath,directoryExternalId:revision?.directoryExternalId,declaredMimeType:revision?.declaredMimeType},idempotencyKey:`library-document:${idempotencyKey}`});return context.json({document,job},202);}catch(error){return context.json({error:{code:'invalid_document',message:error instanceof Error?error.message:String(error)}},422);}finally{if(temporary)await rm(temporary.directory,{recursive:true,force:true});}});
	app.delete('/v1/libraries/:id/documents/:documentId',requireScope('libraries:write'),async context=>{if(!context.req.header('idempotency-key'))return context.json({error:{code:'invalid_request',message:'Idempotency-Key is required.'}},400);const removed=await input.libraries?.deleteDocument(context.req.param('id'),context.req.param('documentId'));return removed?context.json({deleted:true}):context.json({error:{code:'not_found',message:'Document not found.'}},404);});
	app.delete('/v1/libraries/:id/documents/external/:externalId',requireScope('libraries:write'),async context=>{if(!context.req.header('idempotency-key'))return context.json({error:{code:'invalid_request',message:'Idempotency-Key is required.'}},400);const removed=await input.libraries?.deleteExternalDocument(context.req.param('id'),context.req.param('externalId'));return removed?context.json({deleted:true}):context.json({error:{code:'not_found',message:'Document not found.'}},404);});
	app.post('/v1/libraries/:id/relationships',requireScope('libraries:write'),async context=>{if(!context.req.header('idempotency-key'))return context.json({error:{code:'invalid_request',message:'Idempotency-Key is required.'}},400);try{return context.json(await input.libraries?.relationships(context.req.param('id'),await context.req.json())??{updated:0});}catch(error){return context.json({error:{code:'invalid_relationship',message:error instanceof Error?error.message:String(error)}},422);}});
	app.get('/v1/libraries/:id/snapshots',requireScope('libraries:read'),async context=>context.json({items:await input.libraries?.snapshots(context.req.param('id'))??[]}));
	app.post('/v1/libraries/:id/snapshots',requireScope('libraries:train'),async context=>{if(!context.req.header('idempotency-key'))return context.json({error:{code:'invalid_request',message:'Idempotency-Key is required.'}},400);try{return context.json(await input.libraries?.freezeSnapshot(context.req.param('id'),String((await context.req.json()).mode)as'smoke'|'standard'),201);}catch(error){return context.json({error:{code:'snapshot_rejected',message:error instanceof Error?error.message:String(error)}},422);}});
	app.post('/v1/libraries/:id/snapshots/:snapshotId/prepare',requireScope('libraries:train'),async context=>{const key=context.req.header('idempotency-key');if(!key)return context.json({error:{code:'invalid_request',message:'Idempotency-Key is required.'}},400);const body=await context.req.json().catch(()=>({}))as Record<string,unknown>,job=await input.jobs.submit({type:'library.dataset.prepare',idempotencyKey:`library-dataset:${key}`,request:{snapshotId:context.req.param('snapshotId'),baseModel:process.env.SOURCE_MODEL??'Qwen/Qwen3.5-4B',baseModelRevision:process.env.SOURCE_MODEL_REVISION??'851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a',sequenceLength:Number(body.sequenceLength??2048)}});return context.json(job,202);});
	app.get('/v1/library-runs',requireScope('libraries:read'),async context=>context.json({items:await input.libraries?.runs()??[]}));
	app.get('/v1/library-runs/:id',requireScope('libraries:read'),async context=>{const run=(await input.libraries?.runs(context.req.param('id'))??[])[0];return run?context.json(run):context.json({error:{code:'not_found',message:'Library run not found.'}},404);});
	app.post('/v1/library-runs',requireScope('libraries:train'),async context=>{if(!input.libraries)return context.json({error:{code:'unavailable',message:'Library storage is unavailable.'}},503);const key=context.req.header('idempotency-key');if(!key)return context.json({error:{code:'invalid_request',message:'Idempotency-Key is required.'}},400);try{const body=await context.req.json(),run=await input.libraries.createRun(String(body.libraryId),{snapshotId:String(body.snapshotId),idempotencyKey:key}),job=await input.jobs.submit({type:'library.training.qlora',idempotencyKey:`library-run:${run.id}`,request:{runId:run.id,libraryId:run.libraryId,librarySlug:run.librarySlug,snapshotId:run.snapshotId,mode:run.mode,baseModel:process.env.SOURCE_MODEL??'Qwen/Qwen3.5-4B',baseModelRevision:process.env.SOURCE_MODEL_REVISION??'851bf6e806efd8d0a36b00ddf55e13ccb7b8cd0a',sequenceLength:Number(body.sequenceLength??2048),datasetManifest:run.datasetManifestUri,trainUri:run.trainUri}});return context.json(await input.libraries.updateRunJob(run.id,job.id),202);}catch(error){return context.json({error:{code:'library_run_rejected',message:error instanceof Error?error.message:String(error)}},422);}});
	app.post('/v1/library-training-profile/qualify',requireScope('libraries:train'),async context=>{const key=context.req.header('idempotency-key');if(!key)return context.json({error:{code:'invalid_request',message:'Idempotency-Key is required.'}},400);const body=await context.req.json()as{trainUri?:string};if(!body.trainUri)return context.json({error:{code:'invalid_request',message:'trainUri is required.'}},400);return context.json(await input.jobs.submit({type:'library.training.qualify',idempotencyKey:`library-qualify:${key}`,request:{trainUri:body.trainUri}}),202);});
	const submit=(type:string,scope:string,extra:Record<string,string>={})=>[requireScope(scope),async(context:any)=>{const body=await context.req.json();if(!body.idempotencyKey)return context.json({error:{code:'invalid_request',message:'idempotencyKey is required.'}},400);const request={...(body.input??{}),...Object.fromEntries(Object.entries(extra).map(([key,param])=>[key,context.req.param(param)]))};const job=await input.jobs.submit({type,request,idempotencyKey:body.idempotencyKey,priority:body.priority});return context.json(job,202);} ] as const;
	app.post('/v1/documents',...submit('document.process','documents:write'));app.post('/v1/datasets',...submit('dataset.prepare','datasets:write'));app.post('/v1/training-runs',...submit('training.qlora','training:write'));app.post('/v1/experience-batches',...submit('experience.register','datasets:write'));app.post('/v1/experience-batches/:id/prepare',...submit('experience.prepare','datasets:write',{batchJobId:'id'}));app.post('/v1/artifacts/:id/verify',...submit('artifact.verify','artifacts:write',{artifactId:'id'}));app.post('/v1/archives',...submit('archive.create','archives:write'));app.post('/v1/archives/:id/restore',...submit('archive.restore','archives:write',{archiveId:'id'}));
	app.notFound((context)=>context.json({error:{code:'not_found',message:'Route not found.'}},404));app.onError((error,context)=>context.json({error:{code:'internal_error',message:error.message}},500));return app;
}
