import { readFile,stat } from 'node:fs/promises';
import type { Pool,PoolClient } from 'pg';
import type{ObjectWriter}from'./minio-storage.js';

export const documentStates=['received','classified','pending_processing','processing','ready','quarantined','deleted'] as const;
export interface LibraryInput {sourceKind:'open-webui'|'api';externalId:string;slug:string;name:string;description?:string}
export interface DocumentInput {externalId:string;filename:string;relativePath:string;directoryExternalId?:string;declaredMimeType:string;detectedMimeType:string;sha256:string;size:number;provenance?:Record<string,unknown>}
export interface RelationshipInput {directories?:Array<{externalId:string;parentExternalId?:string;name:string;relativePath:string;deleted?:boolean}>;documents?:Array<{externalId:string;filename?:string;relativePath?:string;directoryExternalId?:string}>}

const maximumDocumentBytes=100*1024*1024;
export async function boundedDocumentBytes(path:string,expectedSize:number){
	const details=await stat(path);if(details.size!==expectedSize)throw new Error('Document size changed before object storage');
	if(details.size<0||details.size>maximumDocumentBytes)throw new Error('Document exceeds the 100 MiB limit');
	const bytes=await readFile(path);if(bytes.byteLength!==expectedSize)throw new Error('Document size changed while reading');return bytes;
}

export function sameDocumentRevision(current:Record<string,unknown>,input:DocumentInput){
	return current.object_sha256===input.sha256&&current.declared_mime_type===input.declaredMimeType;
}

export function sameRelationshipRevision(current:Record<string,unknown>,input:{filename?:string;relativePath?:string;directoryExternalId?:string}){
	return (input.filename??current.filename)===current.filename&&(input.relativePath??current.relative_path)===current.relative_path&&(input.directoryExternalId??current.directory_external_id??null)===(current.directory_external_id??null);
}

function row(value:Record<string,unknown>){return{id:String(value.id),sourceKind:value.source_kind,externalId:value.external_id,slug:value.slug,name:value.name,description:value.description,deleted:value.deleted,createdAt:new Date(value.created_at as string).toISOString(),updatedAt:new Date(value.updated_at as string).toISOString()};}
function documentRow(value:Record<string,unknown>){return{id:String(value.id),libraryId:String(value.library_id),externalId:value.external_id,state:value.state,deletedAt:value.deleted_at?new Date(value.deleted_at as string).toISOString():null,currentRevision:value.current_revision_id?{id:String(value.current_revision_id),sha256:value.object_sha256,objectUri:value.object_uri,filename:value.filename,relativePath:value.relative_path,directoryExternalId:value.directory_external_id,declaredMimeType:value.declared_mime_type,detectedMimeType:value.detected_mime_type,revision:Number(value.revision),provenance:value.provenance,diagnostics:value.diagnostics,normalizedManifestUri:value.normalized_manifest_uri,tokenCount:value.token_count===null?null:Number(value.token_count)}:null,createdAt:new Date(value.created_at as string).toISOString(),updatedAt:new Date(value.updated_at as string).toISOString()};}

export class LibraryRepository {
	constructor(readonly pool:Pool,readonly objects:ObjectWriter){}
	async list(){const result=await this.pool.query('SELECT * FROM libraries WHERE deleted=false ORDER BY name,id');return result.rows.map(row);}
	async get(id:string){const result=await this.pool.query('SELECT * FROM libraries WHERE id=$1 AND deleted=false',[id]);return result.rowCount?row(result.rows[0]):null;}
	async upsert(input:LibraryInput){
		if(!/^[a-z0-9][a-z0-9-]{0,62}$/u.test(input.slug))throw new Error('slug must contain lowercase letters, numbers, and hyphens');
		if(!input.externalId||!input.name||input.externalId.length>200||input.name.length>200)throw new Error('externalId and name are required');
		const result=await this.pool.query(`INSERT INTO libraries(source_kind,external_id,slug,name,description) VALUES($1,$2,$3,$4,$5) ON CONFLICT(source_kind,external_id) DO UPDATE SET slug=excluded.slug,name=excluded.name,description=excluded.description,deleted=false,updated_at=now() RETURNING *`,[input.sourceKind,input.externalId,input.slug,input.name,input.description??'']);return row(result.rows[0]);
	}
	async documents(libraryId:string){const result=await this.pool.query(`SELECT d.*,r.object_sha256,o.object_uri,r.filename,r.relative_path,r.directory_external_id,r.declared_mime_type,r.detected_mime_type,r.revision,r.provenance,r.diagnostics,r.normalized_manifest_uri,r.token_count FROM library_documents d LEFT JOIN document_revisions r ON r.id=d.current_revision_id LEFT JOIN document_objects o ON o.sha256=r.object_sha256 WHERE d.library_id=$1 ORDER BY r.relative_path,d.id`,[libraryId]);return result.rows.map(documentRow);}
	async ingest(libraryId:string,input:DocumentInput,temporaryPath:string){
		if(!/^[a-f0-9]{64}$/u.test(input.sha256))throw new Error('A valid SHA-256 digest is required');
		const bytes=await boundedDocumentBytes(temporaryPath,input.size),stored=await this.objects.put(`library-source/${input.sha256}`,bytes,input.detectedMimeType);
		if(stored.sha256!==input.sha256)throw new Error('Document SHA-256 changed before object storage');
		const client=await this.pool.connect();try{return await this.ingestTransaction(client,libraryId,input,stored.uri);}finally{client.release();}
	}
	private async ingestTransaction(client:PoolClient,libraryId:string,input:DocumentInput,uri:string){
		await client.query('BEGIN');try{
			const library=await client.query('SELECT id FROM libraries WHERE id=$1 AND deleted=false FOR UPDATE',[libraryId]);if(!library.rowCount)throw new Error('Library not found');
			await client.query(`INSERT INTO document_objects(sha256,object_uri,size,detected_mime_type) VALUES($1,$2,$3,$4) ON CONFLICT(sha256) DO NOTHING`,[input.sha256,uri,input.size,input.detectedMimeType]);
			const document=await client.query(`INSERT INTO library_documents(library_id,external_id) VALUES($1,$2) ON CONFLICT(library_id,external_id) DO UPDATE SET deleted_at=null,updated_at=now() RETURNING id`,[libraryId,input.externalId]);
			const current=await client.query(`SELECT r.object_sha256,r.filename,r.relative_path,r.directory_external_id,r.declared_mime_type,r.state FROM library_documents d JOIN document_revisions r ON r.id=d.current_revision_id WHERE d.id=$1`,[document.rows[0].id]);
			if(current.rowCount&&sameDocumentRevision(current.rows[0],input)){await client.query('UPDATE library_documents SET state=$1,deleted_at=null,updated_at=now() WHERE id=$2',[current.rows[0].state,document.rows[0].id]);await client.query('COMMIT');return(await this.documents(libraryId)).find((value)=>value.id===String(document.rows[0].id));}
			const revision=await client.query('SELECT COALESCE(MAX(revision),0)+1 next FROM document_revisions WHERE document_id=$1',[document.rows[0].id]);
			const inserted=await client.query(`INSERT INTO document_revisions(document_id,object_sha256,revision,filename,relative_path,directory_external_id,declared_mime_type,detected_mime_type,provenance) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING id`,[document.rows[0].id,input.sha256,revision.rows[0].next,input.filename,input.relativePath,input.directoryExternalId??null,input.declaredMimeType,input.detectedMimeType,input.provenance??{}]);
			await client.query(`UPDATE library_documents SET current_revision_id=$1,state='received',updated_at=now() WHERE id=$2`,[inserted.rows[0].id,document.rows[0].id]);await client.query('COMMIT');
			return(await this.documents(libraryId)).find((value)=>value.id===String(document.rows[0].id));
		}catch(error){await client.query('ROLLBACK');throw error;}
	}
	async deleteDocument(libraryId:string,documentId:string){const result=await this.pool.query(`UPDATE library_documents SET state='deleted',deleted_at=now(),updated_at=now() WHERE id=$1 AND library_id=$2 AND state<>'deleted' RETURNING id`,[documentId,libraryId]);return Boolean(result.rowCount);}
	async deleteExternalDocument(libraryId:string,externalId:string){const result=await this.pool.query(`UPDATE library_documents SET state='deleted',deleted_at=now(),updated_at=now() WHERE external_id=$1 AND library_id=$2 AND state<>'deleted' RETURNING id`,[externalId,libraryId]);return Boolean(result.rowCount);}
	async relationships(libraryId:string,input:RelationshipInput){
		const directories=input.directories??[],documents=input.documents??[],client=await this.pool.connect();let updated=directories.length;try{await client.query('BEGIN');for(const directory of directories){if(!directory.externalId||!directory.name)throw new Error('Directory identity and name are required');await client.query(`INSERT INTO library_directories(library_id,external_id,parent_external_id,name,relative_path,deleted) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(library_id,external_id) DO UPDATE SET parent_external_id=excluded.parent_external_id,name=excluded.name,relative_path=excluded.relative_path,deleted=excluded.deleted,revision=library_directories.revision+1,updated_at=now()`,[libraryId,directory.externalId,directory.parentExternalId??null,directory.name,directory.relativePath,directory.deleted??false]);}for(const relation of documents){const current=await client.query(`SELECT d.id,r.* FROM library_documents d JOIN document_revisions r ON r.id=d.current_revision_id WHERE d.library_id=$1 AND d.external_id=$2 FOR UPDATE`,[libraryId,relation.externalId]);if(!current.rowCount)continue;const value=current.rows[0];if(sameRelationshipRevision(value,relation))continue;const revision=Number(value.revision)+1,inserted=await client.query(`INSERT INTO document_revisions(document_id,object_sha256,revision,filename,relative_path,directory_external_id,declared_mime_type,detected_mime_type,state,provenance,diagnostics,normalized_manifest_uri,token_count) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id`,[value.id,value.object_sha256,revision,relation.filename??value.filename,relation.relativePath??value.relative_path,relation.directoryExternalId??value.directory_external_id,value.declared_mime_type,value.detected_mime_type,value.state,value.provenance,value.diagnostics,value.normalized_manifest_uri,value.token_count]);await client.query('UPDATE library_documents SET current_revision_id=$1,updated_at=now() WHERE id=$2',[inserted.rows[0].id,value.id]);updated++;}await client.query('COMMIT');return{updated};}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
	}
	async snapshots(libraryId:string){const result=await this.pool.query('SELECT s.*,d.train_uri,d.evaluation_uri,d.multimodal_train_uri,d.multimodal_evaluation_uri,d.multimodal_example_count FROM library_snapshots s LEFT JOIN library_datasets d ON d.snapshot_id=s.id WHERE s.library_id=$1 ORDER BY s.created_at DESC',[libraryId]);return result.rows.map((value)=>({id:String(value.id),libraryId:String(value.library_id),mode:value.mode,state:value.state,manifestUri:value.manifest_uri,trainUri:value.train_uri,evaluationUri:value.evaluation_uri,multimodalTrainUri:value.multimodal_train_uri,multimodalEvaluationUri:value.multimodal_evaluation_uri,multimodalExampleCount:Number(value.multimodal_example_count??0),documentCount:Number(value.document_count),tokenCount:Number(value.token_count),createdAt:new Date(value.created_at).toISOString(),updatedAt:new Date(value.updated_at).toISOString()}));}
	async freezeSnapshot(libraryId:string,mode:'smoke'|'standard'){
		if(!['smoke','standard'].includes(mode))throw new Error('Snapshot mode must be smoke or standard');const client=await this.pool.connect();try{await client.query('BEGIN');const docs=await client.query(`SELECT d.current_revision_id revision_id,d.state,r.relative_path,r.directory_external_id FROM library_documents d JOIN document_revisions r ON r.id=d.current_revision_id WHERE d.library_id=$1 AND d.state<>'deleted' ORDER BY r.object_sha256,r.relative_path FOR SHARE`,[libraryId]);if(!docs.rowCount)throw new Error('Library has no documents');if(docs.rows.some((item)=>item.state==='quarantined'))throw new Error('Quarantined documents must be removed or replaced');const snapshot=await client.query(`INSERT INTO library_snapshots(library_id,mode,document_count) VALUES($1,$2,$3) RETURNING id`,[libraryId,mode,docs.rowCount]);for(const doc of docs.rows)await client.query(`INSERT INTO library_snapshot_documents(snapshot_id,document_revision_id,relationship) VALUES($1,$2,$3)`,[snapshot.rows[0].id,doc.revision_id,{relativePath:doc.relative_path,directoryExternalId:doc.directory_external_id}]);await client.query('COMMIT');return(await this.snapshots(libraryId)).find((item)=>item.id===String(snapshot.rows[0].id));}catch(error){await client.query('ROLLBACK');throw error;}finally{client.release();}
	}
	async runs(id?:string){const result=await this.pool.query(`SELECT r.*,l.slug library_slug,l.name library_name,d.manifest_uri dataset_manifest_uri,d.train_uri,d.multimodal_train_uri FROM library_runs r JOIN libraries l ON l.id=r.library_id LEFT JOIN library_datasets d ON d.id=r.dataset_id ${id?'WHERE r.id=$1':''} ORDER BY r.created_at DESC`,id?[id]:[]);return result.rows.map((value)=>({id:String(value.id),libraryId:String(value.library_id),librarySlug:value.library_slug,libraryName:value.library_name,snapshotId:String(value.snapshot_id),datasetId:value.dataset_id?String(value.dataset_id):null,datasetManifestUri:value.dataset_manifest_uri,trainUri:value.train_uri,multimodalTrainUri:value.multimodal_train_uri,mode:value.mode,state:value.state,phaseJobId:value.phase_job_id?String(value.phase_job_id):null,visionPhaseJobId:value.vision_phase_job_id?String(value.vision_phase_job_id):null,compositionPhaseJobId:value.composition_phase_job_id?String(value.composition_phase_job_id):null,adapterManifestUri:value.adapter_manifest_uri,visionAdapterManifestUri:value.vision_adapter_manifest_uri,composedAdapterManifestUri:value.composed_adapter_manifest_uri,candidateId:value.candidate_id,evaluationManifestUri:value.evaluation_manifest_uri,promotionEligible:value.promotion_eligible,error:value.error,createdAt:new Date(value.created_at).toISOString(),updatedAt:new Date(value.updated_at).toISOString()}));}
	async createRun(libraryId:string,input:{snapshotId:string;idempotencyKey:string}){const result=await this.pool.query(`INSERT INTO library_runs(library_id,snapshot_id,dataset_id,mode,state,promotion_eligible,idempotency_key) SELECT s.library_id,s.id,d.id,s.mode,'dataset',s.mode='standard',$3 FROM library_snapshots s JOIN library_datasets d ON d.snapshot_id=s.id WHERE s.id=$2 AND s.library_id=$1 AND s.state='ready' ON CONFLICT(idempotency_key) DO UPDATE SET idempotency_key=excluded.idempotency_key RETURNING id`,[libraryId,input.snapshotId,input.idempotencyKey]);if(!result.rowCount)throw new Error('A ready immutable snapshot and dataset are required');return(await this.runs(String(result.rows[0].id)))[0];}
	async updateVisionRunJob(id:string,jobId:string){await this.pool.query(`UPDATE library_runs SET vision_phase_job_id=$2,updated_at=now() WHERE id=$1`,[id,jobId]);return(await this.runs(id))[0];}
	async updateCompositionRunJob(id:string,jobId:string){await this.pool.query(`UPDATE library_runs SET composition_phase_job_id=$2,updated_at=now() WHERE id=$1`,[id,jobId]);return(await this.runs(id))[0];}
	async updateRunJob(id:string,jobId:string){await this.pool.query(`UPDATE library_runs SET phase_job_id=$2,state='training',updated_at=now() WHERE id=$1`,[id,jobId]);return(await this.runs(id))[0];}
}
