import{createHash}from'node:crypto';import{mkdtemp,readFile,rm,writeFile}from'node:fs/promises';import{tmpdir}from'node:os';import{join}from'node:path';import{describe,expect,it,vi}from'vitest';import{FilesystemArtifactRepository,hashApiKey,MemoryJobRepository}from'../../packages/common/src/index.ts';import{createTrainingControlApp}from'../../packages/training-api/src/app.ts';import{trainingArtifacts,verifyArtifacts}from'../../packages/training-api/src/artifact-storage.ts';import{trainingConfig}from'../../packages/training-api/src/config.ts';import{metadata,spool}from'../../packages/training-api/src/intake.ts';import{boundedDocumentBytes,sameDocumentRevision}from'../../packages/training-api/src/libraries.ts';
import{readFileSync}from'node:fs';
import{sameRelationshipRevision}from'../../packages/training-api/src/libraries.ts';
const record={id:'test',hash:hashApiKey('secret','salt'),scopes:['*'],revoked:false},resolveKey=async(id:string)=>id==='test'?record:null,authorization={authorization:'Bearer ak_test_secret'};
function encoded(value:unknown){return Buffer.from(JSON.stringify(value)).toString('base64url');}
describe('library document intake',()=>{
	it('validates metadata and streams a bounded checksum-verified temporary object',async()=>{const body=new Blob(['knowledge']).stream(),digest=createHash('sha256').update('knowledge').digest('hex'),value=await spool(body,digest);expect(await readFile(value.path,'utf8')).toBe('knowledge');expect(value).toMatchObject({size:9,sha256:digest});expect(metadata(encoded({externalId:'f1',filename:'a.md',relativePath:'topic/a.md'}))).toMatchObject({externalId:'f1'});await import('node:fs/promises').then(({rm})=>rm(value.directory,{recursive:true}));});
	it('rejects path escapes and checksum mismatches',async()=>{expect(()=>metadata(encoded({externalId:'f1',filename:'a',relativePath:'../a'}))).toThrow(/relative/u);await expect(spool(new Blob(['x']).stream(),'0'.repeat(64))).rejects.toThrow(/does not match/u);});
	it('validates the bounded file without materializing it and rejects size drift',async()=>{const directory=await mkdtemp(join(tmpdir(),'treeai-bounded-upload-')),path=join(directory,'upload');try{await writeFile(path,'knowledge');expect(await boundedDocumentBytes(path,9)).toBe(9);await expect(boundedDocumentBytes(path,8)).rejects.toThrow(/size changed/u);}finally{await rm(directory,{recursive:true,force:true});}});
	it('proves immutable filesystem write and read capability',async()=>{const root=await mkdtemp(join(tmpdir(),'treeai-training-artifacts-')),repository=new FilesystemArtifactRepository('training',root,['ai-training']);try{await verifyArtifacts(repository);const stored=await repository.put('library-source/digest',Buffer.from('knowledge'),'text/markdown');expect(stored).toMatchObject({uri:'artifact://training/library-source/digest',size:9});expect(Buffer.from(await repository.bytes(stored.uri)).toString()).toBe('knowledge');}finally{await rm(root,{recursive:true,force:true});}});
	it('selects filesystem by default and accepts R2 credentials only through files',async()=>{const common={DATABASE_URL:'postgres://test',AI_API_KEYS:'[]'},local=trainingConfig(common);expect(local.artifacts).toMatchObject({backend:'filesystem',root:'/artifacts',storeId:'training',legacyBuckets:['ai-training']});const root=await mkdtemp(join(tmpdir(),'treeai-r2-config-')),access=join(root,'access'),secret=join(root,'secret');try{await writeFile(access,'access-id\n');await writeFile(secret,'secret-value\n');const remote=trainingConfig({...common,ARTIFACT_BACKEND:'r2',R2_ENDPOINT:'https://account.r2.cloudflarestorage.com',R2_BUCKET:'training',R2_ACCESS_KEY_FILE:access,R2_SECRET_KEY_FILE:secret});expect(remote.artifacts).toMatchObject({backend:'r2',bucket:'training',accessKeyFile:access,secretKeyFile:secret});expect(()=>trainingArtifacts({...remote.artifacts,endpoint:'http://r2.invalid'})).toThrow(/HTTPS origin/u);}finally{await rm(root,{recursive:true,force:true});}});
	it('mounts the shared local artifact store into the established non-root worker UID',()=>{const compose=readFileSync('deploy/training/compose.yml','utf8'),dockerfile=readFileSync('containers/training/api.Dockerfile','utf8');expect(compose).toMatch(/api:\n(?:.|\n)*?volumes: \["training-artifacts:\/artifacts"\]/u);expect(dockerfile).toContain('useradd --system --uid 10001 --gid 10001');expect(dockerfile).toContain('mkdir -p /artifacts && chown training-api:training-api /artifacts');expect(dockerfile).toMatch(/USER 10001:10001\s+CMD/u);});
	it('exposes authenticated idempotent library ingestion routes',async()=>{const library={id:'library-1'},document={id:'document-1',currentRevision:{id:'revision-1'}},libraries={list:vi.fn(async()=>[library]),get:vi.fn(async()=>library),upsert:vi.fn(async()=>library),documents:vi.fn(async()=>[document]),ingest:vi.fn(async()=>document),deleteDocument:vi.fn(async()=>true),deleteExternalDocument:vi.fn(async()=>true),relationships:vi.fn(async()=>({updated:1})),snapshots:vi.fn(async()=>[]),freezeSnapshot:vi.fn(async()=>({id:'snapshot-1'}))},jobs=new MemoryJobRepository(),app=createTrainingControlApp({jobs,resolveKey,libraries: libraries as never});
		const created=await app.request('/v1/libraries',{method:'POST',headers:{...authorization,'content-type':'application/json','idempotency-key':'library-1'},body:JSON.stringify({sourceKind:'open-webui',externalId:'kb-1',slug:'docs',name:'Docs'})});expect(created.status).toBe(201);
		const digest=createHash('sha256').update('hello').digest('hex'),uploaded=await app.request('/v1/libraries/library-1/documents',{method:'POST',headers:{...authorization,'content-type':'text/markdown','idempotency-key':'upload-1','x-content-sha256':digest,'x-treeai-document':encoded({externalId:'file-1',filename:'guide.md',relativePath:'docs/guide.md'})},body:'hello'});expect(uploaded.status).toBe(202);expect(await uploaded.json()).toMatchObject({document:{id:'document-1'},job:{type:'library.document.classify',idempotencyKey:'library-document:revision-1'}});expect(libraries.ingest).toHaveBeenCalled();
		const snapshot=await app.request('/v1/libraries/library-1/snapshots',{method:'POST',headers:{...authorization,'content-type':'application/json','idempotency-key':'freeze-1'},body:JSON.stringify({mode:'smoke'})});expect(snapshot.status).toBe(201);expect(await snapshot.json()).toMatchObject({id:'snapshot-1'});expect(libraries.freezeSnapshot).toHaveBeenCalledWith('library-1','smoke');
	});
	it('keeps content ingestion independent from relationship-only revisions',()=>{const input={externalId:'file-1',filename:'guide.md',relativePath:'docs/guide.md',declaredMimeType:'text/markdown',detectedMimeType:'application/octet-stream',sha256:'a'.repeat(64),size:10},current={object_sha256:input.sha256,filename:input.filename,relative_path:'moved/guide.md',directory_external_id:'topic-1',declared_mime_type:input.declaredMimeType};expect(sameDocumentRevision(current,input)).toBe(true);expect(sameDocumentRevision({...current,object_sha256:'b'.repeat(64)},input)).toBe(false);expect(sameDocumentRevision({...current,provenance:{processingProfile:'marker-balanced-v3'}},{...input,provenance:{processingProfile:'marker-balanced-v4'}})).toBe(false);expect(sameRelationshipRevision(current,{filename:'guide.md',relativePath:'moved/guide.md',directoryExternalId:'topic-1'})).toBe(true);expect(sameRelationshipRevision(current,{relativePath:'other/guide.md'})).toBe(false);});
	it('retries only failed processing for the current document revision',async()=>{const document={id:'document-1',currentRevision:{id:'revision-1'}},libraries={documents:vi.fn(async()=>[document])},jobs=new MemoryJobRepository(),failed=await jobs.submit({type:'library.document.marker',request:{libraryId:'library-1',documentId:document.id,revisionId:document.currentRevision.id},idempotencyKey:'marker-1',maxAttempts:1});await jobs.claim('worker',[failed.type],60);await jobs.fail(failed.id,'worker',{code:'marker_failed',message:'failed'});const app=createTrainingControlApp({jobs,resolveKey,libraries:libraries as never}),response=await app.request('/v1/libraries/library-1/documents/document-1/retry',{method:'POST',headers:{...authorization,'idempotency-key':'retry-1'}}),value=await response.json()as any;expect(response.status).toBe(202);expect(value).toMatchObject({retried:true,job:{state:'queued',attempts:0,request:{revisionId:'revision-1'}}});const duplicate=await app.request('/v1/libraries/library-1/documents/document-1/retry',{method:'POST',headers:{...authorization,'idempotency-key':'retry-1'}});expect((await duplicate.json()as any).job.id).toBe(value.job.id);});
	it('recovers an unprocessed current revision without a directly failed job',async()=>{const document={id:'document-1',state:'received',currentRevision:{id:'revision-2',objectUri:'s3://bucket/object',sha256:'a'.repeat(64),filename:'guide.md',relativePath:'docs/guide.md',directoryExternalId:'topic',declaredMimeType:'text/markdown'}},libraries={documents:vi.fn(async()=>[document])},jobs=new MemoryJobRepository(),app=createTrainingControlApp({jobs,resolveKey,libraries:libraries as never}),response=await app.request('/v1/libraries/library-1/documents/document-1/retry',{method:'POST',headers:{...authorization,'idempotency-key':'recovery-1'}}),value=await response.json()as any;expect(response.status).toBe(202);expect(value).toMatchObject({retried:true,recovered:true,job:{type:'library.document.classify',request:{revisionId:'revision-2',objectUri:'s3://bucket/object'}}});});
});
