import{createHash}from'node:crypto';import{readFile}from'node:fs/promises';import{describe,expect,it,vi}from'vitest';import{hashApiKey,MemoryJobRepository}from'../../packages/common/src/index.ts';import{createTrainingControlApp}from'../../packages/training-api/src/app.ts';import{metadata,spool}from'../../packages/training-api/src/intake.ts';import{sameDocumentRevision}from'../../packages/training-api/src/libraries.ts';
const record={id:'test',hash:hashApiKey('secret','salt'),scopes:['*'],revoked:false},resolveKey=async(id:string)=>id==='test'?record:null,authorization={authorization:'Bearer ak_test_secret'};
function encoded(value:unknown){return Buffer.from(JSON.stringify(value)).toString('base64url');}
describe('library document intake',()=>{
	it('validates metadata and streams a bounded checksum-verified temporary object',async()=>{const body=new Blob(['knowledge']).stream(),digest=createHash('sha256').update('knowledge').digest('hex'),value=await spool(body,digest);expect(await readFile(value.path,'utf8')).toBe('knowledge');expect(value).toMatchObject({size:9,sha256:digest});expect(metadata(encoded({externalId:'f1',filename:'a.md',relativePath:'topic/a.md'}))).toMatchObject({externalId:'f1'});await import('node:fs/promises').then(({rm})=>rm(value.directory,{recursive:true}));});
	it('rejects path escapes and checksum mismatches',async()=>{expect(()=>metadata(encoded({externalId:'f1',filename:'a',relativePath:'../a'}))).toThrow(/relative/u);await expect(spool(new Blob(['x']).stream(),'0'.repeat(64))).rejects.toThrow(/does not match/u);});
	it('exposes authenticated idempotent library ingestion routes',async()=>{const library={id:'library-1'},document={id:'document-1',currentRevision:{id:'revision-1'}},libraries={list:vi.fn(async()=>[library]),get:vi.fn(async()=>library),upsert:vi.fn(async()=>library),documents:vi.fn(async()=>[document]),ingest:vi.fn(async()=>document),deleteDocument:vi.fn(async()=>true),deleteExternalDocument:vi.fn(async()=>true),relationships:vi.fn(async()=>({updated:1})),snapshots:vi.fn(async()=>[]),freezeSnapshot:vi.fn(async()=>({id:'snapshot-1'}))},jobs=new MemoryJobRepository(),app=createTrainingControlApp({jobs,resolveKey,libraries: libraries as never});
		const created=await app.request('/v1/libraries',{method:'POST',headers:{...authorization,'content-type':'application/json','idempotency-key':'library-1'},body:JSON.stringify({sourceKind:'open-webui',externalId:'kb-1',slug:'docs',name:'Docs'})});expect(created.status).toBe(201);
		const digest=createHash('sha256').update('hello').digest('hex'),uploaded=await app.request('/v1/libraries/library-1/documents',{method:'POST',headers:{...authorization,'content-type':'text/markdown','idempotency-key':'upload-1','x-content-sha256':digest,'x-treeai-document':encoded({externalId:'file-1',filename:'guide.md',relativePath:'docs/guide.md'})},body:'hello'});expect(uploaded.status).toBe(202);expect(await uploaded.json()).toMatchObject({document:{id:'document-1'},job:{type:'library.document.classify',idempotencyKey:'library-document:revision-1'}});expect(libraries.ingest).toHaveBeenCalled();
		const snapshot=await app.request('/v1/libraries/library-1/snapshots',{method:'POST',headers:{...authorization,'content-type':'application/json','idempotency-key':'freeze-1'},body:JSON.stringify({mode:'smoke'})});expect(snapshot.status).toBe(201);expect(await snapshot.json()).toMatchObject({id:'snapshot-1'});expect(libraries.freezeSnapshot).toHaveBeenCalledWith('library-1','smoke');
	});
	it('recognizes only byte-and-relationship-identical document revisions',()=>{const input={externalId:'file-1',filename:'guide.md',relativePath:'docs/guide.md',declaredMimeType:'text/markdown',detectedMimeType:'application/octet-stream',sha256:'a'.repeat(64),size:10};expect(sameDocumentRevision({object_sha256:input.sha256,filename:input.filename,relative_path:input.relativePath,directory_external_id:null,declared_mime_type:input.declaredMimeType},input)).toBe(true);expect(sameDocumentRevision({object_sha256:input.sha256,filename:input.filename,relative_path:'other/guide.md',directory_external_id:null,declared_mime_type:input.declaredMimeType},input)).toBe(false);});
});
