#!/usr/bin/env node
import{spawnSync}from'node:child_process';import{existsSync}from'node:fs';import{configPath,envelope,keyPath,packageNames,VERSION,type Group}from'./contracts.js';import{discover}from'./descriptors.js';
const args=process.argv.slice(2),json=args.includes('--json'),command=args[0];
const descriptions:Record<Group,string>={platform:'Platform health and reconciliation',update:'Managed release updates',mode:'Exclusive GPU mode',config:'Desired-state configuration',recovery:'Generation recovery','local-build':'Explicit local source image builds',host:'Docker and NVIDIA host runtime',inference:'Inference control',training:'Training control',lab:'Experience laboratory'};
function emit(value:unknown){process.stdout.write(`${JSON.stringify(value,null,json?2:0)}\n`);}
function fail(code:string,message:string,exit=1){if(json)emit(envelope(code,message));else process.stderr.write(`${message}\n`);process.exitCode=exit;}
function help(){const states=discover();process.stdout.write(`treeai ${VERSION}\n\nCommands:\n  version\n  packages\n  doctor\n  auth status|rotate\n`);for(const state of states)process.stdout.write(`  ${state.group.padEnd(10)} ${state.status==='installed'?descriptions[state.group]:`unavailable; install ${state.package}`}\n`);}
function dispatch(group:Group){const state=discover().find(item=>item.group===group)!;if(state.status!=='installed'||!state.descriptor)return fail('package_unavailable',`${group} is ${state.status}: ${state.message}`,state.status==='missing'?3:4);const subcommand=args[1],bare=group==='mode';if(!bare&&(!subcommand||!state.descriptor.commands.includes(subcommand)))return fail('usage',`Unsupported ${group} command ${subcommand??''}. Available: ${state.descriptor.commands.join(', ')}.`,64);if(bare&&subcommand&&!state.descriptor.commands.includes(subcommand))return fail('usage',`Mode must be awake or sleep.`,64);const manager=state.descriptor.executable.includes('/manager/'),product=state.descriptor.executable.endsWith('product-cli.js'),childArgs=manager||product?[group,...args.slice(1)]:args.slice(1),result=spawnSync('/usr/lib/treeseed-ai/runtime/bin/node',[state.descriptor.executable,...childArgs],{stdio:'inherit',env:{...process.env,TREEAI_INVOKED:'1'}});if(result.error)return fail('dispatch_failed',result.error.message);process.exitCode=result.status??1;}
function packageRecord(name:string,optional=false){const installedResult=spawnSync('dpkg-query',['-W','-f=${db:Status-Abbrev} ${Version}',name],{encoding:'utf8'}),installed=installedResult.status===0?installedResult.stdout.trim().match(/^ii\s+(\S+)$/u)?.[1]:undefined,policy=spawnSync('apt-cache',['policy',name],{encoding:'utf8'}).stdout,candidate=policy.match(/Candidate:\s+(\S+)/u)?.[1],held=spawnSync('apt-mark',['showhold'],{encoding:'utf8'}).stdout.split('\n').includes(name);return{package:name,status:installed?'installed':optional?'missing':'desired',installed,candidate:candidate==='(none)'?undefined:candidate,held,managerOwned:name!=='treeseed-ai'};}
function packages(){const states=discover(),names=['treeseed-ai','treeseed-ai-archive-keyring','treeseed-ai-development-archive-keyring','treeseed-ai-host-js-runtime','treeseed-ai-manager','treeseed-ai-cli','treeseed-ai-release-catalog','treeseed-ai-host-runtime','treeseed-ai-inference','treeseed-ai-training','treeseed-ai-lab'],records=names.map(name=>packageRecord(name,name==='treeseed-ai-lab'));emit({schemaVersion:'treeai.packages/v2',status:states.some(item=>item.status==='damaged'||item.status==='incompatible')?'blocked':'ready',version:VERSION,packages:records,commands:states});}
function doctor(){const states=discover(),issues=states.filter(item=>item.status==='damaged'||item.status==='incompatible');emit({schemaVersion:'treeai.doctor/v2',status:issues.length?'blocked':'ready',version:VERSION,config:existsSync(configPath),operatorCredential:existsSync(keyPath),packages:states});if(issues.length)process.exitCode=2;}
function auth(){if(args[1]==='status')return emit({status:existsSync(keyPath)?'ready':'blocked',credential:keyPath,configured:existsSync(keyPath)});if(args[1]==='rotate'){if(process.getuid?.()!==0)return fail('root_required','treeai auth rotate must run as root.');const result=spawnSync('/usr/lib/treeseed-ai/runtime/bin/node',['/usr/lib/treeseed-ai/manager/dist/cli.js','auth','rotate',...(json?['--json']:[])],{stdio:'inherit'});process.exitCode=result.status??1;return;}return fail('usage','Usage: treeai auth status|rotate');}
if(!command||command==='help'||command==='--help')help();else if(command==='version')emit({version:VERSION});else if(command==='packages')packages();else if(command==='doctor')doctor();else if(command==='auth')auth();else if(command in packageNames)dispatch(command as Group);else fail('usage',`Unknown command ${command}. Run treeai --help.`,64);
