#!/usr/bin/env node
import{spawnSync}from'node:child_process';import{existsSync}from'node:fs';
import{configPath,envelope,keyPath,packageNames,VERSION,type Group}from'./contracts.js';import{discover}from'./descriptors.js';

const args=process.argv.slice(2),json=args.includes('--json'),command=args[0];
const descriptions:Record<string,string>={host:'Host Docker and NVIDIA runtime',factory:'Local factory lifecycle',inference:'Inference control',training:'Training control',lab:'Experience laboratory'};
function emit(value:unknown){process.stdout.write(`${JSON.stringify(value,null,json?2:0)}\n`);}
function fail(code:string,message:string,exit=1){if(json)emit(envelope(code,message));else process.stderr.write(`${message}\n`);process.exitCode=exit;}
function help(){const states=discover();process.stdout.write(`treeai ${VERSION}\n\nCommands:\n  version\n  packages\n  doctor\n  auth status|rotate\n`);for(const state of states)process.stdout.write(`  ${state.group.padEnd(10)} ${state.status==='installed'?descriptions[state.group]:`unavailable; install ${state.package}`}\n`);}
function dispatch(group:Group){const state=discover().find((item)=>item.group===group)!;if(state.status!=='installed'||!state.descriptor)return fail('package_unavailable',`${group} is ${state.status}: ${state.message}`,state.status==='missing'?3:4);const subcommand=args[1];if(!subcommand||!state.descriptor.commands.includes(subcommand))return fail('usage',`Unsupported ${group} command ${subcommand??''}. Available: ${state.descriptor.commands.join(', ')}.`,64);const childArgs=state.descriptor.executable.endsWith('product-cli.js')?[group,...args.slice(1)]:args.slice(1),result=spawnSync(process.execPath,[state.descriptor.executable,...childArgs],{stdio:'inherit',env:{...process.env,TREEAI_INVOKED:'1'}});if(result.error)return fail('dispatch_failed',result.error.message);process.exitCode=result.status??1;}
function packageRecord(name:string,optional=false){const result=spawnSync('dpkg-query',['-W','-f=${db:Status-Abbrev} ${Version}',name],{encoding:'utf8'}),installed=result.status===0?result.stdout.trim().match(/^ii\s+(\S+)$/u)?.[1]:undefined;return{package:name,status:installed===VERSION?'installed':installed?'incompatible':optional?'missing':'damaged',version:installed,message:installed?installed===VERSION?'Installed.':`Requires ${VERSION}.`:`${name} is not installed.`};}
function packages(){const states=discover(),records=[packageRecord('treeseed-ai-cli'),...states,packageRecord('treeseed-ai-factory',true)];emit({schemaVersion:'treeai.packages/v1',status:records.some((item)=>item.status==='damaged'||item.status==='incompatible')?'blocked':'ready',version:VERSION,packages:records});}
function doctor(){const states=discover(),issues=states.filter((item)=>item.status==='damaged'||item.status==='incompatible');emit({schemaVersion:'treeai.doctor/v1',status:issues.length?'blocked':'ready',version:VERSION,config:existsSync(configPath),operatorCredential:existsSync(keyPath),packages:states});if(issues.length)process.exitCode=2;}
function auth(){if(args[1]==='status')return emit({status:existsSync(keyPath)?'ready':'blocked',credential:keyPath,configured:existsSync(keyPath)});if(args[1]==='rotate'){if(process.getuid?.()!==0)return fail('root_required','treeai auth rotate must run as root.');const state=discover().find((item)=>item.group==='factory');if(state?.status!=='installed'||!state.descriptor)return fail('package_unavailable','Install a compatible treeseed-ai-host-runtime package.');const result=spawnSync(process.execPath,[state.descriptor.executable,'configure','--rotate-client-keys',...(json?['--json']:[])],{stdio:'inherit'});process.exitCode=result.status??1;return;}return fail('usage','Usage: treeai auth status|rotate');}
if(!command||command==='help'||command==='--help')help();else if(command==='version')emit({version:VERSION});else if(command==='packages')packages();else if(command==='doctor')doctor();else if(command==='auth')auth();else if(command in packageNames)dispatch(command as Group);else fail('usage',`Unknown command ${command}. Run treeai --help.`,64);
