import{chmodSync,mkdtempSync,readFileSync,writeFileSync}from'node:fs';
import{tmpdir}from'node:os';
import{join}from'node:path';
import{afterEach,describe,expect,it,vi}from'vitest';
import{localImageReadiness}from'../../packages/manager/src/lifecycle/local-build.js';
import{assertCatalogedSimulation}from'../../packages/manager/src/lifecycle/apt-policy.js';
import{validateCatalog,type ReleaseCatalog}from'../../packages/manager/src/core/catalog.js';

const digest=`sha256:${'a'.repeat(64)}`,identity=`sha256:${'b'.repeat(64)}`;
function catalog():ReleaseCatalog{return{schemaVersion:'treeai.release-catalog/v1',release:'0.7.1-rc2',channel:'development',generation:7000003,compatibilityId:'test',classification:'automatic',automatic:true,suite:'development',signingKeyFingerprint:'A'.repeat(40),platform:{architecture:'amd64',operatingSystems:['ubuntu:26.04'],manager:'>=0.6.2',nodeRuntime:'24',nvidiaDriver:'>=570'},packages:[],images:[{role:'inference-api',repository:'treeseed/inference-api',digest,buildIdentity:identity,consumers:['inference'],restartImpact:'inference-api',firstBuildGeneration:1}],imagePolicy:{mode:'local-images-required',productionManifestVersion:'0.7.1',sourceRevision:'a'.repeat(40),sourceBundle:{url:'https://github.com/treeseed-ai/ai/releases/download/0.7.1-rc2/treeai-source.tar.gz',sha256:'f'.repeat(64),format:'tar.gz'},requiredLocalImages:[{role:'inference-api',buildIdentity:identity}]},runtimeImages:[],composeGeneration:1,configurationGeneration:1,migrations:[],gates:[],rollback:{compatible:true,requiresBackup:false},evidence:{cosignIssuer:'issuer',cosignIdentity:'identity',githubRelease:'release',sbomAssetPattern:'sbom',vulnerabilityAssetPattern:'vuln'}};}
function receipt(buildIdentity=identity){return{schemaVersion:'treeai.local-build-receipt/v1',generation:7000003,release:'0.7.1-rc2',sourceRevision:'a'.repeat(40),platform:'linux/amd64',images:[{role:'inference-api',buildIdentity,tag:'local/inference-api:test',imageId:digest,configDigest:digest,baseDigest:`sha256:${'e'.repeat(64)}`,smoke:'passed'}]};}

describe('repository-local image admission',()=>{
  const original=process.env.TREEAI_LOCAL_BUILD_RECEIPT,originalPath=process.env.PATH;
  afterEach(()=>{vi.restoreAllMocks();process.env.PATH=originalPath;if(original)process.env.TREEAI_LOCAL_BUILD_RECEIPT=original;else delete process.env.TREEAI_LOCAL_BUILD_RECEIPT;});
  it('accepts package-only generations without a receipt',()=>{const value=catalog();value.imagePolicy={...value.imagePolicy,mode:'package-only',sourceBundle:null,requiredLocalImages:[]};expect(localImageReadiness(value).ready).toBe(true);});
  it('blocks a local-image generation without its exact receipt',()=>{process.env.TREEAI_LOCAL_BUILD_RECEIPT=join(mkdtempSync(join(tmpdir(),'treeai-local-')),'missing.json');expect(localImageReadiness(catalog())).toEqual(expect.objectContaining({ready:false,reason:'local_build_receipt_missing'}));});
  it('rejects a receipt for a different build identity before image inspection',()=>{const root=mkdtempSync(join(tmpdir(),'treeai-local-')),path=join(root,'receipt.json');process.env.TREEAI_LOCAL_BUILD_RECEIPT=path;writeFileSync(path,JSON.stringify(receipt(`sha256:${'c'.repeat(64)}`)));expect(localImageReadiness(catalog())).toEqual(expect.objectContaining({ready:false,reason:'local_build_receipt_mismatch:inference-api'}));});
  it('detects a local tag moved away from its receipted image ID',()=>{const root=mkdtempSync(join(tmpdir(),'treeai-local-')),path=join(root,'receipt.json'),docker=join(root,'docker');process.env.TREEAI_LOCAL_BUILD_RECEIPT=path;process.env.PATH=`${root}:${originalPath}`;writeFileSync(path,JSON.stringify(receipt()));writeFileSync(docker,`#!/bin/sh\nprintf '{"Id":"sha256:${'d'.repeat(64)}"}'\n`);chmodSync(docker,0o755);expect(localImageReadiness(catalog())).toEqual(expect.objectContaining({ready:false,reason:'local_image_moved:inference-api'}));});
  it('automatically builds only through catalog authority before admission',()=>{const update=readFileSync('packages/manager/src/lifecycle/update.ts','utf8'),build=readFileSync('packages/manager/src/lifecycle/local-build.ts','utf8'),gate=update.slice(update.indexOf('if (\n\t\t!plan.localImages.ready'),update.indexOf('event("root-capability.started"'));expect(update).toContain('buildCatalogLocalImages(catalog)');expect(update).toContain('root-capability.started');expect(gate).toContain('config.updates.channel === "development"');expect(gate).not.toContain('config.imageSource === "local-build"');expect(build).toContain('development.local-images.build');expect(build).toContain('requiredRoles: catalog.imagePolicy.requiredLocalImages');expect(build).not.toContain('exec(');});
  it('rejects TreeAI packages introduced only by dependency solving',()=>{expect(()=>assertCatalogedSimulation('Inst treeseed-ai-manager [old] (new)\nInst treeseed-ai-lab [old] (new)',{...catalog(),packages:[{name:'treeseed-ai-manager',version:'new',architecture:'amd64',origin:'TreeSeed AI',order:0}]})).toThrow(/treeseed-ai-lab/u);});
  it('postpones before runtime image acquisition or dpkg installation',()=>{const update=readFileSync('packages/manager/src/lifecycle/update.ts','utf8'),gate=update.indexOf('if (!plan.localImages.ready)'),acquire=update.indexOf('await acquireImages(catalog)'),install=update.indexOf('event("update.installing"');expect(gate).toBeGreaterThan(0);expect(gate).toBeLessThan(acquire);expect(gate).toBeLessThan(install);});
  it('does not pull images or reconcile products for package-only bridges',()=>{const update=readFileSync('packages/manager/src/lifecycle/update.ts','utf8');expect(update).toContain('if (!packageOnly) await acquireImages(catalog)');expect(update).toContain('packageOnly ? undefined : await reconcilePlatform()');});
});
  it('validates a catalog with exact local image requirements',()=>{expect(validateCatalog(catalog()).imagePolicy.mode).toBe('local-images-required');});
  it('allows a non-pullable sentinel only for an exact development local build',()=>{const value=catalog();value.images[0]!.digest=`sha256:${'0'.repeat(64)}`;value.images[0]!.localBuildOnly=true;expect(validateCatalog(value).images[0]!.localBuildOnly).toBe(true);value.imagePolicy.requiredLocalImages=[];expect(()=>validateCatalog(value)).toThrow(/image delivery policy/u);});
  it('rejects a non-release source URL',()=>{const value=catalog();value.imagePolicy.sourceBundle={...value.imagePolicy.sourceBundle!,url:'https://example.com/source.tar.gz'};expect(()=>validateCatalog(value)).toThrow(/image delivery policy/u);});
  it('retains the prior development APT suite during publication',()=>{expect(readFileSync('.github/workflows/publish-development.yml','utf8')).toContain('mirror-apt-suite.sh https://treeseed-ai.github.io/ai/apt development pages/apt');});
