import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest';import YAML from'yaml';import{redactKnownCredentials}from'../../packages/lab/src/shared.js';import{createTrainingControlApp}from'../../packages/training-api/src/app.js';
const root=process.cwd();
describe('optional experience lab',()=>{
 it('redacts API keys, named secrets, and unrestricted home paths',()=>{const value=redactKnownCredentials('token=abc123 key ak_lab_abcdefghijklmnopqrstuvwxyz /home/alice/private.txt');expect(value).not.toContain('abc123');expect(value).not.toContain('abcdefghijklmnopqrstuvwxyz');expect(value).not.toContain('/home/alice');});
 it('publishes only the three TLS gateway ports and has no privileged mounts',()=>{const raw=readFileSync(`${root}/deploy/lab/compose.yml`,'utf8'),compose=YAML.parse(raw);expect(compose.services.gateway.ports).toHaveLength(3);expect(raw).not.toContain('/var/run/docker.sock');expect(raw).not.toMatch(/postgres/i);expect(raw).toContain('ai-shared');expect(raw).toContain('factory-inference-key');});
 it('pins Hermes and Open WebUI release inputs',()=>{expect(readFileSync(`${root}/containers/lab/hermes.Dockerfile`,'utf8')).toContain('hermes_agent-0.18.2');expect(readFileSync(`${root}/containers/lab/hermes.Dockerfile`,'utf8')).toContain('8f02155cfc84b28bd98551cd18dffec0efa9ec070dd08f90f1a850f1c779492f');expect(readFileSync(`${root}/deploy/lab/compose.yml`,'utf8')).toContain('sha256:ef3eaeb6235dd86d8ae7425e6af38272b0cea27896c0d5ae8c5cf23f886de76a');});
 it('repairs persistent volume ownership before dropping Hermes privileges',()=>{const dockerfile=readFileSync(`${root}/containers/lab/hermes.Dockerfile`,'utf8'),entrypoint=readFileSync(`${root}/containers/lab/hermes-entrypoint.sh`,'utf8');expect(dockerfile).toContain('install -d -o hermes -g hermes /home/hermes/.hermes /workspace');expect(dockerfile).toContain('ENTRYPOINT ["/usr/local/bin/hermes-entrypoint"]');expect(entrypoint).toContain('chown hermes:hermes "$HERMES_HOME" /workspace');expect(entrypoint).toContain('exec gosu hermes hermes dashboard');});
 it('keeps the Hermes password provider out of its OAuth-only auto-SSO path',()=>{const dockerfile=readFileSync(`${root}/containers/lab/hermes.Dockerfile`,'utf8'),patch=readFileSync(`${root}/containers/lab/hermes-password-auth.patch`,'utf8');expect(dockerfile).toContain('hermes-password-auth.patch');expect(patch).toContain('getattr(provider, "supports_password", False)');expect(patch).toContain('return None');});
 it('declares experience batch routes in OpenAPI 3.1.1',async()=>{const app=createTrainingControlApp({jobs:{}as any,resolveKey:async()=>null});const document=await(await app.request('/openapi.json')).json()as any;expect(document.openapi).toBe('3.1.1');expect(document.paths['/v1/experience-batches']).toBeTruthy();expect(document.paths['/v1/experience-batches/{id}/prepare']).toBeTruthy();});
 it('uses inference-based evaluation and strict promotion policy',()=>{const source=readFileSync(`${root}/workers/evaluator/worker.py`,'utf8');expect(source).toContain('/v1/chat/completions');expect(source).toContain('strict-improvement-v1');expect(source).toContain('aggregate improvement is below 0.02');expect(source).not.toContain('int(digest(item)');});
 it('uses private factory service keys and the shared operator record',()=>{const source=readFileSync(`${root}/packages/lab/src/cli.ts`,'utf8');expect(source).toContain("operator-record.json");expect(source).toContain("factory-service-key");expect(source).toContain("TREEAI_OPERATOR_KEY_VALUE");expect(source).toContain("typeof value==='string'");});
});
