import{readFileSync}from'node:fs';import{describe,expect,it}from'vitest';import YAML from'yaml';import{redactKnownCredentials}from'../../packages/lab/src/shared.js';import{createTrainingControlApp}from'../../packages/training-api/src/app.js';
const root=process.cwd();
describe('optional experience lab',()=>{
 it('redacts API keys, named secrets, and unrestricted home paths',()=>{const value=redactKnownCredentials('token=abc123 key ak_lab_abcdefghijklmnopqrstuvwxyz /home/alice/private.txt');expect(value).not.toContain('abc123');expect(value).not.toContain('abcdefghijklmnopqrstuvwxyz');expect(value).not.toContain('/home/alice');});
 it('publishes only the loopback browser and lab API ports and has no privileged mounts',()=>{const raw=readFileSync(`${root}/deploy/lab/compose.yml`,'utf8'),compose=YAML.parse(raw);expect(compose.services.gateway.ports).toHaveLength(2);expect(raw).not.toContain('/var/run/docker.sock');expect(raw).not.toMatch(/postgres/i);expect(compose.networks['lab-private'].internal).toBe(true);expect(compose.services['hermes-agent'].networks).toEqual(['lab-private']);expect(compose.services['hermes-dashboard'].networks).toEqual(['lab-private']);expect(compose.services['open-webui'].networks).toEqual(['lab-private']);expect(compose.services['web-tool-proxy'].secrets).toBeUndefined();expect(compose.services['web-tool-proxy'].volumes).toBeUndefined();expect(compose.services['web-tool-proxy'].tmpfs).toEqual(['/tmp:size=16m,mode=1777']);expect(raw).toContain('ai-shared');expect(raw).toContain('hermes-api-key');expect(raw).not.toContain(':4792:4792');});
 it('pins Hermes and obtains Open WebUI from the release catalog',()=>{expect(readFileSync(`${root}/containers/lab/hermes.Dockerfile`,'utf8')).toContain('hermes_agent-0.18.2');expect(readFileSync(`${root}/containers/lab/hermes.Dockerfile`,'utf8')).toContain('8f02155cfc84b28bd98551cd18dffec0efa9ec070dd08f90f1a850f1c779492f');const catalog=JSON.parse(readFileSync(`${root}/release/catalog.json`,'utf8'));const webui=catalog.runtimeImages.find((item:any)=>item.id==='open-webui');expect(webui.reference).toContain('v0.11.0@sha256:72c0ba641ba75e7aa52655cb242570906ececd09b1140fb736483038a22b3228');expect(readFileSync(`${root}/deploy/lab/compose.yml`,'utf8')).toContain('${OPEN_WEBUI_IMAGE:?OPEN_WEBUI_IMAGE is required}');});
 it('repairs persistent volume ownership before dropping Hermes privileges',()=>{const dockerfile=readFileSync(`${root}/containers/lab/hermes.Dockerfile`,'utf8'),entrypoint=readFileSync(`${root}/containers/lab/hermes-entrypoint.sh`,'utf8');expect(dockerfile).toContain('install -d -o hermes -g hermes /home/hermes/.hermes /workspace');expect(dockerfile).toContain('ENTRYPOINT ["/usr/local/bin/hermes-entrypoint"]');expect(entrypoint).toContain('chown hermes:hermes "$HERMES_HOME" /workspace');expect(entrypoint).toContain('exec gosu hermes hermes dashboard');expect(entrypoint).toContain('max_concurrent_runs: 2');});
 it('pins Hermes through ephemeral managed scope without persisting its API secret',()=>{const entrypoint=readFileSync(`${root}/containers/lab/hermes-entrypoint.sh`,'utf8');expect(entrypoint).toContain('HERMES_MANAGED_DIR');expect(entrypoint).toContain('$managed/config.yaml');expect(entrypoint).toContain('$managed/.env');expect(entrypoint).toContain('cat /run/secrets/hermes-api-key');expect(entrypoint).not.toContain('$HERMES_HOME/.env');expect(entrypoint).not.toContain('$HERMES_HOME/config.yaml');});
 it('keeps the control gateway reachable while an agent dependency is degraded',()=>{const compose=YAML.parse(readFileSync(`${root}/deploy/lab/compose.yml`,'utf8'));expect(compose.services.controller.depends_on).toEqual({'experience-proxy':{condition:'service_healthy'}});expect(compose.services.gateway.depends_on).toBeUndefined();});
 it('correlates inner Hermes model calls through managed middleware',()=>{const plugin=readFileSync(`${root}/containers/lab/treeai-web-plugin/__init__.py`,'utf8');expect(plugin).toContain('ctx.register_middleware("llm_request", correlate_llm_request)');expect(plugin).toContain('x-treeai-hermes-session-id');expect(plugin).toContain('x-treeai-hermes-turn-id');});
 it('keeps the Hermes password provider out of its OAuth-only auto-SSO path',()=>{const dockerfile=readFileSync(`${root}/containers/lab/hermes.Dockerfile`,'utf8'),patch=readFileSync(`${root}/containers/lab/hermes-password-auth.patch`,'utf8');expect(dockerfile).toContain('hermes-password-auth.patch');expect(patch).toContain('getattr(provider, "supports_password", False)');expect(patch).toContain('return None');});
 it('declares experience batch routes in OpenAPI 3.1.1',async()=>{const app=createTrainingControlApp({jobs:{}as any,resolveKey:async()=>null});const document=await(await app.request('/openapi.json')).json()as any;expect(document.openapi).toBe('3.1.1');expect(document.paths['/v1/experience-batches']).toBeTruthy();expect(document.paths['/v1/experience-batches/{id}/prepare']).toBeTruthy();});
 it('uses inference-based evaluation and strict promotion policy',()=>{const source=readFileSync(`${root}/workers/evaluator/worker.py`,'utf8');expect(source).toContain('/v1/chat/completions');expect(source).toContain('strict-improvement-v1');expect(source).toContain('aggregate improvement is below 0.02');expect(source).not.toContain('int(digest(item)');});
 it('uses manager-owned configuration and fixed supervisor operations',()=>{const source=readFileSync(`${root}/packages/lab/src/cli.ts`,'utf8');expect(source).toContain('TREEAI_OPERATOR_KEY_VALUE');expect(source).toContain('lab.webui.configure');expect(source).toContain('lab.webui.reset');expect(source).not.toContain('factory-inference-key');});
});
